const defaultFields = {
  works: [
    "doi",
    "authorships",
    "locations",
    "primary_topic.id",
    "institutions_distinct_count",
    "referenced_works_count",
    "cited_by_count",
  ],
  sources: [
    "id",
    "display_name",
    "issn_l",
    "issn",
    "type",
    "host_organization",
    "host_organization_name",
    "host_organization_lineage",
    "works_count",
    "cited_by_count",
    "is_oa",
    "is_in_doaj",
    "is_core",
    "ids",
    "homepage_url",
    "country_code",
    "alternate_titles",
    "abbreviated_title",
    "topics",
    "counts_by_year",
  ],
  publishers: [
    "id",
    "display_name",
    "alternate_titles",
    "hierarchy_level",
    "parent_publisher",
    "country_codes",
    "homepage_url",
    "image_url",
    "image_thumbnail_url",
  ],
  languages: [
    "id",
    "display_name",
  ],
};

const schema = {
  works: {
    abstract_inverted_index: "object",
    authorships: "array|<5%",
    apc_list: "object",
    apc_paid: "object",
    "best_oa_location.source.display_name": "string",
    "best_oa_location.source.type": "string",
    "best_oa_location.source.is_oa": "boolean",
    "best_oa_location.source.is_in_doaj": "boolean",
    "best_oa_location.source.version": "string",
    "best_oa_location.source.license": "string",
    biblio: "object",
    citation_normalized_percentile: "object",
    cited_by_api_url: "string",
    cited_by_count: "number|<5%",
    concepts: "array",
    corresponding_author_ids: "array",
    corresponding_institution_ids: "array",
    countries_distinct_count: "number",
    counts_by_year: "array",
    created_date: "string",
    display_name: "string",
    doi: "string",
    fulltext_origin: "string",
    fwci: "number",
    grants: "array",
    has_fulltext: "boolean",
    id: "string",
    ids: "object",
    indexed_in: "array",
    institutions_distinct_count: "number|<5%",
    is_paratext: "boolean",
    is_retracted: "boolean",
    keywords: "array",
    language: "string",
    license: "string",
    locations: "array|≥",
    locations_count: "number|≥",
    mesh: "array",
    open_access: "object",
    "open_access.oa_status": "string",
    "primary_location.source.display_name": "string",
    "primary_location.source.type": "string",
    "primary_location.source.is_oa": "boolean",
    "primary_location.source.is_in_doaj": "boolean",
    "primary_location.source.version": "string",
    "primary_location.source.license": "string",
    primary_topic: "object",
    "primary_topic.id": "string",
    publication_date: "string",
    publication_year: "number",
    referenced_works_count: "number|<5%",
    referenced_works: "array",
    related_works: "array",
    sustainable_development_goals: "array",
    topics: "array",
    title: "string",
    type: "string",
    type_crossref: "string",
  },
  sources: {
    id: "string",
    issn_l: "string",
    issn: "array",
    display_name: "string",
    host_organization: "null",
    host_organization_name: "null",
    host_organization_lineage: "array",
    works_count: "number",
    cited_by_count: "number",
    summary_stats: "object",
    is_oa: "boolean",
    is_in_doaj: "boolean",
    is_indexed_in_scopus: "boolean",
    is_core: "boolean",
    ids: "object",
    homepage_url: "string",
    apc_prices: "null",
    apc_usd: "null",
    country_code: "string",
    societies: "null",
    alternate_titles: "array",
    abbreviated_title: "null",
    type: "string",
    topics: "array",
    topic_share: "array",
    x_concepts: "array",
    counts_by_year: "array",
    works_api_url: "string",
    updated_date: "string",
    created_date: "string"
  },
  publishers: {
    id: "string",
    display_name: "string",
    alternate_titles: "array",
    hierarchy_level: "number",
    parent_publisher: "null",
    lineage: "array",
    country_codes: "array",
    homepage_url: "null",
    image_url: "null",
    image_thumbnail_url: "null",
    works_count: "number",
    cited_by_count: "number",
    summary_stats: "object",
    ids: "object",
    counts_by_year: "array",
    roles: "array",
    sources_api_url: "string",
    updated_date: "string",
    created_date: "string"
  },
  languages: {
    id: "string",
    display_name: "string",
    works_count: "number",
    cited_by_count: "number",
    works_api_url: "string",
    updated_date: "string",
    created_date: "string"
  }
};

const fieldIcons = {
    "title": "mdi-format-title",
    "publication_year": "mdi-calendar-month",

    "primary_location.is_oa": "mdi-lock-open-outline",
    "primary_location.source.id": "mdi-map-marker-account",
    "primary_location.source.is_in_doaj": "mdi-map-marker-check",
    "primary_location.source.is_core": "mdi-map-marker-check",
    "primary_location.source.is_indexed_in_scopus": "mdi-map-marker-check",
    "primary_location.source.host_organization": "mdi-map-marker-star",

    "best_oa_location.source.id": "mdi-map-marker-account-outline",
    "best_oa_location.source.pdf_url": "mdi-file-pdf-box",
    "best_oa_location.source.license": "mdi-license",
    "best_oa_location.source.is_accepted": "mdi-map-marker-check-outline",
    "best_oa_location.source.is_published": "mdi-map-marker-check-outline",
    "best_oa_location.source.is_in_doaj": "mdi-map-marker-check-outline",

    "open_access.is_oa": "mdi-lock-open-outline",
    "open_access.oa_status": "mdi-lock-percent-open-outline",
    "open_access.any_repository_has_fulltext": "mdi-file-lock-open-outline",

    "language": "mdi-translate",
    "type": "mdi-shape-outline",
    "indexed_in": "mdi-database-outline",
    "is_retracted": "mdi-file-excel-outline",
    "locations_count": "mdi-map-marker-multiple-outline",
    "referenced_works_count": "mdi-book-arrow-down-outline",
    "related_works": "mdi-book-arrow-down-outline",
    "abstract_inverted_index": "mdi-text-box-outline",
    "grants": "mdi-cash",

    "authorships": "mdi-account-multiple-outline",
    "authorships.id": "mdi-account-multiple-check-outline",
    "authorships.institutions.id": "mdi-town-hall",
    "authorships.countries": "mdi-earth",
    "corresponding_author_ids": "mdi-account-check-outline",

    "apc_list.value_usd": "mdi-currency-usd",
    "apc_paid.value_usd": "mdi-currency-usd",

    "primary_topic.id": "mdi-tag-outline",
    "topics.id": "mdi-tag-text-outline",
    "keywords": "mdi-alpha-k",
    "concepts.id": "mdi-lightbulb-outline",
    "sustainable_development_goals.id": "mdi-sprout-outline",
};

export {
  defaultFields,
  schema,
  fieldIcons,
};