/**
 * oxjob #378 V1 — differential gate for the chip-hydration cutover (C1).
 *
 * #378 moves the SOURCE of basic-chip hydration from the raw route (`?filter=`)
 * to the server's canonical `meta.x_query.url` (the server is the source of truth
 * for how a query is interpreted). Before flipping that source (C1), this gate
 * proves the cutover is safe: for a popularity-weighted sample of real filter URLs
 * (#323 corpus), hydrating chips from `x_query.url` must produce the SAME API call
 * as hydrating from the raw route — i.e. `filtersAsUrlStr(filtersFromUrlStr(route))`
 * ≡ `filtersAsUrlStr(filtersFromUrlStr(x_query.url))`, modulo canonicalization.
 *
 * The server canonicalizes (reorders clauses, sorts pipe-OR options, normalizes
 * ranges / De Morgan), so equivalence is asserted as the SAME QUERY, not byte-
 * equality: both serialized filter strings are normalized (clauses sorted, options
 * within each clause sorted) before comparison. Order-only differences are the
 * expected, accepted shape; anything else is a real divergence to triage.
 *
 * Fixture (real server responses) lives in the job dir, regenerated by:
 *   cd ~/Documents/oxjobs/working/gui-oqo-source-of-truth/work/v1-gate
 *   SAMPLE_SIZE=400 python3 gen_fixture.py
 * The gate is `it.skipIf(no fixture)` so clean CI (no network) is a no-op.
 *
 * Run: npx vitest run xQueryHydration
 */
import { describe, it, expect } from "vitest";
import fs from "fs";
import path from "path";

import { filtersFromUrlStr, filtersAsUrlStr } from "@/filterConfigs";

const FIXTURE = path.resolve(
    __dirname,
    "../../../oxjobs/working/gui-oqo-source-of-truth/work/v1-gate/fixture.json",
);
const REPORT = path.resolve(
    __dirname,
    "../../../oxjobs/working/gui-oqo-source-of-truth/work/v1-gate/gate-report.json",
);

// --- order-insensitive normalization of a filter string (the "same query" key) ---

// Quote-aware top-level comma split — mirrors filterConfigs.splitFilterString
// (not exported). Filter clauses are comma-separated; quoted values may embed commas.
function splitClauses(s) {
    const parts = [];
    let cur = "", inQ = false;
    for (const ch of s) {
        if (ch === '"') { inQ = !inQ; cur += ch; }
        else if (ch === "," && !inQ) { if (cur) parts.push(cur); cur = ""; }
        else cur += ch;
    }
    if (cur) parts.push(cur);
    return parts;
}

// Normalize one `key:value` clause: split the value on the OR/AND separator,
// sort the options, preserve the separator + leading negation. (Sorting options
// mirrors the server canonicalization that sorts pipe-OR values.)
function normClause(clause) {
    const m = clause.match(/^(.*?)(?<!http|https):([\s\S]*)$/);
    if (!m) return clause;
    const key = m[1];
    let val = m[2];
    let neg = "";
    if (val.startsWith("!")) { neg = "!"; val = val.slice(1); }
    const sep = val.includes("+") ? "+" : "|";
    const opts = val.split(/[+|]/).sort();
    return `${key}:${neg}${opts.join(sep)}`;
}

function normFilter(s) {
    if (!s) return "";
    return splitClauses(s).map(normClause).sort().join(",");
}

// The API call a given filter-source produces, run through the real chip
// round-trip (parse -> chips -> serialize), then order-normalized.
function chipQuery(entityType, filterStr) {
    return normFilter(filtersAsUrlStr(filtersFromUrlStr(entityType, filterStr)));
}

const haveFixture = fs.existsSync(FIXTURE);
const rows = haveFixture ? JSON.parse(fs.readFileSync(FIXTURE, "utf8")) : [];

// Divergence categories we've inspected and accept: canonicalization that changes
// chip STRUCTURE but not query meaning. Decided with Jason (2026-06-07):
//   SEARCH_RESTRUCTURE — a boolean `*.search` expression (`(A AND B)` / `(A OR B)`)
//   is canonicalized into AND'd search clauses / a pipe-OR value. Semantically
//   identical, advanced/rare, and arguably clearer as chips. (Bounded RANGES are
//   NOT accepted here — they're fixed at the source by #378 S4's range-collapse, so
//   they must hydrate identically; a range reappearing here is a real regression.)
const ACCEPTED_CATEGORIES = new Set([
    "SEARCH_RESTRUCTURE",
]);

const clauseKey = (clause) => (clause.split(/(?<!http|https):/)[0] || "");
const isSearchClause = (clause) => /\.search$|(^|\.)search$/.test(clauseKey(clause))
    || clauseKey(clause).endsWith(".search");

function classify(row, qRoute, qXq) {
    const a = new Set(splitClauses(qRoute));
    const b = new Set(splitClauses(qXq));
    const differing = [
        ...[...a].filter((c) => !b.has(c)),
        ...[...b].filter((c) => !a.has(c)),
    ];
    // Accepted iff EVERY clause that differs is a search clause — i.e. the only
    // thing canonicalization reshaped is a boolean search. Anything touching a
    // non-search clause (ranges, entity filters, …) is a real, unaccepted diverge.
    if (differing.length && differing.every(isSearchClause)) return "SEARCH_RESTRUCTURE";
    if (b.size > a.size && [...b].some((c) => /:[<>]/.test(c) || /:\d+-\d+/.test(c)))
        return "RANGE_SPLIT";
    if (a.size !== b.size) return "CLAUSE_COUNT_DIFF";
    return "VALUE_DIFF";
}

describe("oxjob #378 V1 — chip hydration: route ≡ x_query.url (same API call)", () => {
    it.skipIf(!haveFixture)(
        "hydrating chips from x_query.url yields the same query as from the route",
        () => {
            const report = {
                generated_at: new Date().toISOString(),
                fixture_rows: rows.length,
                summary: { ok: 0, match: 0, diverge: 0, skipped_status: 0, classified: {} },
                divergences: [],
            };

            for (const row of rows) {
                if (row.status !== "ok" || !row.x_query_filter) {
                    report.summary.skipped_status += 1;
                    continue;
                }
                report.summary.ok += 1;
                const qRoute = chipQuery(row.entity_type, row.route_filter);
                const qXq = chipQuery(row.entity_type, row.x_query_filter);
                if (qRoute === qXq) {
                    report.summary.match += 1;
                    continue;
                }
                const category = classify(row, qRoute, qXq);
                report.summary.classified[category] =
                    (report.summary.classified[category] || 0) + 1;
                report.divergences.push({
                    entity_type: row.entity_type,
                    route_filter: row.route_filter,
                    x_query_filter: row.x_query_filter,
                    q_from_route: qRoute,
                    q_from_x_query: qXq,
                    category,
                    accepted: ACCEPTED_CATEGORIES.has(category),
                });
                if (!ACCEPTED_CATEGORIES.has(category)) report.summary.diverge += 1;
            }

            fs.writeFileSync(REPORT, JSON.stringify(report, null, 2));

            expect(report.summary.ok, "fixture had no ok rows").toBeGreaterThan(0);
            // Hard gate: zero UNACCEPTED divergences. A failure prints the report path
            // + the first few divergences so they can be triaged (and, if benign,
            // added to ACCEPTED_CATEGORIES).
            const unaccepted = report.divergences.filter((d) => !d.accepted);
            expect(
                unaccepted.length,
                `${unaccepted.length} unaccepted chip-hydration divergence(s). `
                + `Report: ${REPORT}\nFirst few:\n`
                + JSON.stringify(unaccepted.slice(0, 5), null, 2),
            ).toBe(0);
        },
    );
});
