#!/usr/bin/env python3
"""Generate src/oqlCorpus.js from the OQL v2 normative corpus (oxjob #330, #345).

The corpus lives in the sibling openalex-elastic-api repo
(docs/oql/corpus.yaml). It is the single source of truth; this script copies it
into the GUI as a plain JS module (like src/countries.js) so the OQL playground's
Cases subpage can render it with no runtime YAML dependency or backend call.

PURE yaml->js copy (oxjob #384): every field the playground needs is now
precomputed IN the corpus by openalex-elastic-api/docs/oql/regen_corpus_oql.py —
the canonical `oql`, the materialized `oqo` (every ok row, incl. row 78), the
rendered `oxurl`, and the authored `oxurl_status`. So this script no longer
shells out to the elastic-api OQL parser/venv; it has NO dependency beyond
pyyaml. Re-run whenever corpus.yaml changes, then commit the regenerated JS.

    python3 scripts/gen_oql_corpus.py            # write src/oqlCorpus.js
    python3 scripts/gen_oql_corpus.py --check     # exit 1 if the mirror is stale

`--check` is the drift gate: it fails if src/oqlCorpus.js is not a byte-exact
copy of a fresh build from corpus.yaml, so the playground can never silently
show data older than the corpus. Requires the openalex-elastic-api repo as a
sibling dir (for corpus.yaml); pyyaml is the only Python dependency.
"""
import argparse
import json
import os
import sys

import yaml

HERE = os.path.dirname(os.path.abspath(__file__))
GUI_ROOT = os.path.dirname(HERE)
ELASTIC_API = os.path.normpath(os.path.join(GUI_ROOT, "..", "openalex-elastic-api"))
CORPUS_YAML = os.path.join(ELASTIC_API, "docs", "oql", "corpus.yaml")
OUT_JS = os.path.join(GUI_ROOT, "src", "oqlCorpus.js")


def build_js(corpus: dict) -> str:
    """Render the oqlCorpus.js module text from the parsed corpus dict."""
    out = []
    for row in corpus["rows"]:
        prov = row.get("provenance") or {}
        out.append({
            "id": row["id"],
            "tags": row.get("tags", []),
            "provenance": {
                "type": prov.get("type", ""),
                "label": prov.get("label", ""),
                "url": prov.get("url") or None,
            },
            # oxurl_status (#384): the 4-way taxonomy on ok/hint rows; null on
            # error / out-of-scope rows (the playground keys those off `status`).
            # Field order matches the historical generator (oqo/oxurl last) to keep
            # the regenerated mirror's diff focused on real changes.
            "oxurl_status": row.get("oxurl_status"),
            "status": row["status"],
            "oql": row["oql"],
            "note": row.get("note", ""),
            "diagnostic": row.get("diagnostic", ""),
            "oqo": row.get("oqo"),
            "oxurl": row.get("oxurl"),
        })

    body = json.dumps(out, indent=2, ensure_ascii=False)
    header = (
        "// AUTO-GENERATED by scripts/gen_oql_corpus.py -- do not edit by hand.\n"
        "// Source of truth: openalex-elastic-api/docs/oql/corpus.yaml (oxjob #330).\n"
        "// A pure yaml->js copy (oxjob #384): the canonical `oql`, materialized\n"
        "// `oqo`, rendered `oxurl`, and authored `oxurl_status` are all precomputed\n"
        "// in the corpus by its regen script, so this mirror needs no live parser.\n"
        "// `oxurl_status` (ok rows): has-oxurl | oql-only | translator-bug |\n"
        "// server-unsupported. `oxurl` is null for oql-only rows. See #345 / #384.\n"
        f"// corpus version: {corpus.get('version')}; rows: {len(out)}.\n\n"
    )
    return header + f"export const oqlCorpus = {body};\n"


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if src/oqlCorpus.js is stale vs corpus.yaml "
                         "(don't write); used by the CI drift gate")
    args = ap.parse_args()

    if not os.path.exists(CORPUS_YAML):
        sys.exit(f"corpus not found: {CORPUS_YAML}\n"
                 "expected openalex-elastic-api as a sibling repo")
    with open(CORPUS_YAML) as f:
        corpus = yaml.safe_load(f)
    fresh = build_js(corpus)

    if args.check:
        current = ""
        if os.path.exists(OUT_JS):
            with open(OUT_JS) as f:
                current = f.read()
        if current != fresh:
            sys.stderr.write(
                "src/oqlCorpus.js is STALE vs corpus.yaml — run "
                "`python3 scripts/gen_oql_corpus.py` and commit.\n")
            return 1
        print(f"src/oqlCorpus.js is up to date ({len(corpus['rows'])} rows).")
        return 0

    with open(OUT_JS, "w") as f:
        f.write(fresh)

    rows = corpus["rows"]
    ok = sum(1 for r in rows if r["status"] in ("ok", "hint"))
    withurl = sum(1 for r in rows if r.get("oxurl"))
    print(f"wrote {OUT_JS}: {len(rows)} rows ({ok} ok); {withurl} with oxurl.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
