// copy/pasted from https://api.openalex.org/entities/config

export const oaxConfigs = {
    "works": {
        "id": "works",
        "icon": "mdi-file-document-outline",
        "name": "works",
        "nameSingular": "work",
        "displayName": "works",
        "displayNameSingular": "work",
        "descr": "Scholarly papers, books, datasets, etc.",
        "eg": "On the Electrodynamics of Moving Bodies",
        "placeholder": "Search scholarly papers, books, and more",
        "filterName": "work",
        "filterKey": "ids.openalex",
        "hintVerb": "by",
        "color": "blue",
        "hasAutocomplete": true,
        "isNative": true,
        "hasSerp": true,
        "highlightFilters": [{
            "key": "open_access.is_oa",
            "value": true,
            "displayName": "Open Access works"
        }, {
            "key": "institutions.is_global_south",
            "value": true,
            "displayName": "from the Global South"
        }, {"key": "type", "value": "dataset", "displayName": "datasets"}],
        "idRegex": "(?i)(?:works\\/)?(?:https:\\/\\/openalex\\.org\\/)?(w\\d+)",
        "rowsToShowOnEntityPage": ["id", "display_name", "publication_year", "type", "abstract_inverted_index", "primary_location.source.id", "authorships.author.id", "authorships.institutions.id", "primary_topic.id", "primary_topic.subfield.id", "primary_topic.field.id", "primary_topic.domain.id", "sustainable_development_goals.id", "open_access.oa_status", "apc_paid.value_usd", "grants.funder", "grants.award_id"],
        "rowsToShowOnTablePage": ["display_name", "publication_year", "type", "primary_location.source.id", "authorships.author.id", "authorships.institutions.id", "primary_topic.id", "primary_topic.subfield.id", "primary_topic.field.id", "primary_topic.domain.id", "sustainable_development_goals.id", "open_access.oa_status"],
        "groupByDefaults": ["publication_year", "open_access.is_oa", "primary_topic.id", "authorships.institutions.lineage", "type"],
        "properties": {
            "id": {
                "id": "id",
                "subjectEntity": "works",
                "entityId": "works",
                "objectEntity": "works",
                "displayName": "OpenAlex ID",
                "isSingleWork": true,
                "isId": true,
                "newType": "string",
                "category": "ids",
                "actions": [""],
                "icon": "mdi-file-document-outline"
            },
            "works": {
                "id": "works",
                "subjectEntity": "works",
                "entityId": "works",
                "objectEntity": "works",
                "displayName": "OpenAlex ID",
                "isSingleWork": true,
                "isId": true,
                "newType": "string",
                "category": "ids",
                "actions": [""],
                "icon": "mdi-file-document-outline"
            },
            "doi": {
                "id": "doi",
                "subjectEntity": "works",
                "entityId": "works",
                "objectEntity": "works",
                "displayName": "DOI",
                "isSingleWork": true,
                "isId": true,
                "newType": "string",
                "category": "ids",
                "actions": [],
                "icon": "mdi-file-document-outline"
            },
            "concepts.id": {
                "id": "concepts.id",
                "isList": true,
                "subjectEntity": "works",
                "displayName": "concept",
                "entityId": "concepts",
                "objectEntity": "concepts",
                "newType": "entity",
                "category": "other",
                "actions": [],
                "actionsPopular": [],
                "icon": "mdi-tag-outline"
            },
            "primary_topic.id": {
                "id": "primary_topic.id",
                "subjectEntity": "works",
                "displayName": "topic",
                "entityId": "topics",
                "objectEntity": "topics",
                "newType": "entity",
                "category": "other",
                "actions": ["filter", "group_by"],
                "actionsPopular": ["filter", "group_by"],
                "icon": "mdi-tag-outline"
            },
            "keywords.id": {
                "id": "keywords.id",
                "isList": true,
                "subjectEntity": "works",
                "displayName": "keyword",
                "entityId": "keywords",
                "objectEntity": "keywords",
                "newType": "entity",
                "category": "other",
                "actions": ["filter", "group_by"],
                "actionsPopular": ["filter", "group_by"],
                "icon": "mdi-tag-outline"
            },
            "primary_topic.subfield.id": {
                "id": "primary_topic.subfield.id",
                "subjectEntity": "works",
                "displayName": "subfield",
                "entityId": "subfields",
                "objectEntity": "subfields",
                "newType": "entity",
                "category": "other",
                "actions": ["filter", "group_by"],
                "actionsPopular": [],
                "icon": "mdi-tag-outline"
            },
            "primary_topic.field.id": {
                "id": "primary_topic.field.id",
                "subjectEntity": "works",
                "displayName": "field",
                "entityId": "fields",
                "objectEntity": "fields",
                "newType": "entity",
                "category": "other",
                "actions": ["filter", "group_by"],
                "actionsPopular": [],
                "icon": "mdi-tag-outline"
            },
            "primary_topic.domain.id": {
                "id": "primary_topic.domain.id",
                "subjectEntity": "works",
                "displayName": "domain",
                "entityId": "domains",
                "objectEntity": "domains",
                "newType": "entity",
                "category": "other",
                "actions": ["filter", "group_by"],
                "actionsPopular": [],
                "icon": "mdi-tag-outline"
            },
            "grants.funder": {
                "id": "grants.funder",
                "isList": true,
                "subjectEntity": "works",
                "displayName": "funder",
                "entityId": "funders",
                "objectEntity": "funders",
                "newType": "entity",
                "category": "other",
                "actions": ["filter", "group_by"],
                "icon": "mdi-cash-multiple"
            },
            "grants.award_id": {
                "id": "grants.award_id",
                "isList": true,
                "subjectEntity": "works",
                "displayName": "grant ID",
                "newType": "string",
                "category": "other",
                "actions": [],
                "icon": "mdi-cash-multiple"
            },
            "authorships.institutions.id": {
                "id": "authorships.institutions.id",
                "isList": true,
                "subjectEntity": "works",
                "displayName": "institutions",
                "entityId": "institutions",
                "objectEntity": "institutions",
                "newType": "entity",
                "category": "institution",
                "actions": ["filter", "group_by"],
                "actionsPopular": ["filter", "group_by"],
                "icon": "mdi-town-hall"
            },
            "authorships.institutions.ror": {
                "id": "authorships.institutions.ror",
                "isList": true,
                "subjectEntity": "works",
                "entityId": "institutions",
                "objectEntity": "institutions",
                "displayName": "ROR ID",
                "isId": true,
                "newType": "string",
                "category": "ids",
                "actions": [],
                "icon": "mdi-town-hall"
            },
            "authorships.author.id": {
                "id": "authorships.author.id",
                "isList": true,
                "subjectEntity": "works",
                "displayName": "authors",
                "entityId": "authors",
                "objectEntity": "authors",
                "newType": "entity",
                "category": "author",
                "actions": ["filter", "group_by"],
                "actionsPopular": ["filter", "group_by"],
                "icon": "mdi-account-outline"
            },
            "authorships.author.orcid": {
                "id": "authorships.author.orcid",
                "isList": true,
                "subjectEntity": "works",
                "entityId": "authors",
                "objectEntity": "authors",
                "displayName": "ORCID",
                "isId": true,
                "newType": "string",
                "category": "ids",
                "actions": [],
                "icon": "mdi-account-outline"
            },
            "default.search": {
                "id": "default.search",
                "subjectEntity": "works",
                "displayName": "fulltext",
                "newType": "string",
                "actions": ["filter"],
                "actionsPopular": ["filter"],
                "category": "other",
                "icon": "mdi-magnify"
            },
            "title_and_abstract.search": {
                "id": "title_and_abstract.search",
                "subjectEntity": "works",
                "displayName": "title & abstract",
                "newType": "string",
                "actions": ["filter"],
                "actionsPopular": [],
                "category": "other",
                "icon": "mdi-magnify"
            },
            "display_name.search": {
                "id": "display_name.search",
                "subjectEntity": "works",
                "displayName": "title",
                "actions": ["filter"],
                "actionsPopular": [],
                "newType": "string",
                "icon": "mdi-magnify"
            },
            "raw_affiliation_strings.search": {
                "id": "raw_affiliation_strings.search",
                "subjectEntity": "works",
                "displayName": "raw affiliation string",
                "newType": "string",
                "actions": ["filter"],
                "actionsPopular": [""],
                "category": "other",
                "icon": "mdi-magnify"
            },
            "doi_starts_with": {
                "id": "doi_starts_with",
                "subjectEntity": "works",
                "displayName": "DOI prefix",
                "newType": "string",
                "actions": ["filter"],
                "actionsPopular": [],
                "category": "other",
                "icon": "mdi-magnify",
                "verb": "starts with"
            },
            "display_name": {
                "id": "display_name",
                "isColumnMandatory": true,
                "subjectEntity": "works",
                "displayName": "title",
                "newType": "string",
                "actions": ["sort", "column"],
                "actionsPopular": ["sort", "column"],
                "category": "other",
                "icon": "mdi-file-document-outline"
            },
            "title": {
                "id": "title",
                "isColumnMandatory": false,
                "subjectEntity": "works",
                "displayName": "title",
                "newType": "string",
                "actions": ["sort", "column"],
                "actionsPopular": ["sort", "column"],
                "category": "other",
                "icon": "mdi-file-document-outline"
            },
            "has_abstract": {
                "id": "has_abstract",
                "subjectEntity": "works",
                "displayName": "Abstract available",
                "newType": "boolean",
                "actions": ["filter"],
                "icon": "mdi-file-document-outline"
            },
            "authors_count": {
                "id": "authors_count",
                "subjectEntity": "works",
                "displayName": "authors count",
                "newType": "number",
                "sortByValue": true,
                "category": "author",
                "actions": ["filter", "sort", "column"],
                "icon": "mdi-account-outline"
            },
            "corresponding_author_ids": {
                "id": "corresponding_author_ids",
                "isList": true,
                "subjectEntity": "works",
                "entityId": "authors",
                "objectEntity": "authors",
                "displayName": "corresponding author",
                "newType": "entity",
                "category": "author",
                "actions": ["filter", "group_by"],
                "icon": "mdi-email-outline"
            },
            "open_access.is_oa": {
                "id": "open_access.is_oa",
                "subjectEntity": "works",
                "displayName": "open access",
                "newType": "boolean",
                "actions": ["filter", "column", "group_by"],
                "actionsPopular": ["filter", "column", "group_by"],
                "category": "open access",
                "icon": "mdi-lock-open-outline"
            },
            "best_oa_location.license": {
                "id": "best_oa_location.license",
                "subjectEntity": "works",
                "entityId": "licenses",
                "displayName": "license",
                "isId": true,
                "newType": "entity",
                "actions": ["filter", "column", "group_by"],
                "category": "open access",
                "icon": "mdi-lock-open-outline",
                "displayNullAs": "All rights reserved"
            },
            "open_access.oa_status": {
                "id": "open_access.oa_status",
                "subjectEntity": "works",
                "displayName": "oa status",
                "newType": "string",
                "actions": [],
                "category": "open access",
                "icon": "mdi-lock-open-outline"
            },
            "best_oa_location.is_accepted": {
                "id": "best_oa_location.is_accepted",
                "subjectEntity": "works",
                "displayName": "open access accepted",
                "newType": "boolean",
                "actions": ["filter", "column", "group_by"],
                "category": "open access",
                "icon": "mdi-lock-open-outline"
            },
            "best_oa_location.is_published": {
                "id": "best_oa_location.is_published",
                "subjectEntity": "works",
                "displayName": "open access published",
                "newType": "boolean",
                "actions": ["filter", "column", "group_by"],
                "category": "open access",
                "icon": "mdi-lock-open-outline"
            },
            "apc_paid.value_usd": {
                "id": "apc_paid.value_usd",
                "isCurrency": true,
                "subjectEntity": "works",
                "displayName": "APC paid (est)",
                "newType": "number",
                "sortByValue": true,
                "actions": ["filter"],
                "icon": "mdi-cash"
            },
            "authorships.countries": {
                "id": "authorships.countries",
                "isList": true,
                "subjectEntity": "works",
                "entityId": "countries",
                "objectEntity": "countries",
                "displayName": "Country",
                "newType": "entity",
                "isCountry": true,
                "actions": ["filter", "column", "group_by"],
                "actionsPopular": ["group_by"],
                "category": "institution",
                "icon": "mdi-earth"
            },
            "countries_distinct_count": {
                "id": "countries_distinct_count",
                "subjectEntity": "works",
                "displayName": "countries count",
                "newType": "number",
                "sortByValue": true,
                "examples": ["1", "2-", "2-10"],
                "actions": ["filter", "sort", "column"],
                "category": "institution",
                "icon": "mdi-earth"
            },
            "institutions_distinct_count": {
                "id": "institutions_distinct_count",
                "subjectEntity": "works",
                "displayName": "institutions count",
                "newType": "number",
                "sortByValue": true,
                "examples": ["1", "2-", "2-10"],
                "actions": ["filter", "sort", "column"],
                "category": "institution",
                "icon": "mdi-earth"
            },
            "authorships.institutions.continent": {
                "id": "authorships.institutions.continent",
                "isList": true,
                "subjectEntity": "works",
                "entityId": "continents",
                "displayName": "Continent",
                "isId": true,
                "newType": "entity",
                "actions": ["filter", "column", "group_by"],
                "actionsPopular": [],
                "icon": "mdi-earth"
            },
            "institutions.is_global_south": {
                "id": "institutions.is_global_south",
                "subjectEntity": "works",
                "displayName": "from Global South",
                "newType": "boolean",
                "actions": ["filter", "column", "group_by"],
                "category": "institution",
                "icon": "mdi-earth"
            },
            "authorships.institutions.type": {
                "id": "authorships.institutions.type",
                "isList": true,
                "subjectEntity": "works",
                "entityId": "institution-types",
                "displayName": "institution type",
                "isId": true,
                "category": "institution",
                "newType": "entity",
                "actions": ["filter", "group_by"],
                "icon": "mdi-town-hall"
            },
            "corresponding_institution_ids": {
                "id": "corresponding_institution_ids",
                "isList": true,
                "subjectEntity": "works",
                "entityId": "institutions",
                "objectEntity": "institutions",
                "displayName": "corresponding institution",
                "category": "institution",
                "newType": "entity",
                "actions": ["filter", "group_by"],
                "icon": "mdi-email-outline"
            },
            "primary_location.source.id": {
                "id": "primary_location.source.id",
                "subjectEntity": "works",
                "displayName": "source",
                "entityId": "sources",
                "objectEntity": "sources",
                "newType": "entity",
                "category": "source",
                "actions": ["filter", "group_by"],
                "icon": "mdi-book-open-outline"
            },
            "primary_location.source.issn": {
                "id": "primary_location.source.issn",
                "subjectEntity": "works",
                "entityId": "sources",
                "objectEntity": "sources",
                "displayName": "ISSN",
                "isId": true,
                "newType": "string",
                "category": "ids",
                "actions": [],
                "icon": "mdi-book-open-outline"
            },
            "primary_location.source.type": {
                "id": "primary_location.source.type",
                "subjectEntity": "works",
                "entityId": "source-types",
                "displayName": "source type",
                "isId": true,
                "newType": "entity",
                "category": "source",
                "actions": ["filter", "column", "group_by"],
                "icon": "mdi-book-open-outline"
            },
            "primary_location.source.is_in_doaj": {
                "id": "primary_location.source.is_in_doaj",
                "subjectEntity": "works",
                "displayName": "indexed by DOAJ",
                "newType": "boolean",
                "category": "source",
                "actions": ["filter", "group_by"],
                "icon": "mdi-book-open-outline"
            },
            "primary_location.source.is_oa": {
                "id": "primary_location.source.is_oa",
                "subjectEntity": "works",
                "displayName": "in OA source",
                "newType": "boolean",
                "category": "source",
                "actions": ["filter", "column", "group_by"],
                "icon": "mdi-book-open-outline"
            },
            "primary_location.source.publisher_lineage": {
                "id": "primary_location.source.publisher_lineage",
                "subjectEntity": "works",
                "entityId": "publishers",
                "objectEntity": "publishers",
                "displayName": "publisher",
                "newType": "entity",
                "category": "source",
                "actions": ["filter", "group_by"],
                "icon": "mdi-domain"
            },
            "repository": {
                "id": "repository",
                "subjectEntity": "works",
                "displayName": "repository",
                "entityId": "sources",
                "objectEntity": "sources",
                "newType": "entity",
                "category": "source",
                "actions": ["filter", "group_by"],
                "icon": "mdi-book-open-outline"
            },
            "open_access.any_repository_has_fulltext": {
                "id": "open_access.any_repository_has_fulltext",
                "subjectEntity": "works",
                "displayName": "has repository fulltext",
                "newType": "boolean",
                "category": "source",
                "actions": ["filter", "column", "group_by"],
                "icon": "mdi-tag-outline"
            },
            "type": {
                "id": "type",
                "subjectEntity": "works",
                "entityId": "types",
                "displayName": "type",
                "isExternalId": true,
                "isId": true,
                "externalIdPrefix": "work-types",
                "newType": "entity",
                "category": "other",
                "actions": ["filter", "column", "group_by"],
                "actionsPopular": ["filter", "column", "group_by"],
                "icon": "mdi-shape-outline"
            },
            "abstract_inverted_index": {
                "id": "abstract_inverted_index",
                "subjectEntity": "works",
                "displayName": "Abstract",
                "newType": "string",
                "actions": [],
                "icon": "mdi-text"
            },
            "publication_year": {
                "id": "publication_year",
                "isYear": true,
                "subjectEntity": "works",
                "displayName": "year",
                "isDate": true,
                "newType": "number",
                "sortByValue": true,
                "examples": ["1999", "1999-", "1999-2020"],
                "category": "other",
                "actions": ["filter", "sort", "column", "group_by"],
                "actionsPopular": ["filter", "sort", "column", "group_by"],
                "icon": "mdi-calendar-range"
            },
            "apc_sum": {
                "id": "apc_sum",
                "isCurrency": true,
                "subjectEntity": "works",
                "displayName": "APC sum",
                "newType": "sum",
                "category": "other",
                "actions": ["group_by"],
                "actionsPopular": ["group_by"],
                "icon": "mdi-cash"
            },
            "publication_date": {
                "id": "publication_date",
                "subjectEntity": "works",
                "displayName": "date",
                "isDate": true,
                "newType": "number",
                "actions": ["sort"],
                "sortByValue": true,
                "category": "other",
                "examples": ["1999", "1999-", "1999-2020"],
                "icon": "mdi-calendar-range"
            },
            "has_doi": {
                "id": "has_doi",
                "subjectEntity": "works",
                "displayName": "indexed by Crossref",
                "newType": "boolean",
                "category": "ids",
                "actions": ["filter", "group_by"],
                "icon": "mdi-tag-outline"
            },
            "mag_only": {
                "id": "mag_only",
                "subjectEntity": "works",
                "displayName": "indexed by MAG only",
                "newType": "boolean",
                "category": "ids",
                "actions": ["filter", "group_by"],
                "icon": "mdi-tag-outline"
            },
            "has_orcid": {
                "id": "has_orcid",
                "subjectEntity": "works",
                "displayName": "indexed by ORCID",
                "newType": "boolean",
                "actions": ["filter", "group_by"],
                "icon": "mdi-tag-outline"
            },
            "has_pmid": {
                "id": "has_pmid",
                "subjectEntity": "works",
                "displayName": "indexed by PubMed",
                "newType": "boolean",
                "category": "ids",
                "actions": ["filter", "group_by"],
                "icon": "mdi-tag-outline"
            },
            "is_retracted": {
                "id": "is_retracted",
                "subjectEntity": "works",
                "displayName": "retracted",
                "newType": "boolean",
                "category": "other",
                "actions": ["filter", "column", "group_by"],
                "icon": "mdi-close-octagon"
            },
            "language": {
                "id": "language",
                "entityId": "languages",
                "subjectEntity": "works",
                "displayName": "language",
                "isId": true,
                "newType": "entity",
                "displayNullAs": "Unknown",
                "category": "other",
                "actions": ["filter", "column", "group_by"],
                "actionsPopular": ["column", "group_by"],
                "icon": "mdi-translate"
            },
            "sustainable_development_goals.id": {
                "id": "sustainable_development_goals.id",
                "isList": true,
                "entityId": "sdgs",
                "objectEntity": "sdgs",
                "subjectEntity": "works",
                "displayName": "sdgs",
                "newType": "entity",
                "displayNullAs": "Unknown",
                "category": "other",
                "actions": ["filter", "group_by"],
                "icon": "mdi-sprout-outline"
            },
            "referenced_works": {
                "id": "referenced_works",
                "subjectEntity": "works",
                "entityId": "works",
                "isList": true,
                "isId": true,
                "objectEntity": "works",
                "displayName": "cites",
                "newType": "string",
                "category": "citation",
                "actions": [],
                "icon": "mdi-format-quote-close",
                "isDisplayedAsCount": true
            },
            "related_works": {
                "id": "related_works",
                "subjectEntity": "works",
                "entityId": "works",
                "objectEntity": "works",
                "displayName": "related to",
                "isList": true,
                "isId": true,
                "newType": "string",
                "category": "other",
                "actions": ["filter"],
                "isHidden": true,
                "icon": "mdi-book-open-outline",
                "isDisplayedAsCount": true
            }
        }
    },
    "authors": {
        "id": "authors",
        "icon": "mdi-account-outline",
        "name": "authors",
        "nameSingular": "author",
        "displayName": "authors",
        "displayNameSingular": "author",
        "descr": "Creators of scholarly works",
        "eg": "Albert Einstein",
        "placeholder": "Search scholarly authors",
        "filterName": "author",
        "filterKey": "authorships.author.id",
        "hintVerb": "at",
        "color": "green",
        "hasAutocomplete": true,
        "isNative": true,
        "hasSerp": true,
        "highlightFilters": [{
            "key": "has_orcid",
            "value": true,
            "displayName": "with ORCIDs"
        }, {"key": "last_known_institutions.is_global_south", "value": true, "displayName": "from the Global South"}],
        "idRegex": "(?i)(?:authors\\/)?(?:https:\\/\\/openalex\\.org\\/)?(a\\d+)",
        "rowsToShowOnEntityPage": ["id", "display_name", "display_name_alternatives", "last_known_institutions.id", "affiliations.institution.id", "ids.orcid"],
        "rowsToShowOnTablePage": ["display_name", "display_name_alternatives", "last_known_institutions.id", "ids.orcid"],
        "groupByDefaults": ["last_known_institutions.id", "last_known_institutions.country_code", "has_orcid"],
        "properties": {
            "id": {
                "id": "id",
                "subjectEntity": "authors",
                "entityId": "authors",
                "objectEntity": "authors",
                "displayName": "OpenAlex ID",
                "newType": "string",
                "actions": [],
                "actionsPopular": [],
                "isId": true,
                "icon": "mdi-account-outline"
            },
            "ids.orcid": {
                "id": "ids.orcid",
                "subjectEntity": "authors",
                "entityId": "authors",
                "objectEntity": "authors",
                "displayName": "ORCID",
                "isId": true,
                "newType": "string",
                "icon": "mdi-account-outline"
            },
            "default.search": {
                "id": "default.search",
                "subjectEntity": "authors",
                "entityId": "authors",
                "objectEntity": "authors",
                "displayName": "name",
                "newType": "string",
                "actions": ["filter"],
                "actionsPopular": ["filter"],
                "icon": "mdi-magnify"
            },
            "display_name": {
                "id": "display_name",
                "isColumnMandatory": true,
                "subjectEntity": "authors",
                "displayName": "name",
                "newType": "string",
                "actions": ["sort", "column"],
                "actionsPopular": ["sort", "column"],
                "category": "other",
                "icon": "mdi-account-outline"
            },
            "affiliations.institution.id": {
                "id": "affiliations.institution.id",
                "isList": true,
                "subjectEntity": "authors",
                "displayName": "Past institutions",
                "entityId": "institutions",
                "objectEntity": "institutions",
                "newType": "entity",
                "actions": ["filter", "group_by"],
                "actionsPopular": ["filter"],
                "icon": "mdi-town-hall"
            },
            "affiliations.institution.type": {
                "id": "affiliations.institution.type",
                "isList": true,
                "isId": true,
                "subjectEntity": "authors",
                "entityId": "institution-types",
                "objectEntity": "institution-types",
                "displayName": "Past institutions type",
                "newType": "entity",
                "actions": ["filter", "group_by"],
                "actionsPopular": ["filter"],
                "icon": "mdi-shape-outline"
            },
            "last_known_institutions.id": {
                "id": "last_known_institutions.id",
                "isList": true,
                "subjectEntity": "authors",
                "displayName": "institution",
                "entityId": "institutions",
                "objectEntity": "institutions",
                "newType": "entity",
                "actions": ["filter", "group_by"],
                "actionsPopular": ["filter", "group_by"],
                "icon": "mdi-town-hall"
            },
            "last_known_institutions.country_code": {
                "id": "last_known_institutions.country_code",
                "isList": true,
                "subjectEntity": "authors",
                "entityId": "countries",
                "isId": true,
                "displayName": "institution country",
                "newType": "entity",
                "isCountry": true,
                "actions": ["filter", "group_by"],
                "actionsPopular": ["filter", "group_by"],
                "icon": "mdi-earth"
            },
            "last_known_institutions.type": {
                "id": "last_known_institutions.type",
                "isList": true,
                "subjectEntity": "authors",
                "entityId": "institution-types",
                "displayName": "Institution type",
                "isId": true,
                "newType": "entity",
                "actions": ["filter", "group_by"],
                "actionsPopular": ["filter"],
                "icon": "mdi-shape-outline"
            },
            "has_orcid": {
                "id": "has_orcid",
                "subjectEntity": "authors",
                "entityId": "authors",
                "objectEntity": "authors",
                "displayName": "Has an ORCID",
                "newType": "boolean",
                "actions": ["filter", "group_by"],
                "actionsPopular": ["filter", "group_by"],
                "icon": "mdi-tag-outline"
            },
            "display_name_alternatives": {
                "id": "display_name_alternatives",
                "isList": true,
                "subjectEntity": "authors",
                "entityId": "authors",
                "objectEntity": "authors",
                "displayName": "alternate names",
                "newType": "string",
                "actions": [],
                "actionsPopular": [],
                "icon": "mdi-town-hall"
            }
        }
    },
    "sources": {
        "id": "sources",
        "icon": "mdi-book-open-outline",
        "name": "sources",
        "nameSingular": "source",
        "displayName": "sources",
        "displayNameSingular": "source",
        "descr": "Journals, conferences, and repositories",
        "eg": "The New England Journal of Medicine",
        "placeholder": "Search academic journals & repositories",
        "filterName": "primary_location.source",
        "filterKey": "primary_location.source.id",
        "hintVerb": "published by",
        "color": "orange",
        "hasAutocomplete": true,
        "isNative": true,
        "hasSerp": true,
        "highlightFilters": [{"key": "is_oa", "value": true, "displayName": "that are Open Access"}],
        "idRegex": "(?i)(?:sources\\/)?(?:https:\\/\\/openalex\\.org\\/)?(s\\d+)",
        "rowsToShowOnEntityPage": ["id", "display_name", "ids.issn", "type", "publisher", "alternate_titles", "is_oa", "is_in_doaj", "apc_usd"],
        "rowsToShowOnTablePage": ["display_name", "ids.issn", "type", "publisher", "is_oa", "is_in_doaj"],
        "groupByDefaults": ["type", "is_oa", "is_in_doaj"],
        "properties": {
            "id": {
                "id": "id",
                "subjectEntity": "sources",
                "entityId": "sources",
                "objectEntity": "sources",
                "displayName": "OpenAlex ID",
                "isId": true,
                "newType": "string",
                "icon": "mdi-book-open-outline"
            },
            "default.search": {
                "id": "default.search",
                "subjectEntity": "sources",
                "entityId": "sources",
                "objectEntity": "sources",
                "displayName": "name",
                "newType": "string",
                "actions": ["filter"],
                "actionsPopular": ["filter"],
                "icon": "mdi-magnify"
            },
            "ids.issn": {
                "id": "ids.issn",
                "subjectEntity": "sources",
                "entityId": "sources",
                "displayName": "ISSNs",
                "isId": true,
                "newType": "string",
                "icon": "mdi-book-open-outline"
            },
            "display_name.search": {
                "id": "display_name.search",
                "subjectEntity": "sources",
                "displayName": "Title search",
                "newType": "string",
                "icon": "mdi-magnify"
            },
            "display_name": {
                "id": "display_name",
                "isColumnMandatory": true,
                "subjectEntity": "sources",
                "displayName": "name",
                "newType": "string",
                "actions": ["sort", "column"],
                "actionsPopular": ["sort", "column"],
                "category": "other",
                "icon": "mdi-account-outline"
            },
            "publisher": {
                "id": "publisher",
                "subjectEntity": "sources",
                "entityId": "publishers",
                "objectEntity": "publishers",
                "displayName": "Publisher",
                "newType": "entity",
                "actions": [],
                "actionsPopular": [],
                "icon": "mdi-domain"
            },
            "type": {
                "id": "type",
                "subjectEntity": "sources",
                "entityId": "source-types",
                "displayName": "Source type",
                "isId": true,
                "newType": "entity",
                "actions": ["filter"],
                "actionsPopular": ["filter"],
                "icon": "mdi-shape-outline"
            },
            "apc_usd": {
                "id": "apc_usd",
                "isCurrency": true,
                "subjectEntity": "sources",
                "displayName": "Article Processing Charge",
                "newType": "number",
                "actions": ["filter"],
                "actionsPopular": ["filter"],
                "icon": "mdi-cash"
            },
            "is_oa": {
                "id": "is_oa",
                "subjectEntity": "sources",
                "displayName": "Fully open access",
                "newType": "boolean",
                "actions": ["filter"],
                "actionsPopular": ["filter"],
                "icon": "mdi-lock-open-outline"
            },
            "is_in_doaj": {
                "id": "is_in_doaj",
                "subjectEntity": "sources",
                "displayName": "In DOAJ",
                "newType": "boolean",
                "actions": ["filter"],
                "actionsPopular": ["filter"],
                "icon": "mdi-lock-open-outline"
            },
            "alternate_titles": {
                "id": "alternate_titles",
                "isList": true,
                "subjectEntity": "sources",
                "displayName": "alternate names",
                "newType": "string",
                "actions": [],
                "actionsPopular": [],
                "icon": "mdi-book-open-outline"
            }
        }
    },
    "publishers": {
        "id": "publishers",
        "icon": "mdi-domain",
        "name": "publishers",
        "nameSingular": "publisher",
        "displayName": "publishers",
        "displayNameSingular": "publisher",
        "descr": "Company hosting journals",
        "eg": "Elsevier",
        "placeholder": "Search academic publishers",
        "filterName": "primary_location.source.publisher_lineage",
        "filterKey": "primary_location.source.publisher_lineage",
        "color": "pink",
        "hasAutocomplete": true,
        "isNative": true,
        "idRegex": "(?i)(?:publishers\\/)?(?:https:\\/\\/openalex\\.org\\/)?(p\\d+)",
        "rowsToShowOnEntityPage": ["id", "display_name"],
        "rowsToShowOnTablePage": ["display_name"],
        "properties": {
            "id": {
                "id": "id",
                "subjectEntity": "publishers",
                "entityId": "publishers",
                "objectEntity": "publishers",
                "displayName": "OpenAlex ID",
                "isId": true,
                "newType": "string",
                "icon": "mdi-domain"
            },
            "display_name": {
                "id": "display_name",
                "isColumnMandatory": true,
                "subjectEntity": "publishers",
                "displayName": "name",
                "newType": "string",
                "actions": ["sort", "column"],
                "actionsPopular": ["sort", "column"],
                "category": "other",
                "icon": "mdi-account-outline"
            },
            "display_name.search": {
                "id": "display_name.search",
                "subjectEntity": "publishers",
                "displayName": "Name search",
                "newType": "string",
                "icon": "mdi-magnify"
            }
        }
    },
    "funders": {
        "id": "funders",
        "icon": "mdi-cash-multiple",
        "name": "funders",
        "nameSingular": "funder",
        "displayName": "funders",
        "displayNameSingular": "funder",
        "descr": "Organization funding works via grants",
        "eg": "US National Science Foundation",
        "placeholder": "Search research funders",
        "filterName": "grants.funder",
        "filterKey": "grants.funder",
        "color": "brown",
        "hasAutocomplete": true,
        "isNative": true,
        "idRegex": "(?i)(?:funders\\/)?(?:https:\\/\\/openalex\\.org\\/)?(f\\d+)",
        "rowsToShowOnEntityPage": ["id", "display_name"],
        "rowsToShowOnTablePage": ["display_name"],
        "properties": {
            "id": {
                "id": "id",
                "subjectEntity": "funders",
                "entityId": "funders",
                "objectEntity": "funders",
                "displayName": "OpenAlex ID",
                "isId": true,
                "newType": "string",
                "icon": "mdi-cash-multiple"
            },
            "display_name": {
                "id": "display_name",
                "isColumnMandatory": true,
                "subjectEntity": "funders",
                "displayName": "name",
                "newType": "string",
                "actions": ["sort", "column"],
                "actionsPopular": ["sort", "column"],
                "category": "other",
                "icon": "mdi-account-outline"
            },
            "display_name.search": {
                "id": "display_name.search",
                "subjectEntity": "funders",
                "displayName": "Name search",
                "newType": "string",
                "icon": "mdi-magnify"
            }
        }
    },
    "institutions": {
        "id": "institutions",
        "icon": "mdi-town-hall",
        "name": "institutions",
        "nameSingular": "institution",
        "displayName": "institutions",
        "displayNameSingular": "institution",
        "descr": "Universities and research centers",
        "eg": "Harvard University",
        "placeholder": "Search academic institutions",
        "filterName": "institutions",
        "filterKey": "authorships.institutions.lineage",
        "hintVerb": "in",
        "color": "purple",
        "hasAutocomplete": true,
        "isNative": true,
        "hasSerp": true,
        "rowsToShowOnEntityPage": ["id", "display_name", "display_name_alternatives", "parent_institutions", "child_institutions", "related_institutions", "ids.ror"],
        "rowsToShowOnTablePage": ["display_name", "type", "country_code", "parent_institutions", "child_institutions", "ids.ror"],
        "idRegex": "(?i)(?:institutions\\/)?(?:https:\\/\\/openalex\\.org\\/)?(i\\d+)",
        "groupByDefaults": ["country_code", "type"],
        "properties": {
            "id": {
                "id": "id",
                "subjectEntity": "institutions",
                "entityId": "institutions",
                "objectEntity": "institutions",
                "displayName": "OpenAlex ID",
                "isId": true,
                "newType": "string",
                "icon": "mdi-town-hall"
            },
            "default.search": {
                "id": "default.search",
                "subjectEntity": "institutions",
                "entityId": "institutions",
                "objectEntity": "institutions",
                "displayName": "name",
                "newType": "string",
                "actions": ["filter"],
                "actionsPopular": ["filter"],
                "icon": "mdi-magnify"
            },
            "display_name": {
                "id": "display_name",
                "isColumnMandatory": true,
                "subjectEntity": "institutions",
                "displayName": "name",
                "newType": "string",
                "actions": ["sort", "column"],
                "actionsPopular": ["sort", "column"],
                "category": "other",
                "icon": "mdi-account-outline"
            },
            "ids.ror": {
                "id": "ids.ror",
                "subjectEntity": "institutions",
                "entityId": "institutions",
                "objectEntity": "institutions",
                "displayName": "ROR",
                "isId": true,
                "newType": "string",
                "icon": "mdi-town-hall"
            },
            "display_name.search": {
                "id": "display_name.search",
                "subjectEntity": "institutions",
                "displayName": "Name search",
                "newType": "string",
                "icon": "mdi-magnify"
            },
            "country_code": {
                "id": "country_code",
                "subjectEntity": "institutions",
                "entityId": "countries",
                "displayName": "Country",
                "isId": true,
                "newType": "entity",
                "isExternalId": true,
                "externalIdPrefix": "countries",
                "isCountry": true,
                "actions": ["filter"],
                "actionsPopular": ["filter"],
                "icon": "mdi-earth"
            },
            "type": {
                "id": "type",
                "subjectEntity": "institutions",
                "entityId": "institution-types",
                "displayName": "Institution type",
                "isExternalId": true,
                "externalIdPrefix": "institution-types",
                "isId": true,
                "newType": "entity",
                "actions": ["filter"],
                "actionsPopular": ["filter"],
                "icon": "mdi-shape-outline"
            },
            "x_concepts.id": {
                "id": "x_concepts.id",
                "isList": true,
                "subjectEntity": "institutions",
                "displayName": "Concepts",
                "entityId": "concepts",
                "objectEntity": "concepts",
                "newType": "entity",
                "icon": "mdi-tag-outline"
            },
            "display_name_alternatives": {
                "id": "display_name_alternatives",
                "isList": true,
                "subjectEntity": "institutions",
                "displayName": "alternate names",
                "newType": "string",
                "actions": [],
                "actionsPopular": [],
                "icon": "mdi-town-hall"
            },
            "parent_institutions": {
                "id": "parent_institutions",
                "isList": true,
                "subjectEntity": "institutions",
                "objectEntity": "institutions",
                "displayName": "parent institutions",
                "newType": "entity",
                "actions": [],
                "actionsPopular": [],
                "icon": "mdi-town-hall"
            },
            "child_institutions": {
                "id": "child_institutions",
                "isList": true,
                "subjectEntity": "institutions",
                "objectEntity": "institutions",
                "displayName": "child institutions",
                "newType": "entity",
                "actions": [],
                "actionsPopular": [],
                "icon": "mdi-town-hall"
            },
            "related_institutions": {
                "id": "related_institutions",
                "isList": true,
                "subjectEntity": "institutions",
                "objectEntity": "institutions",
                "displayName": "related institutions",
                "newType": "entity",
                "actions": [],
                "actionsPopular": [],
                "icon": "mdi-town-hall"
            }
        }
    },
    "concepts": {
        "id": "concepts",
        "icon": "mdi-tag-outline",
        "name": "concepts",
        "nameSingular": "concept",
        "displayName": "concepts",
        "displayNameSingular": "concept",
        "descr": "Topics and fields of study",
        "eg": "History",
        "placeholder": "Search topics",
        "filterName": "concepts",
        "filterKey": "concepts.id",
        "hasAutocomplete": true,
        "isNative": true,
        "idRegex": "(?i)(?:concepts\\/)?(?:https:\\/\\/openalex\\.org\\/)?(c\\d+)",
        "rowsToShowOnEntityPage": ["id", "display_name", "description"],
        "rowsToShowOnTablePage": ["display_name", "description"],
        "properties": {
            "id": {
                "id": "id",
                "subjectEntity": "concepts",
                "entityId": "concepts",
                "objectEntity": "concepts",
                "displayName": "OpenAlex ID",
                "isId": true,
                "newType": "string",
                "icon": "mdi-tag-outline"
            },
            "display_name": {
                "id": "display_name",
                "isColumnMandatory": true,
                "subjectEntity": "concepts",
                "displayName": "name",
                "newType": "string",
                "actions": ["sort", "column"],
                "actionsPopular": ["sort", "column"],
                "category": "other",
                "icon": "mdi-account-outline"
            },
            "description": {
                "id": "description",
                "subjectEntity": "concepts",
                "entityId": "concepts",
                "objectEntity": "concepts",
                "displayName": "description",
                "newType": "string",
                "icon": "mdi-tag-outline"
            },
            "display_name.search": {
                "id": "display_name.search",
                "subjectEntity": "concepts",
                "displayName": "Name search",
                "newType": "string",
                "icon": "mdi-magnify"
            },
            "level": {
                "id": "level",
                "subjectEntity": "concepts",
                "displayName": "Level",
                "maxPotentialFiltersToShow": 10,
                "newType": "number",
                "icon": "mdi-tag-outline"
            }
        }
    },
    "keywords": {
        "id": "keywords",
        "icon": "mdi-tag-outline",
        "name": "keywords",
        "nameSingular": "keyword",
        "displayName": "keywords",
        "displayNameSingular": "keyword",
        "descr": "what works are about",
        "eg": "Cardiac imaging",
        "placeholder": "Search keywords",
        "filterName": "keywords",
        "filterKey": "keywords.id",
        "hintVerb": ":",
        "hasAutocomplete": true,
        "isNative": false,
        "idRegex": "(?:https:\\/\\/openalex\\.org\\/keywords\\/|keywords\\/)([a-zA-Z0-9\\-]+)",
        "rowsToShowOnEntityPage": ["id", "display_name"],
        "rowsToShowOnTablePage": ["display_name"],
        "properties": {
            "id": {
                "id": "id",
                "subjectEntity": "keywords",
                "entityId": "keywords",
                "objectEntity": "keywords",
                "displayName": "Keyword ID",
                "isId": true,
                "newType": "string",
                "icon": "mdi-tag-outline"
            },
            "display_name": {
                "id": "display_name",
                "isColumnMandatory": true,
                "subjectEntity": "keywords",
                "displayName": "name",
                "newType": "string",
                "actions": ["sort", "column"],
                "actionsPopular": ["sort", "column"],
                "category": "other",
                "icon": "mdi-account-outline"
            }
        }
    },
    "topics": {
        "id": "topics",
        "icon": "mdi-tag-outline",
        "name": "topics",
        "nameSingular": "topic",
        "displayName": "topics",
        "displayNameSingular": "topics",
        "descr": "what works are about",
        "eg": "RNA sequencing",
        "placeholder": "Search topics",
        "filterName": "topics",
        "filterKey": "primary_topic.id",
        "hintVerb": ":",
        "hasAutocomplete": true,
        "isNative": true,
        "idRegex": "(?i)(?:topics\\/)?(?:https:\\/\\/openalex\\.org\\/)?(t\\d+)",
        "rowsToShowOnEntityPage": ["id", "display_name", "description", "siblings", "subfield", "field", "domain"],
        "rowsToShowOnTablePage": ["display_name", "description", "siblings", "subfield", "field", "domain"],
        "properties": {
            "id": {
                "id": "id",
                "subjectEntity": "topics",
                "entityId": "topics",
                "objectEntity": "topics",
                "displayName": "OpenAlex ID",
                "isId": true,
                "newType": "string",
                "icon": "mdi-tag-outline"
            },
            "display_name": {
                "id": "display_name",
                "isColumnMandatory": true,
                "subjectEntity": "topics",
                "displayName": "name",
                "newType": "string",
                "actions": ["sort", "column"],
                "actionsPopular": ["sort", "column"],
                "category": "other",
                "icon": "mdi-account-outline"
            },
            "description": {
                "id": "description",
                "subjectEntity": "topics",
                "entityId": "topics",
                "objectEntity": "topics",
                "displayName": "description",
                "newType": "string",
                "icon": "mdi-tag-outline"
            },
            "siblings": {
                "id": "siblings",
                "isList": true,
                "subjectEntity": "topics",
                "entityId": "topics",
                "objectEntity": "topics",
                "displayName": "related topics (siblings)",
                "newType": "entity",
                "icon": "mdi-tag-outline"
            },
            "subfield": {
                "id": "subfield",
                "subjectEntity": "topics",
                "entityId": "subfields",
                "objectEntity": "subfields",
                "displayName": "subfield (parent)",
                "newType": "entity",
                "icon": "mdi-tag-outline"
            },
            "field": {
                "id": "field",
                "subjectEntity": "topics",
                "entityId": "fields",
                "objectEntity": "fields",
                "displayName": "field",
                "newType": "entity",
                "icon": "mdi-tag-outline"
            },
            "domain": {
                "id": "domain",
                "subjectEntity": "topics",
                "entityId": "domains",
                "objectEntity": "domains",
                "displayName": "domain",
                "newType": "entity",
                "icon": "mdi-tag-outline"
            }
        }
    },
    "subfields": {
        "id": "subfields",
        "icon": "mdi-tag-outline",
        "name": "subfields",
        "nameSingular": "subfield",
        "displayName": "subfields",
        "displayNameSingular": "subfield",
        "descr": "what works are about",
        "eg": "Molecular biology",
        "placeholder": "Search subfields",
        "filterName": "subfields",
        "filterKey": "primary_topic.subfield.id",
        "hasAutocomplete": false,
        "isNative": false,
        "idRegex": "(?:https:\\/\\/openalex\\.org\\/subfields\\/|subfields\\/)(\\d+)",
        "rowsToShowOnEntityPage": ["id", "display_name", "description", "topics", "siblings", "field", "domain"],
        "rowsToShowOnTablePage": ["display_name", "description", "topics", "siblings", "field", "domain"],
        "properties": {
            "id": {
                "id": "id",
                "subjectEntity": "subfields",
                "entityId": "subfields",
                "objectEntity": "subfields",
                "displayName": "OpenAlex ID",
                "isId": true,
                "newType": "string",
                "icon": "mdi-tag-outline"
            },
            "display_name": {
                "id": "display_name",
                "isColumnMandatory": true,
                "subjectEntity": "subfields",
                "displayName": "name",
                "newType": "string",
                "actions": ["sort", "column"],
                "actionsPopular": ["sort", "column"],
                "category": "other",
                "icon": "mdi-account-outline"
            },
            "description": {
                "id": "description",
                "subjectEntity": "subfields",
                "entityId": "subfields",
                "objectEntity": "subfields",
                "displayName": "description",
                "newType": "string",
                "icon": "mdi-tag-outline"
            },
            "display_name_alternatives": {
                "id": "display_name_alternatives",
                "isList": true,
                "subjectEntity": "subfields",
                "entityId": "subfields",
                "objectEntity": "subfields",
                "displayName": "alternate names",
                "newType": "string",
                "icon": "mdi-tag-outline"
            },
            "topics": {
                "id": "topics",
                "isList": true,
                "subjectEntity": "subfields",
                "entityId": "topics",
                "objectEntity": "topics",
                "displayName": "topics (children)",
                "newType": "entity",
                "icon": "mdi-tag-outline"
            },
            "siblings": {
                "id": "siblings",
                "isList": true,
                "subjectEntity": "subfields",
                "entityId": "subfields",
                "objectEntity": "subfields",
                "displayName": "related subfields (siblings)",
                "newType": "entity",
                "icon": "mdi-tag-outline"
            },
            "field": {
                "id": "field",
                "subjectEntity": "subfields",
                "entityId": "fields",
                "objectEntity": "fields",
                "displayName": "field (parent)",
                "newType": "entity",
                "icon": "mdi-tag-outline"
            },
            "domain": {
                "id": "domain",
                "subjectEntity": "subfields",
                "entityId": "domains",
                "objectEntity": "domains",
                "displayName": "domain",
                "newType": "entity",
                "icon": "mdi-tag-outline"
            }
        }
    },
    "fields": {
        "id": "fields",
        "icon": "mdi-tag-outline",
        "name": "fields",
        "nameSingular": "field",
        "displayName": "fields",
        "displayNameSingular": "field",
        "descr": "what works are about",
        "eg": "Computer science",
        "placeholder": "Search fields",
        "filterName": "fields",
        "filterKey": "primary_topic.field.id",
        "hasAutocomplete": false,
        "isNative": false,
        "idRegex": "(?:https:\\/\\/openalex\\.org\\/fields\\/|fields\\/)(\\d+)",
        "rowsToShowOnEntityPage": ["id", "display_name", "description", "display_name_alternatives", "subfields", "siblings", "domain"],
        "rowsToShowOnTablePage": ["display_name", "description", "subfields", "siblings", "domain"],
        "properties": {
            "id": {
                "id": "id",
                "subjectEntity": "fields",
                "entityId": "fields",
                "objectEntity": "fields",
                "displayName": "OpenAlex ID",
                "isId": true,
                "newType": "string",
                "icon": "mdi-tag-outline"
            },
            "display_name": {
                "id": "display_name",
                "isColumnMandatory": true,
                "subjectEntity": "fields",
                "displayName": "name",
                "newType": "string",
                "actions": ["sort", "column"],
                "actionsPopular": ["sort", "column"],
                "category": "other",
                "icon": "mdi-account-outline"
            },
            "description": {
                "id": "description",
                "subjectEntity": "fields",
                "entityId": "fields",
                "objectEntity": "fields",
                "displayName": "description",
                "newType": "string",
                "icon": "mdi-tag-outline"
            },
            "display_name_alternatives": {
                "id": "display_name_alternatives",
                "isList": true,
                "subjectEntity": "fields",
                "entityId": "fields",
                "objectEntity": "fields",
                "displayName": "alternate names",
                "newType": "string",
                "icon": "mdi-tag-outline"
            },
            "siblings": {
                "id": "siblings",
                "isList": true,
                "subjectEntity": "fields",
                "entityId": "fields",
                "objectEntity": "fields",
                "displayName": "related fields (siblings)",
                "newType": "entity",
                "icon": "mdi-tag-outline"
            },
            "subfields": {
                "id": "subfields",
                "isList": true,
                "subjectEntity": "fields",
                "entityId": "subfields",
                "objectEntity": "subfields",
                "displayName": "subfields (children)",
                "newType": "entity",
                "icon": "mdi-tag-outline"
            },
            "domain": {
                "id": "domain",
                "subjectEntity": "fields",
                "entityId": "domains",
                "objectEntity": "domains",
                "displayName": "domain (parent)",
                "newType": "entity",
                "icon": "mdi-tag-outline"
            }
        }
    },
    "domains": {
        "id": "domains",
        "icon": "mdi-tag-outline",
        "name": "domains",
        "nameSingular": "domain",
        "displayName": "domains",
        "displayNameSingular": "domain",
        "descr": "what works are about",
        "eg": "Life sciences",
        "placeholder": "Search domains",
        "filterName": "domains",
        "filterKey": "primary_topic.domain.id",
        "hasAutocomplete": false,
        "isNative": false,
        "idRegex": "(?:https:\\/\\/openalex\\.org\\/domains\\/|domains\\/)(\\d+)",
        "rowsToShowOnEntityPage": ["id", "display_name", "description", "display_name_alternatives", "fields", "siblings"],
        "rowsToShowOnTablePage": ["display_name", "description", "fields", "siblings"],
        "properties": {
            "id": {
                "id": "id",
                "subjectEntity": "domains",
                "entityId": "domains",
                "objectEntity": "domains",
                "displayName": "OpenAlex ID",
                "isId": true,
                "newType": "string",
                "icon": "mdi-tag-outline"
            },
            "display_name": {
                "id": "display_name",
                "isColumnMandatory": true,
                "subjectEntity": "domains",
                "displayName": "name",
                "newType": "string",
                "actions": ["sort", "column"],
                "actionsPopular": ["sort", "column"],
                "category": "other",
                "icon": "mdi-account-outline"
            },
            "description": {
                "id": "description",
                "subjectEntity": "domains",
                "entityId": "domains",
                "objectEntity": "domains",
                "displayName": "description",
                "newType": "string",
                "icon": "mdi-tag-outline"
            },
            "display_name_alternatives": {
                "id": "display_name_alternatives",
                "isList": true,
                "subjectEntity": "domains",
                "entityId": "domains",
                "objectEntity": "domains",
                "displayName": "alternate names",
                "newType": "string",
                "icon": "mdi-tag-outline"
            },
            "fields": {
                "id": "fields",
                "isList": true,
                "subjectEntity": "domains",
                "entityId": "fields",
                "objectEntity": "fields",
                "displayName": "fields (children)",
                "newType": "entity",
                "icon": "mdi-tag-outline"
            },
            "siblings": {
                "id": "siblings",
                "isList": true,
                "subjectEntity": "domains",
                "entityId": "domains",
                "objectEntity": "domains",
                "displayName": "other domains (siblings)",
                "newType": "entity",
                "icon": "mdi-tag-outline"
            }
        }
    },
    "sdgs": {
        "id": "sdgs",
        "icon": "mdi-sprout-outline",
        "name": "sdgs",
        "nameSingular": "sdg",
        "displayName": "Sustainable Development Goals",
        "displayNameSingular": "Sustainable Development Goal",
        "descr": "Relevant UN SDGs",
        "eg": "Clean water and sanitation",
        "placeholder": "Search SDGs",
        "filterName": "Sustainable Development Goals",
        "filterKey": "sustainable_development_goals.id",
        "hasAutocomplete": false,
        "isNative": false,
        "idRegex": "(?:https:\\/\\/openalex\\.org\\/sdgs\\/|sdgs\\/)(\\d+)",
        "rowsToShowOnEntityPage": ["id", "display_name"],
        "rowsToShowOnTablePage": ["display_name"],
        "properties": {
            "id": {
                "id": "id",
                "subjectEntity": "sdgs",
                "entityId": "sdgs",
                "objectEntity": "sdgs",
                "displayName": "SDG ID",
                "isId": true,
                "actions": ["sort"],
                "newType": "string",
                "icon": "mdi-tag-outline"
            },
            "display_name": {
                "id": "display_name",
                "isColumnMandatory": true,
                "subjectEntity": "sdgs",
                "displayName": "name",
                "newType": "string",
                "actions": ["sort", "column"],
                "actionsPopular": ["sort", "column"],
                "category": "other",
                "icon": "mdi-account-outline"
            }
        }
    },
    "countries": {
        "id": "countries",
        "icon": "mdi-earth",
        "name": "countries",
        "nameSingular": "country",
        "displayName": "countries",
        "displayNameSingular": "country",
        "descr": "Countries",
        "eg": "Nigeria",
        "placeholder": "Search countries",
        "filterName": "countries",
        "filterKey": "authorships.countries",
        "hasAutocomplete": false,
        "isNative": false,
        "idRegex": "(?:https:\\/\\/openalex\\.org\\/countries\\/|countries\\/)([a-zA-Z]{2})",
        "rowsToShowOnEntityPage": ["id", "display_name"],
        "rowsToShowOnTablePage": ["display_name"],
        "properties": {
            "id": {
                "id": "id",
                "subjectEntity": "countries",
                "entityId": "countries",
                "objectEntity": "countries",
                "displayName": "Country ID",
                "isId": true,
                "newType": "string",
                "icon": "mdi-tag-outline"
            },
            "display_name": {
                "id": "display_name",
                "isColumnMandatory": true,
                "subjectEntity": "countries",
                "displayName": "name",
                "newType": "string",
                "actions": ["sort", "column"],
                "actionsPopular": ["sort", "column"],
                "category": "other",
                "icon": "mdi-account-outline"
            }
        }
    },
    "continents": {
        "id": "continents",
        "icon": "mdi-earth",
        "name": "continents",
        "nameSingular": "continent",
        "displayName": "continents",
        "displayNameSingular": "continent",
        "descr": "Continents",
        "eg": "Africa",
        "placeholder": "Search continents",
        "filterName": "continent",
        "filterKey": "authorships.institutions.continent",
        "hasAutocomplete": false,
        "isNative": false,
        "idRegex": "(?i)(?:https:\\/\\/openalex\\.org\\/continents\\/|continents\\/)(q\\d+)",
        "rowsToShowOnEntityPage": ["id", "display_name", "countries"],
        "rowsToShowOnTablePage": ["display_name", "countries"],
        "properties": {
            "id": {
                "id": "id",
                "subjectEntity": "continents",
                "entityId": "continents",
                "isId": true,
                "objectEntity": "continents",
                "displayName": "Continent ID",
                "newType": "string",
                "actions": ["filter"],
                "actionsPopular": ["filter"],
                "icon": "mdi-shape-outline"
            },
            "display_name": {
                "id": "display_name",
                "subjectEntity": "continents",
                "entityId": "continents",
                "objectEntity": "continents",
                "displayName": "Continent name",
                "newType": "entity",
                "actions": ["filter"],
                "actionsPopular": ["filter"],
                "icon": "mdi-shape-outline"
            },
            "countries": {
                "id": "countries",
                "isList": true,
                "subjectEntity": "continents",
                "entityId": "continents",
                "objectEntity": "continents",
                "displayName": "countries",
                "newType": "entity",
                "icon": "mdi-earth"
            }
        }
    },
    "languages": {
        "id": "languages",
        "icon": "mdi-translate",
        "name": "languages",
        "nameSingular": "language",
        "displayName": "languages",
        "displayNameSingular": "language",
        "descr": "Languages",
        "eg": "Swahili",
        "placeholder": "Search languages",
        "filterName": "languages",
        "filterKey": "language",
        "hasAutocomplete": false,
        "isNative": false,
        "idRegex": "(?:https:\\/\\/openalex\\.org\\/languages\\/|languages\\/)([a-zA-Z]{2})",
        "rowsToShowOnEntityPage": ["id", "display_name"],
        "rowsToShowOnTablePage": ["display_name"],
        "properties": {
            "id": {
                "id": "id",
                "subjectEntity": "languages",
                "entityId": "languages",
                "objectEntity": "languages",
                "displayName": "Language ID",
                "isId": true,
                "newType": "string",
                "icon": "mdi-tag-outline"
            },
            "display_name": {
                "id": "display_name",
                "isColumnMandatory": true,
                "subjectEntity": "languages",
                "displayName": "name",
                "newType": "string",
                "actions": ["sort", "column"],
                "actionsPopular": ["sort", "column"],
                "category": "other",
                "icon": "mdi-account-outline"
            }
        }
    },
    "types": {
        "id": "types",
        "icon": "mdi-shape-outline",
        "name": "types",
        "nameSingular": "type",
        "displayName": "types",
        "displayNameSingular": "type",
        "descr": "Work type",
        "eg": "article",
        "placeholder": "Search work types",
        "filterName": "type",
        "filterKey": "type",
        "hasAutocomplete": false,
        "isNative": false,
        "idRegex": "(?:https:\\/\\/openalex\\.org\\/types\\/|types\\/)([a-zA-Z\\-]+)",
        "rowsToShowOnEntityPage": ["id", "display_name", "description", "crossref_types"],
        "rowsToShowOnTablePage": ["display_name", "description"],
        "properties": {
            "id": {
                "id": "id",
                "subjectEntity": "types",
                "entityId": "types",
                "objectEntity": "types",
                "displayName": "Type ID",
                "isId": true,
                "newType": "string",
                "icon": "mdi-tag-outline"
            },
            "display_name": {
                "id": "display_name",
                "isColumnMandatory": true,
                "subjectEntity": "types",
                "displayName": "name",
                "newType": "string",
                "actions": ["sort", "column"],
                "actionsPopular": ["sort", "column"],
                "category": "other",
                "icon": "mdi-account-outline"
            },
            "description": {
                "id": "description",
                "subjectEntity": "types",
                "entityId": "types",
                "objectEntity": "types",
                "displayName": "description",
                "newType": "string",
                "icon": "mdi-shape-outline"
            },
            "crossref_types": {
                "id": "crossref_types",
                "isList": true,
                "subjectEntity": "types",
                "entityId": "types",
                "displayName": "alternate names (Crossref)",
                "newType": "string",
                "icon": "mdi-shape-outline"
            }
        }
    },
    "source-types": {
        "id": "source-types",
        "icon": "mdi-shape-outline",
        "name": "source-types",
        "nameSingular": "source type",
        "displayName": "source types",
        "displayNameSingular": "source type",
        "descr": "Source type",
        "eg": "journal",
        "placeholder": "Search source types",
        "filterName": "source type",
        "filterKey": "primary_location.source.type",
        "hasAutocomplete": false,
        "isNative": false,
        "idRegex": "(?:https:\\/\\/openalex\\.org\\/source-types\\/|source-types\\/)([a-zA-Z\\-]+)",
        "rowsToShowOnEntityPage": ["id", "display_name", "description"],
        "rowsToShowOnTablePage": ["display_name", "description"],
        "properties": {
            "id": {
                "id": "id",
                "subjectEntity": "source-types",
                "entityId": "source-types",
                "objectEntity": "source-types",
                "displayName": "Source Type ID",
                "isId": true,
                "newType": "string",
                "actions": ["filter"],
                "actionsPopular": ["filter"],
                "icon": "mdi-shape-outline"
            },
            "display_name": {
                "id": "display_name",
                "subjectEntity": "source-types",
                "entityId": "source-types",
                "objectEntity": "source-types",
                "displayName": "Source type name",
                "newType": "entity",
                "actions": ["filter"],
                "actionsPopular": ["filter"],
                "icon": "mdi-shape-outline"
            },
            "description": {
                "id": "description",
                "subjectEntity": "source-types",
                "entityId": "source-types",
                "objectEntity": "source-types",
                "displayName": "Source type description",
                "newType": "entity",
                "actions": ["filter"],
                "actionsPopular": ["filter"],
                "icon": "mdi-shape-outline"
            }
        }
    },
    "institution-types": {
        "id": "institution-types",
        "icon": "mdi-shape-outline",
        "name": "institution-types",
        "nameSingular": "institution type",
        "displayName": "institution types",
        "displayNameSingular": "institution type",
        "descr": "institution type",
        "eg": "company",
        "placeholder": "Search institution types",
        "filterName": "institution type",
        "filterKey": "authorships.institutions.type",
        "hasAutocomplete": false,
        "isNative": false,
        "idRegex": "(?:https:\\/\\/openalex\\.org\\/institution-types\\/|institution-types\\/)([a-zA-Z\\-]+)",
        "rowsToShowOnEntityPage": ["id", "display_name"],
        "rowsToShowOnTablePage": ["display_name"],
        "properties": {
            "id": {
                "id": "id",
                "subjectEntity": "institution-types",
                "entityId": "institution-types",
                "objectEntity": "institution-types",
                "displayName": "Institution ID",
                "isId": true,
                "newType": "string",
                "icon": "mdi-tag-outline"
            },
            "display_name": {
                "id": "display_name",
                "isColumnMandatory": true,
                "subjectEntity": "institution-types",
                "displayName": "name",
                "newType": "string",
                "actions": ["sort", "column"],
                "actionsPopular": ["sort", "column"],
                "category": "other",
                "icon": "mdi-account-outline"
            }
        }
    },
    "licenses": {
        "id": "licenses",
        "icon": "mdi-lock-open-outline",
        "name": "licenses",
        "nameSingular": "license",
        "displayName": "licenses",
        "displayNameSingular": "license",
        "descr": "license of best open copy",
        "eg": "CC-BY",
        "placeholder": "Search licenses",
        "filterName": "institution type",
        "filterKey": "best_oa_location.license",
        "hasAutocomplete": false,
        "isNative": false,
        "idRegex": "(?:https:\\/\\/openalex\\.org\\/licenses\\/|licenses\\/)([a-zA-Z0-9\\-]+)",
        "rowsToShowOnEntityPage": ["id", "display_name"],
        "rowsToShowOnTablePage": ["display_name"],
        "properties": {
            "id": {
                "id": "id",
                "subjectEntity": "licenses",
                "entityId": "licenses",
                "objectEntity": "licenses",
                "displayName": "License ID",
                "isId": true,
                "newType": "string",
                "icon": "mdi-tag-outline"
            },
            "display_name": {
                "id": "display_name",
                "isColumnMandatory": true,
                "subjectEntity": "licenses",
                "displayName": "name",
                "newType": "string",
                "actions": ["sort", "column"],
                "actionsPopular": ["sort", "column"],
                "category": "other",
                "icon": "mdi-account-outline"
            }
        }
    }
}