// AUTO-GENERATED by scripts/gen_oql_corpus.py -- do not edit by hand.
// Source of truth: openalex-elastic-api/docs/oql/corpus.yaml (oxjob #330).
// The OQL v2 normative corpus, one entry per worked example. Each `ok`
// row carries its canonical `oqo` (parsed where the corpus omits it) so
// the OQL playground can compute a uniform complexity metric. See #345.
// corpus version: 2; rows: 78.

export const oqlCorpus = [
  {
    "id": "ENT1",
    "category": "entity references",
    "source": "spec spine",
    "status": "ok",
    "oql": "works where institution is I136199984 [Harvard]",
    "note": "ID authoritative; [Harvard] is an ignored annotation, regenerated on output.",
    "diagnostic": "",
    "oqo": {
      "get_rows": "works",
      "filter_rows": [
        {
          "column_id": "authorships.institutions.lineage",
          "value": "I136199984"
        }
      ]
    }
  },
  {
    "id": "ENT2",
    "category": "entity references",
    "source": "spec spine",
    "status": "ok",
    "oql": "works where institution is I136199984 [those Harvard bastards, go Yale]",
    "note": "The annotation is free text and is not validated — it cannot lie because nothing reads it.",
    "diagnostic": "",
    "oqo": {
      "get_rows": "works",
      "filter_rows": [
        {
          "column_id": "authorships.institutions.lineage",
          "value": "I136199984"
        }
      ]
    }
  },
  {
    "id": "ENT3",
    "category": "entity references",
    "source": "spec spine",
    "status": "ok",
    "oql": "works where institution is any of (I33213144 [Harvard], I97018004 [Stanford])",
    "note": "( ... ) is a value list here; per-item annotations allowed.",
    "diagnostic": "",
    "oqo": {
      "get_rows": "works",
      "filter_rows": [
        {
          "join": "or",
          "filters": [
            {
              "column_id": "authorships.institutions.lineage",
              "value": "I33213144"
            },
            {
              "column_id": "authorships.institutions.lineage",
              "value": "I97018004"
            }
          ]
        }
      ]
    }
  },
  {
    "id": "ENT4",
    "category": "entity references",
    "source": "spec spine",
    "status": "ok",
    "oql": "works where institution is not any of (I33213144, I97018004)",
    "note": "Negated set = NOT(a OR b) = (NOT a) AND (NOT b) by De Morgan; canonical NNF carries negation on the leaves.",
    "diagnostic": "",
    "oqo": {
      "get_rows": "works",
      "filter_rows": [
        {
          "column_id": "authorships.institutions.lineage",
          "value": "I33213144",
          "is_negated": true
        },
        {
          "column_id": "authorships.institutions.lineage",
          "value": "I97018004",
          "is_negated": true
        }
      ]
    }
  },
  {
    "id": "ENT5",
    "category": "entity references",
    "source": "spec spine",
    "status": "ok",
    "oql": "works where type is in (article, review)",
    "note": "`is in` is accepted on input; canonical output spells it `is any of`.",
    "diagnostic": "",
    "oqo": {
      "get_rows": "works",
      "filter_rows": [
        {
          "join": "or",
          "filters": [
            {
              "column_id": "type",
              "value": "article"
            },
            {
              "column_id": "type",
              "value": "review"
            }
          ]
        }
      ]
    }
  },
  {
    "id": "ENT6",
    "category": "entity references",
    "source": "spec spine",
    "status": "error",
    "oql": "works where institution is [Harvard]",
    "note": "A display-name annotation with no ID — the v1.1 silent-mismatch footgun, now a loud error.",
    "diagnostic": "OQL_MISSING_ENTITY_ID",
    "oqo": null
  },
  {
    "id": "BOOL1",
    "category": "boolean logic",
    "source": "spec spine",
    "status": "ok",
    "oql": "works where title contains apple and (banana or cherry)",
    "note": "Mixed and/or with explicit parens is unambiguous.",
    "diagnostic": "",
    "oqo": {
      "get_rows": "works",
      "filter_rows": [
        {
          "column_id": "display_name.search",
          "value": "apple",
          "operator": "contains"
        },
        {
          "join": "or",
          "filters": [
            {
              "column_id": "display_name.search",
              "value": "banana",
              "operator": "contains"
            },
            {
              "column_id": "display_name.search",
              "value": "cherry",
              "operator": "contains"
            }
          ]
        }
      ]
    }
  },
  {
    "id": "BOOL2",
    "category": "boolean logic",
    "source": "spec spine",
    "status": "error",
    "oql": "works where title contains apple and banana or cherry",
    "note": "Explicit mixed and/or at one level with no parens — the one deliberate departure from WoS/Scopus.",
    "diagnostic": "OQL_MIXED_BOOL_NEEDS_PARENS",
    "oqo": null
  },
  {
    "id": "BOOL3",
    "category": "boolean logic",
    "source": "spec spine",
    "status": "ok",
    "oql": "works where title contains apple and banana and cherry",
    "note": "Pure-and is associative, no parens needed.",
    "diagnostic": "",
    "oqo": {
      "get_rows": "works",
      "filter_rows": [
        {
          "column_id": "display_name.search",
          "value": "apple",
          "operator": "contains"
        },
        {
          "column_id": "display_name.search",
          "value": "banana",
          "operator": "contains"
        },
        {
          "column_id": "display_name.search",
          "value": "cherry",
          "operator": "contains"
        }
      ]
    }
  },
  {
    "id": "BOOL4",
    "category": "boolean logic",
    "source": "spec spine",
    "status": "ok",
    "oql": "works where title contains apple banana cherry",
    "note": "SPACE = implicit AND (Google/PubMed convention) — `apple banana cherry` == `apple and banana and cherry`.",
    "diagnostic": "",
    "oqo": {
      "get_rows": "works",
      "filter_rows": [
        {
          "column_id": "display_name.search",
          "value": "apple",
          "operator": "contains"
        },
        {
          "column_id": "display_name.search",
          "value": "banana",
          "operator": "contains"
        },
        {
          "column_id": "display_name.search",
          "value": "cherry",
          "operator": "contains"
        }
      ]
    }
  },
  {
    "id": "G1",
    "category": "search semantics",
    "source": "spec spine",
    "status": "ok",
    "oql": "works where title contains climate change",
    "note": "SPACE = stemmed AND; the words may be apart (recall). The everyday default.",
    "diagnostic": "",
    "oqo": {
      "get_rows": "works",
      "filter_rows": [
        {
          "column_id": "display_name.search",
          "value": "climate",
          "operator": "contains"
        },
        {
          "column_id": "display_name.search",
          "value": "change",
          "operator": "contains"
        }
      ]
    }
  },
  {
    "id": "G2",
    "category": "search semantics",
    "source": "spec spine",
    "status": "ok",
    "oql": "works where title contains \"climate change\"",
    "note": "QUOTES = exact adjacent phrase, stemming OFF (.search.exact). The precision lever.",
    "diagnostic": "",
    "oqo": {
      "get_rows": "works",
      "filter_rows": [
        {
          "column_id": "display_name.search.exact",
          "value": "\"climate change\"",
          "operator": "contains"
        }
      ]
    }
  },
  {
    "id": "G3",
    "category": "search semantics",
    "source": "spec spine",
    "status": "ok",
    "oql": "works where title contains near \"whopper junior\"",
    "note": "NEAR = stemmed adjacent phrase (.search) → matches \"whoppers junior\". The bridge that keeps recall on a phrase.",
    "diagnostic": "",
    "oqo": {
      "get_rows": "works",
      "filter_rows": [
        {
          "column_id": "display_name.search",
          "value": "\"whopper junior\"",
          "operator": "contains"
        }
      ]
    }
  },
  {
    "id": "G4",
    "category": "search semantics",
    "source": "spec spine",
    "status": "ok",
    "oql": "works where title contains \"cat\"",
    "note": "Quoting a SINGLE word = exact (no plurals). Same rule as a phrase — quotes always mean exact.",
    "diagnostic": "",
    "oqo": {
      "get_rows": "works",
      "filter_rows": [
        {
          "column_id": "display_name.search.exact",
          "value": "cat",
          "operator": "contains"
        }
      ]
    }
  },
  {
    "id": "G5",
    "category": "search semantics",
    "source": "spec spine",
    "status": "ok",
    "oql": "works where title contains cat",
    "note": "Bare word = stemmed (matches cats). Contrast with G4 \"cat\" (exact).",
    "diagnostic": "",
    "oqo": {
      "get_rows": "works",
      "filter_rows": [
        {
          "column_id": "display_name.search",
          "value": "cat",
          "operator": "contains"
        }
      ]
    }
  },
  {
    "id": "G6",
    "category": "search semantics",
    "source": "spec spine",
    "status": "ok",
    "oql": "works where title contains \"rock or roll\"",
    "note": "Inside quotes = literal: the `or` is a word, not a connective. One exact phrase.",
    "diagnostic": "",
    "oqo": {
      "get_rows": "works",
      "filter_rows": [
        {
          "column_id": "display_name.search.exact",
          "value": "\"rock or roll\"",
          "operator": "contains"
        }
      ]
    }
  },
  {
    "id": "G7",
    "category": "search semantics",
    "source": "spec spine",
    "status": "error",
    "oql": "works where title contains climate change or warming",
    "note": "A space is an AND, so this mixes and/or at one level → loud error (no silent order-of-operations). Fix-it offers `climate (change or warming)` or `(climate change) or warming`.",
    "diagnostic": "OQL_MIXED_BOOL_NEEDS_PARENS",
    "oqo": null
  },
  {
    "id": "G7b",
    "category": "search semantics",
    "source": "spec spine",
    "status": "ok",
    "oql": "works where title contains climate (change or warming)",
    "note": "The likely-intended disambiguation: climate AND (change OR warming). Implicit AND between `climate` and the group; the only `or` is nested.",
    "diagnostic": "",
    "oqo": {
      "get_rows": "works",
      "filter_rows": [
        {
          "column_id": "display_name.search",
          "value": "climate",
          "operator": "contains"
        },
        {
          "join": "or",
          "filters": [
            {
              "column_id": "display_name.search",
              "value": "change",
              "operator": "contains"
            },
            {
              "column_id": "display_name.search",
              "value": "warming",
              "operator": "contains"
            }
          ]
        }
      ]
    }
  },
  {
    "id": "G8",
    "category": "search semantics",
    "source": "spec spine",
    "status": "error",
    "oql": "works where title contains \"bar*\"",
    "note": "`*` inside quotes can't wildcard. Fix-it: use bar* unquoted.",
    "diagnostic": "OQL_WILDCARD_IN_QUOTES",
    "oqo": null
  },
  {
    "id": "G9",
    "category": "search semantics",
    "source": "spec spine",
    "status": "ok",
    "oql": "works where title contains bar*",
    "note": "Bare prefix wildcard (stemmed column).",
    "diagnostic": "",
    "oqo": {
      "get_rows": "works",
      "filter_rows": [
        {
          "column_id": "display_name.search",
          "value": "bar*",
          "operator": "contains"
        }
      ]
    }
  },
  {
    "id": "PW1",
    "category": "proximity & wildcards",
    "source": "spec spine",
    "status": "ok",
    "oql": "works where title contains \"smart phone\" within 3 words",
    "note": "Exact proximity (quoted) → up to N positional moves apart, any order.",
    "diagnostic": "",
    "oqo": {
      "get_rows": "works",
      "filter_rows": [
        {
          "column_id": "display_name.search.exact",
          "value": "\"smart phone\"~3",
          "operator": "contains"
        }
      ]
    }
  },
  {
    "id": "PW2",
    "category": "proximity & wildcards",
    "source": "spec spine",
    "status": "ok",
    "oql": "works where title contains foo*bar",
    "note": "Mid-word `*` (>=3-char prefix, within one token).",
    "diagnostic": "",
    "oqo": {
      "get_rows": "works",
      "filter_rows": [
        {
          "column_id": "display_name.search",
          "value": "foo*bar",
          "operator": "contains"
        }
      ]
    }
  },
  {
    "id": "PW3",
    "category": "proximity & wildcards",
    "source": "spec spine",
    "status": "ok",
    "oql": "works where title contains wom?n",
    "note": "Mid-word `?` = exactly one character.",
    "diagnostic": "",
    "oqo": {
      "get_rows": "works",
      "filter_rows": [
        {
          "column_id": "display_name.search",
          "value": "wom?n",
          "operator": "contains"
        }
      ]
    }
  },
  {
    "id": "PW4",
    "category": "proximity & wildcards",
    "source": "spec spine",
    "status": "error",
    "oql": "works where title contains *cycle",
    "note": "Leading `*` unsupported (perf; allow_leading_wildcard=False).",
    "diagnostic": "OQL_LEADING_WILDCARD",
    "oqo": null
  },
  {
    "id": "PW5",
    "category": "proximity & wildcards",
    "source": "spec spine",
    "status": "error",
    "oql": "works where title contains ?cycle",
    "note": "Leading `?` unsupported.",
    "diagnostic": "OQL_LEADING_WILDCARD",
    "oqo": null
  },
  {
    "id": "PW6",
    "category": "proximity & wildcards",
    "source": "spec spine",
    "status": "error",
    "oql": "works where title contains ab*",
    "note": "Sub-3-char prefix -> error, not a silent literal.",
    "diagnostic": "OQL_SHORT_WILDCARD_PREFIX",
    "oqo": null
  },
  {
    "id": "PW7",
    "category": "proximity & wildcards",
    "source": "spec spine",
    "status": "error",
    "oql": "works where title contains \"smart phone*\" within 3 words",
    "note": "Wildcard inside a phrase — acknowledged limitation (WoS/Scopus do it; ES query_string drops it). Loud error today; future engine work.",
    "diagnostic": "OQL_WILDCARD_IN_QUOTES",
    "oqo": null
  },
  {
    "id": "PW8",
    "category": "proximity & wildcards",
    "source": "spec spine",
    "status": "error",
    "oql": "works where title contains \"smart\" within 3 words of \"phone\"",
    "note": "Binary \"X within N of Y\" is unsupported (ES slop is whole-phrase); loud error.",
    "diagnostic": "OQL_BINARY_PROXIMITY",
    "oqo": null
  },
  {
    "id": "PW9",
    "category": "proximity & wildcards",
    "source": "spec spine",
    "status": "error",
    "oql": "works where title contains smart* within 3 words",
    "note": "Wildcard + proximity can't compose.",
    "diagnostic": "OQL_WILDCARD_IN_PROXIMITY",
    "oqo": null
  },
  {
    "id": "PW10",
    "category": "proximity & wildcards",
    "source": "spec spine",
    "status": "ok",
    "oql": "works where abstract is similar to \"graph neural networks for molecular property prediction\"",
    "note": "Semantic (search.semantic, 2-phase vector search).",
    "diagnostic": "",
    "oqo": {
      "get_rows": "works",
      "filter_rows": [
        {
          "column_id": "abstract.search.semantic",
          "value": "graph neural networks for molecular property prediction",
          "operator": "contains"
        }
      ]
    }
  },
  {
    "id": "PW11",
    "category": "proximity & wildcards",
    "source": "spec spine",
    "status": "ok",
    "oql": "works where title & abstract contains \"machine learning\"",
    "note": "Exact phrase, no stemming (.search.exact).",
    "diagnostic": "",
    "oqo": {
      "get_rows": "works",
      "filter_rows": [
        {
          "column_id": "title_and_abstract.search.exact",
          "value": "\"machine learning\"",
          "operator": "contains"
        }
      ]
    }
  },
  {
    "id": "PW12",
    "category": "proximity & wildcards",
    "source": "spec spine",
    "status": "ok",
    "oql": "works where title contains near \"smart phone\" within 3 words",
    "note": "STEMMED proximity (near + within) → .search column; contrast PW1 (exact proximity).",
    "diagnostic": "",
    "oqo": {
      "get_rows": "works",
      "filter_rows": [
        {
          "column_id": "display_name.search",
          "value": "\"smart phone\"~3",
          "operator": "contains"
        }
      ]
    }
  },
  {
    "id": "A01",
    "category": "filter, sort & sample",
    "source": "#284 worked examples",
    "status": "ok",
    "oql": "works",
    "note": "Bare entity query, no filters.",
    "diagnostic": "",
    "oqo": {
      "get_rows": "works"
    }
  },
  {
    "id": "A02",
    "category": "filter, sort & sample",
    "source": "#284 worked examples",
    "status": "ok",
    "oql": "works where year is 2020",
    "note": "",
    "diagnostic": "",
    "oqo": {
      "get_rows": "works",
      "filter_rows": [
        {
          "column_id": "publication_year",
          "value": 2020
        }
      ]
    }
  },
  {
    "id": "A03",
    "category": "filter, sort & sample",
    "source": "#284 worked examples",
    "status": "ok",
    "oql": "works where institution is any of (I33213144 [University of Florida], I136199984 [Harvard]) and year >= 2020",
    "note": "",
    "diagnostic": "",
    "oqo": {
      "get_rows": "works",
      "filter_rows": [
        {
          "join": "or",
          "filters": [
            {
              "column_id": "authorships.institutions.lineage",
              "value": "I33213144"
            },
            {
              "column_id": "authorships.institutions.lineage",
              "value": "I136199984"
            }
          ]
        },
        {
          "column_id": "publication_year",
          "value": 2020,
          "operator": ">="
        }
      ]
    }
  },
  {
    "id": "A04",
    "category": "filter, sort & sample",
    "source": "#284 worked examples",
    "status": "ok",
    "oql": "works where institution is I130438778 [Memorial University of Newfoundland]; sort by citations desc",
    "note": "",
    "diagnostic": "",
    "oqo": {
      "get_rows": "works",
      "filter_rows": [
        {
          "column_id": "authorships.institutions.lineage",
          "value": "I130438778"
        }
      ],
      "sort_by": [
        {
          "column_id": "cited_by_count",
          "direction": "desc"
        }
      ]
    }
  },
  {
    "id": "A05",
    "category": "filter, sort & sample",
    "source": "#284 worked examples",
    "status": "ok",
    "oql": "works where institution is I201448701 [UW] AND funder is F4320332161 [NIH] AND it's not open access",
    "note": "",
    "diagnostic": "",
    "oqo": {
      "get_rows": "works",
      "filter_rows": [
        {
          "column_id": "authorships.institutions.lineage",
          "value": "I201448701"
        },
        {
          "column_id": "funders.id",
          "value": "F4320332161"
        },
        {
          "column_id": "open_access.is_oa",
          "value": false
        }
      ]
    }
  },
  {
    "id": "A06",
    "category": "filter, sort & sample",
    "source": "#284 worked examples",
    "status": "ok",
    "oql": "works where title & abstract contains climate change",
    "note": "Bare = stemmed AND — exactly what the #284 OXURL did (space = AND on .search). Use `near \"climate change\"` for an adjacent phrase.",
    "diagnostic": "",
    "oqo": {
      "get_rows": "works",
      "filter_rows": [
        {
          "column_id": "title_and_abstract.search",
          "value": "climate",
          "operator": "contains"
        },
        {
          "column_id": "title_and_abstract.search",
          "value": "change",
          "operator": "contains"
        }
      ]
    }
  },
  {
    "id": "A07",
    "category": "filter, sort & sample",
    "source": "#284 worked examples",
    "status": "ok",
    "oql": "authors; sort by works_count desc",
    "note": "",
    "diagnostic": "",
    "oqo": {
      "get_rows": "authors",
      "sort_by": [
        {
          "column_id": "works_count",
          "direction": "desc"
        }
      ]
    }
  },
  {
    "id": "A08",
    "category": "filter, sort & sample",
    "source": "#284 worked examples",
    "status": "ok",
    "oql": "authors where author country is BR and it has an ORCID",
    "note": "",
    "diagnostic": "",
    "oqo": {
      "get_rows": "authors",
      "filter_rows": [
        {
          "column_id": "last_known_institutions.country_code",
          "value": "BR"
        },
        {
          "column_id": "has_orcid",
          "value": true
        }
      ]
    }
  },
  {
    "id": "A09",
    "category": "filter, sort & sample",
    "source": "#284 worked examples",
    "status": "ok",
    "oql": "authors where openalex id is A5022654839",
    "note": "",
    "diagnostic": "",
    "oqo": {
      "get_rows": "authors",
      "filter_rows": [
        {
          "column_id": "ids.openalex",
          "value": "A5022654839"
        }
      ]
    }
  },
  {
    "id": "A10",
    "category": "filter, sort & sample",
    "source": "#284 worked examples",
    "status": "ok",
    "oql": "sources where type is journal",
    "note": "",
    "diagnostic": "",
    "oqo": {
      "get_rows": "sources",
      "filter_rows": [
        {
          "column_id": "type",
          "value": "journal"
        }
      ]
    }
  },
  {
    "id": "A11",
    "category": "filter, sort & sample",
    "source": "#284 worked examples",
    "status": "ok",
    "oql": "institutions where country code is FR",
    "note": "",
    "diagnostic": "",
    "oqo": {
      "get_rows": "institutions",
      "filter_rows": [
        {
          "column_id": "country_code",
          "value": "FR"
        }
      ]
    }
  },
  {
    "id": "A12",
    "category": "filter, sort & sample",
    "source": "#284 worked examples",
    "status": "ok",
    "oql": "topics where domain is 3",
    "note": "",
    "diagnostic": "",
    "oqo": {
      "get_rows": "topics",
      "filter_rows": [
        {
          "column_id": "domain.id",
          "value": "3"
        }
      ]
    }
  },
  {
    "id": "A13",
    "category": "filter, sort & sample",
    "source": "#284 worked examples",
    "status": "ok",
    "oql": "authors where last known institution is I114027177 [UNC] and topics is T10895 [climate change]",
    "note": "",
    "diagnostic": "",
    "oqo": {
      "get_rows": "authors",
      "filter_rows": [
        {
          "column_id": "last_known_institutions.id",
          "value": "I114027177"
        },
        {
          "column_id": "topics.id",
          "value": "T10895"
        }
      ]
    }
  },
  {
    "id": "B01",
    "category": "group by",
    "source": "#284 worked examples",
    "status": "ok",
    "oql": "works where author is A5066175077 [Stephen Hawking]; group by author",
    "note": "",
    "diagnostic": "",
    "oqo": {
      "get_rows": "works",
      "filter_rows": [
        {
          "column_id": "authorships.author.id",
          "value": "A5066175077"
        }
      ],
      "group_by": [
        {
          "column_id": "authorships.author.id"
        }
      ]
    }
  },
  {
    "id": "B02",
    "category": "group by",
    "source": "#284 worked examples",
    "status": "ok",
    "oql": "works where anywhere contains near \"Macrocystis pyrifera\"; group by author",
    "note": "A species name is a phrase but recall matters → `near` (stemmed adjacent), not exact quotes.",
    "diagnostic": "",
    "oqo": {
      "get_rows": "works",
      "filter_rows": [
        {
          "column_id": "default.search",
          "value": "\"Macrocystis pyrifera\"",
          "operator": "contains"
        }
      ],
      "group_by": [
        {
          "column_id": "authorships.author.id"
        }
      ]
    }
  },
  {
    "id": "B03",
    "category": "group by",
    "source": "#284 worked examples",
    "status": "ok",
    "oql": "works where year >= 1976; group by topic, year",
    "note": "Multi-dim group_by is expressible in the spec (live API single-dim only ->",
    "diagnostic": "",
    "oqo": {
      "get_rows": "works",
      "filter_rows": [
        {
          "column_id": "publication_year",
          "value": 1976,
          "operator": ">="
        }
      ],
      "group_by": [
        {
          "column_id": "primary_topic.id"
        },
        {
          "column_id": "publication_year"
        }
      ]
    }
  },
  {
    "id": "B04",
    "category": "group by",
    "source": "#284 worked examples",
    "status": "ok",
    "oql": "works where country is col_eu27 and country is US; group by topic",
    "note": "col_eu27 is a collection reference — a valid bare value (it self-identifies via col_).",
    "diagnostic": "",
    "oqo": {
      "get_rows": "works",
      "filter_rows": [
        {
          "column_id": "authorships.countries",
          "value": "col_eu27"
        },
        {
          "column_id": "authorships.countries",
          "value": "US"
        }
      ],
      "group_by": [
        {
          "column_id": "primary_topic.id"
        }
      ]
    }
  },
  {
    "id": "B05",
    "category": "group by",
    "source": "#284 worked examples",
    "status": "ok",
    "oql": "works where it's retracted; group by institution",
    "note": "",
    "diagnostic": "",
    "oqo": {
      "get_rows": "works",
      "filter_rows": [
        {
          "column_id": "is_retracted",
          "value": true
        }
      ],
      "group_by": [
        {
          "column_id": "authorships.institutions.lineage"
        }
      ]
    }
  },
  {
    "id": "B06",
    "category": "group by",
    "source": "#284 worked examples",
    "status": "ok",
    "oql": "works where title & abstract contains near \"coral bleaching\" and citations > 100; group by source",
    "note": "",
    "diagnostic": "",
    "oqo": {
      "get_rows": "works",
      "filter_rows": [
        {
          "column_id": "title_and_abstract.search",
          "value": "\"coral bleaching\"",
          "operator": "contains"
        },
        {
          "column_id": "cited_by_count",
          "value": 100,
          "operator": ">"
        }
      ],
      "group_by": [
        {
          "column_id": "primary_location.source.id"
        }
      ]
    }
  },
  {
    "id": "B07",
    "category": "group by",
    "source": "#284 worked examples",
    "status": "ok",
    "oql": "works where type is book; group by field",
    "note": "",
    "diagnostic": "",
    "oqo": {
      "get_rows": "works",
      "filter_rows": [
        {
          "column_id": "type",
          "value": "book"
        }
      ],
      "group_by": [
        {
          "column_id": "primary_topic.field.id"
        }
      ]
    }
  },
  {
    "id": "B08",
    "category": "group by",
    "source": "#284 worked examples",
    "status": "ok",
    "oql": "works where institution is I154570441 [UCSB] AND it's retracted; group by author",
    "note": "",
    "diagnostic": "",
    "oqo": {
      "get_rows": "works",
      "filter_rows": [
        {
          "column_id": "authorships.institutions.lineage",
          "value": "I154570441"
        },
        {
          "column_id": "is_retracted",
          "value": true
        }
      ],
      "group_by": [
        {
          "column_id": "authorships.author.id"
        }
      ]
    }
  },
  {
    "id": "B09",
    "category": "group by",
    "source": "#284 worked examples",
    "status": "ok",
    "oql": "works where institution is I107639228 [Notre Dame]; group by SDG",
    "note": "",
    "diagnostic": "",
    "oqo": {
      "get_rows": "works",
      "filter_rows": [
        {
          "column_id": "authorships.institutions.lineage",
          "value": "I107639228"
        }
      ],
      "group_by": [
        {
          "column_id": "sustainable_development_goals.id"
        }
      ]
    }
  },
  {
    "id": "L01",
    "category": "librarian & SR queries",
    "source": "#284 worked examples",
    "status": "ok",
    "oql": "works where title & abstract contains agile and title & abstract contains any of (near \"supply chain\", near \"demand chain\", near \"value chain\") and title & abstract contains any of (near \"lead time\", near \"cycle time\")",
    "note": "AND of OR-groups; the synonym phrases use `near` (stemmed adjacent) for recall. Top level is pure-and so no parens.",
    "diagnostic": "",
    "oqo": {
      "get_rows": "works",
      "filter_rows": [
        {
          "column_id": "title_and_abstract.search",
          "value": "agile",
          "operator": "contains"
        },
        {
          "join": "or",
          "filters": [
            {
              "column_id": "title_and_abstract.search",
              "value": "\"supply chain\"",
              "operator": "contains"
            },
            {
              "column_id": "title_and_abstract.search",
              "value": "\"demand chain\"",
              "operator": "contains"
            },
            {
              "column_id": "title_and_abstract.search",
              "value": "\"value chain\"",
              "operator": "contains"
            }
          ]
        },
        {
          "join": "or",
          "filters": [
            {
              "column_id": "title_and_abstract.search",
              "value": "\"lead time\"",
              "operator": "contains"
            },
            {
              "column_id": "title_and_abstract.search",
              "value": "\"cycle time\"",
              "operator": "contains"
            }
          ]
        }
      ]
    }
  },
  {
    "id": "L02a",
    "category": "librarian & SR queries",
    "source": "#284 worked examples",
    "status": "ok",
    "oql": "works where title & abstract contains near \"smart phone\" within 3 words",
    "note": "Stemmed proximity (`near`) → .search, matching the #284 column. Use plain quotes for exact proximity.",
    "diagnostic": "",
    "oqo": {
      "get_rows": "works",
      "filter_rows": [
        {
          "column_id": "title_and_abstract.search",
          "value": "\"smart phone\"~3",
          "operator": "contains"
        }
      ]
    }
  },
  {
    "id": "L02b",
    "category": "librarian & SR queries",
    "source": "#284 worked examples",
    "status": "ok",
    "oql": "works where title & abstract contains phone*",
    "note": "Spec ✓ (trailing wildcard). ENGINE BUG: the live server 500s on this today (see evidence/engine_findings.md).",
    "diagnostic": "",
    "oqo": {
      "get_rows": "works",
      "filter_rows": [
        {
          "column_id": "title_and_abstract.search",
          "value": "phone*",
          "operator": "contains"
        }
      ]
    }
  },
  {
    "id": "L02c",
    "category": "librarian & SR queries",
    "source": "#284 worked examples",
    "status": "boundary",
    "oql": "works where title & abstract contains \"smart phone*\" within 3 words",
    "note": "Wildcard-in-proximity. ACKNOWLEDGED LIMITATION (not a permanent boundary): WoS/Scopus support it; our ES query_string path drops the wildcard (verified live). Rejected loudly today (PW7); fixable via ES intervals/span queries → future engine work (lift-to-structure rec / #337 / #298).",
    "diagnostic": "OQL_WILDCARD_IN_QUOTES",
    "oqo": null
  },
  {
    "id": "L03",
    "category": "librarian & SR queries",
    "source": "#284 worked examples",
    "status": "ok",
    "oql": "works where title & abstract contains \"oyster toadfish\"",
    "note": "NL says \"exact phrase only, no lemmatization\" → plain quotes (exact, .search.exact). The textbook quotes-mean-exact case.",
    "diagnostic": "",
    "oqo": {
      "get_rows": "works",
      "filter_rows": [
        {
          "column_id": "title_and_abstract.search.exact",
          "value": "\"oyster toadfish\"",
          "operator": "contains"
        }
      ]
    }
  },
  {
    "id": "L04",
    "category": "librarian & SR queries",
    "source": "#284 worked examples",
    "status": "ok",
    "oql": "works where title & abstract contains behavio*r",
    "note": "Mid-word wildcard (UK/US spellings in one query).",
    "diagnostic": "",
    "oqo": {
      "get_rows": "works",
      "filter_rows": [
        {
          "column_id": "title_and_abstract.search",
          "value": "behavio*r",
          "operator": "contains"
        }
      ]
    }
  },
  {
    "id": "L05",
    "category": "librarian & SR queries",
    "source": "#284 worked examples",
    "status": "ok",
    "oql": "works where title & abstract contains any of (autism, ASD, near \"autism spectrum disorder\") and title & abstract contains any of (intervention, therapy, treatment) and year >= 2015 and year <= 2024 and type is any of (article, review) and language is en",
    "note": "",
    "diagnostic": "",
    "oqo": {
      "get_rows": "works",
      "filter_rows": [
        {
          "join": "or",
          "filters": [
            {
              "column_id": "title_and_abstract.search",
              "value": "autism",
              "operator": "contains"
            },
            {
              "column_id": "title_and_abstract.search",
              "value": "ASD",
              "operator": "contains"
            },
            {
              "column_id": "title_and_abstract.search",
              "value": "\"autism spectrum disorder\"",
              "operator": "contains"
            }
          ]
        },
        {
          "join": "or",
          "filters": [
            {
              "column_id": "title_and_abstract.search",
              "value": "intervention",
              "operator": "contains"
            },
            {
              "column_id": "title_and_abstract.search",
              "value": "therapy",
              "operator": "contains"
            },
            {
              "column_id": "title_and_abstract.search",
              "value": "treatment",
              "operator": "contains"
            }
          ]
        },
        {
          "column_id": "publication_year",
          "value": 2015,
          "operator": ">="
        },
        {
          "column_id": "publication_year",
          "value": 2024,
          "operator": "<="
        },
        {
          "join": "or",
          "filters": [
            {
              "column_id": "type",
              "value": "article"
            },
            {
              "column_id": "type",
              "value": "review"
            }
          ]
        },
        {
          "column_id": "language",
          "value": "en"
        }
      ]
    }
  },
  {
    "id": "L06",
    "category": "librarian & SR queries",
    "source": "#284 worked examples",
    "status": "ok",
    "oql": "works where OA status is gold and funder is F4320337351 [NCI]",
    "note": "",
    "diagnostic": "",
    "oqo": {
      "get_rows": "works",
      "filter_rows": [
        {
          "column_id": "open_access.oa_status",
          "value": "gold"
        },
        {
          "column_id": "funders.id",
          "value": "F4320337351"
        }
      ]
    }
  },
  {
    "id": "L07",
    "category": "librarian & SR queries",
    "source": "#284 worked examples",
    "status": "ok",
    "oql": "works where title & abstract contains CRISPR and near \"genome editing\" and year >= 2018 and year <= 2023; sort by citations desc; sample 500",
    "note": "Mixes a bare token (CRISPR, stemmed) with a `near` phrase (genome editing) — the explicit version of #284's loose multi-word search.",
    "diagnostic": "",
    "oqo": {
      "get_rows": "works",
      "filter_rows": [
        {
          "column_id": "title_and_abstract.search",
          "value": "CRISPR",
          "operator": "contains"
        },
        {
          "column_id": "title_and_abstract.search",
          "value": "\"genome editing\"",
          "operator": "contains"
        },
        {
          "column_id": "publication_year",
          "value": 2018,
          "operator": ">="
        },
        {
          "column_id": "publication_year",
          "value": 2023,
          "operator": "<="
        }
      ],
      "sort_by": [
        {
          "column_id": "cited_by_count",
          "direction": "desc"
        }
      ],
      "sample": 500
    }
  },
  {
    "id": "L08",
    "category": "librarian & SR queries",
    "source": "#284 worked examples",
    "status": "ok",
    "oql": "works where raw affiliation contains library",
    "note": "",
    "diagnostic": "",
    "oqo": {
      "get_rows": "works",
      "filter_rows": [
        {
          "column_id": "raw_affiliation_strings.search",
          "value": "library",
          "operator": "contains"
        }
      ]
    }
  },
  {
    "id": "L09",
    "category": "librarian & SR queries",
    "source": "#284 worked examples",
    "status": "ok",
    "oql": "works where raw affiliation contains near \"london hospital\" within 5 words",
    "note": "Quoted phrase scopes to ONE affiliation (position_increment_gap); slop ~5 allows order/gap within it.",
    "diagnostic": "",
    "oqo": {
      "get_rows": "works",
      "filter_rows": [
        {
          "column_id": "raw_affiliation_strings.search",
          "value": "\"london hospital\"~5",
          "operator": "contains"
        }
      ]
    }
  },
  {
    "id": "L10",
    "category": "librarian & SR queries",
    "source": "#284 worked examples",
    "status": "ok",
    "oql": "works where DOI is 10.1021/es052595+",
    "note": "Reserved chars (+, /) are ordinary inside a bare value; no escaping in OQL.",
    "diagnostic": "",
    "oqo": {
      "get_rows": "works",
      "filter_rows": [
        {
          "column_id": "doi",
          "value": "10.1021/es052595+"
        }
      ]
    }
  },
  {
    "id": "L11",
    "category": "librarian & SR queries",
    "source": "#284 worked examples",
    "status": "ok",
    "oql": "works where ORCID is 0000-0002-1838-9363",
    "note": "",
    "diagnostic": "",
    "oqo": {
      "get_rows": "works",
      "filter_rows": [
        {
          "column_id": "authorships.author.orcid",
          "value": "0000-0002-1838-9363"
        }
      ]
    }
  },
  {
    "id": "L12",
    "category": "librarian & SR queries",
    "source": "#284 worked examples",
    "status": "boundary",
    "oql": null,
    "note": "\"funded by the acronym DFG\" — not representable. OQO only expresses funders.id equality AFTER an out-of-band /funders?search=DFG -> ID resolution; the acronym has no OQL/OQO form.",
    "diagnostic": "",
    "oqo": null
  },
  {
    "id": "L13",
    "category": "librarian & SR queries",
    "source": "#284 worked examples",
    "status": "ok",
    "oql": "works where type is any of (article, review)",
    "note": "",
    "diagnostic": "",
    "oqo": {
      "get_rows": "works",
      "filter_rows": [
        {
          "join": "or",
          "filters": [
            {
              "column_id": "type",
              "value": "article"
            },
            {
              "column_id": "type",
              "value": "review"
            }
          ]
        }
      ]
    }
  },
  {
    "id": "L14",
    "category": "librarian & SR queries",
    "source": "#284 worked examples",
    "status": "ok",
    "oql": "works where language is es",
    "note": "",
    "diagnostic": "",
    "oqo": {
      "get_rows": "works",
      "filter_rows": [
        {
          "column_id": "language",
          "value": "es"
        }
      ]
    }
  },
  {
    "id": "L15",
    "category": "librarian & SR queries",
    "source": "#284 worked examples",
    "status": "ok",
    "oql": "works where title & abstract contains covid and title & abstract does not contain pediatric",
    "note": "One negation mechanism: `does not contain` renders is_negated:true on a contains leaf.",
    "diagnostic": "",
    "oqo": {
      "get_rows": "works",
      "filter_rows": [
        {
          "column_id": "title_and_abstract.search",
          "value": "covid",
          "operator": "contains"
        },
        {
          "column_id": "title_and_abstract.search",
          "value": "pediatric",
          "operator": "contains",
          "is_negated": true
        }
      ]
    }
  },
  {
    "id": "L16",
    "category": "librarian & SR queries",
    "source": "#284 worked examples",
    "status": "ok",
    "oql": "works where title & abstract contains quantum computing; group by country",
    "note": "Bare = stemmed AND (faithful to the",
    "diagnostic": "",
    "oqo": {
      "get_rows": "works",
      "filter_rows": [
        {
          "column_id": "title_and_abstract.search",
          "value": "quantum",
          "operator": "contains"
        },
        {
          "column_id": "title_and_abstract.search",
          "value": "computing",
          "operator": "contains"
        }
      ],
      "group_by": [
        {
          "column_id": "authorships.countries"
        }
      ]
    }
  },
  {
    "id": "L17",
    "category": "librarian & SR queries",
    "source": "#284 worked examples",
    "status": "ok",
    "oql": "works where title & abstract contains CRISPR and Cas9; group by author",
    "note": "",
    "diagnostic": "",
    "oqo": {
      "get_rows": "works",
      "filter_rows": [
        {
          "column_id": "title_and_abstract.search",
          "value": "CRISPR",
          "operator": "contains"
        },
        {
          "column_id": "title_and_abstract.search",
          "value": "Cas9",
          "operator": "contains"
        }
      ],
      "group_by": [
        {
          "column_id": "authorships.author.id"
        }
      ]
    }
  },
  {
    "id": "L18",
    "category": "librarian & SR queries",
    "source": "#284 worked examples",
    "status": "ok",
    "oql": "works where title & abstract contains CRISPR; group by funder",
    "note": "Only the group-by-COUNT form is in scope. Ranking groups by mean citation impact is sort-by-aggregate -> #297.",
    "diagnostic": "",
    "oqo": {
      "get_rows": "works",
      "filter_rows": [
        {
          "column_id": "title_and_abstract.search",
          "value": "CRISPR",
          "operator": "contains"
        }
      ],
      "group_by": [
        {
          "column_id": "funders.id"
        }
      ]
    }
  },
  {
    "id": "L19",
    "category": "librarian & SR queries",
    "source": "#284 worked examples",
    "status": "ok",
    "oql": "works where raw affiliation contains near \"tufts boston\" within 5 words",
    "note": "",
    "diagnostic": "",
    "oqo": {
      "get_rows": "works",
      "filter_rows": [
        {
          "column_id": "raw_affiliation_strings.search",
          "value": "\"tufts boston\"~5",
          "operator": "contains"
        }
      ]
    }
  },
  {
    "id": "L20",
    "category": "librarian & SR queries",
    "source": "#284 worked examples",
    "status": "boundary",
    "oql": null,
    "note": "Set-reference / stateful query composition (refine a saved search) — no single OQO; out of scope.",
    "diagnostic": "",
    "oqo": null
  },
  {
    "id": "L22",
    "category": "librarian & SR queries",
    "source": "#284 worked examples",
    "status": "ok",
    "oql": "works where byline contains near \"john smith\" within 2 words",
    "note": "Byline slop ~2 recovers middle-name/initial forms without crossing co-authors.",
    "diagnostic": "",
    "oqo": {
      "get_rows": "works",
      "filter_rows": [
        {
          "column_id": "raw_author_name.search",
          "value": "\"john smith\"~2",
          "operator": "contains"
        }
      ]
    }
  },
  {
    "id": "L21",
    "category": "librarian & SR queries",
    "source": "#284 worked examples",
    "status": "ok",
    "oql": "works where title contains any of (obese, overweight, obesity, \"body image\", fat, fatness, thin, thinness, Height, weight, bodyweight, \"body hatred\", \"body positive\", \"thin ideal\", \"fat ideal\", \"body esteem\", \"body ideal\", \"ideal body\", \"body shape\", \"body size\", \"body sizes\", \"weight bias\", \"being fat\", \"being thin\", \"anti fat\", \"body shame\") and title & abstract contains any of (qualitative, \"focus group\", \"focus groups\", questionnaire, questionnaires, interview, interviews, experiences, \"lived experience\", perceptions, perspective, perspectives, attitude, attitudes, beliefs, diary, diaries) and title & abstract contains any of (qualitative, \"focus group\", \"focus groups\", \"semi structured\", semistructured, unstructured, informal, in-depth, indepth, open, \"open ended\", experiences, \"lived experience\", perceptions, perspective, perspectives, attitude, attitudes, beliefs, diary, diaries) and title contains any of (\"young people\", adolescent, youth, pubertal, pubescent, \"pre adolescent\", \"Pre pubescent\", \"pre pubertal\", teen, preteen, tweens, tweenage, youths, schoolboy, schoolgirl, \"school aged\", \"young person\", juvenile, Boy, boys, children, child's, Girl, girls, Minors, preadolescent, Prepubescent, schoolchild, \"early adolescent\") and anywhere contains any of (GB, Britain, UK, \"United Kingdom\", England, \"Northern Ireland\", \"Northern Irish\", \"North Ireland\", \"North Irish\", Scotland, Scottish, Wales, Welsh, \"english boys\", \"English girls\", \"english school\", \"English children\", \"English teen\", \"English adolescent\", \"English young people\", \"English schoolchild\")",
    "note": "The real zd#8101 systematic-review tree (Claire): a 5-block AND of large OR-synonym groups, each block scoped to a different search field (title / title & abstract x2 / anywhere). 114 leaves. No explicit oqo oracle — the harness asserts OQO->OQL->OQO identity through the whole tree.",
    "diagnostic": "",
    "oqo": {
      "get_rows": "works",
      "filter_rows": [
        {
          "join": "or",
          "filters": [
            {
              "column_id": "display_name.search",
              "value": "obese",
              "operator": "contains"
            },
            {
              "column_id": "display_name.search",
              "value": "overweight",
              "operator": "contains"
            },
            {
              "column_id": "display_name.search",
              "value": "obesity",
              "operator": "contains"
            },
            {
              "column_id": "display_name.search.exact",
              "value": "\"body image\"",
              "operator": "contains"
            },
            {
              "column_id": "display_name.search",
              "value": "fat",
              "operator": "contains"
            },
            {
              "column_id": "display_name.search",
              "value": "fatness",
              "operator": "contains"
            },
            {
              "column_id": "display_name.search",
              "value": "thin",
              "operator": "contains"
            },
            {
              "column_id": "display_name.search",
              "value": "thinness",
              "operator": "contains"
            },
            {
              "column_id": "display_name.search",
              "value": "Height",
              "operator": "contains"
            },
            {
              "column_id": "display_name.search",
              "value": "weight",
              "operator": "contains"
            },
            {
              "column_id": "display_name.search",
              "value": "bodyweight",
              "operator": "contains"
            },
            {
              "column_id": "display_name.search.exact",
              "value": "\"body hatred\"",
              "operator": "contains"
            },
            {
              "column_id": "display_name.search.exact",
              "value": "\"body positive\"",
              "operator": "contains"
            },
            {
              "column_id": "display_name.search.exact",
              "value": "\"thin ideal\"",
              "operator": "contains"
            },
            {
              "column_id": "display_name.search.exact",
              "value": "\"fat ideal\"",
              "operator": "contains"
            },
            {
              "column_id": "display_name.search.exact",
              "value": "\"body esteem\"",
              "operator": "contains"
            },
            {
              "column_id": "display_name.search.exact",
              "value": "\"body ideal\"",
              "operator": "contains"
            },
            {
              "column_id": "display_name.search.exact",
              "value": "\"ideal body\"",
              "operator": "contains"
            },
            {
              "column_id": "display_name.search.exact",
              "value": "\"body shape\"",
              "operator": "contains"
            },
            {
              "column_id": "display_name.search.exact",
              "value": "\"body size\"",
              "operator": "contains"
            },
            {
              "column_id": "display_name.search.exact",
              "value": "\"body sizes\"",
              "operator": "contains"
            },
            {
              "column_id": "display_name.search.exact",
              "value": "\"weight bias\"",
              "operator": "contains"
            },
            {
              "column_id": "display_name.search.exact",
              "value": "\"being fat\"",
              "operator": "contains"
            },
            {
              "column_id": "display_name.search.exact",
              "value": "\"being thin\"",
              "operator": "contains"
            },
            {
              "column_id": "display_name.search.exact",
              "value": "\"anti fat\"",
              "operator": "contains"
            },
            {
              "column_id": "display_name.search.exact",
              "value": "\"body shame\"",
              "operator": "contains"
            }
          ]
        },
        {
          "join": "or",
          "filters": [
            {
              "column_id": "title_and_abstract.search",
              "value": "qualitative",
              "operator": "contains"
            },
            {
              "column_id": "title_and_abstract.search.exact",
              "value": "\"focus group\"",
              "operator": "contains"
            },
            {
              "column_id": "title_and_abstract.search.exact",
              "value": "\"focus groups\"",
              "operator": "contains"
            },
            {
              "column_id": "title_and_abstract.search",
              "value": "questionnaire",
              "operator": "contains"
            },
            {
              "column_id": "title_and_abstract.search",
              "value": "questionnaires",
              "operator": "contains"
            },
            {
              "column_id": "title_and_abstract.search",
              "value": "interview",
              "operator": "contains"
            },
            {
              "column_id": "title_and_abstract.search",
              "value": "interviews",
              "operator": "contains"
            },
            {
              "column_id": "title_and_abstract.search",
              "value": "experiences",
              "operator": "contains"
            },
            {
              "column_id": "title_and_abstract.search.exact",
              "value": "\"lived experience\"",
              "operator": "contains"
            },
            {
              "column_id": "title_and_abstract.search",
              "value": "perceptions",
              "operator": "contains"
            },
            {
              "column_id": "title_and_abstract.search",
              "value": "perspective",
              "operator": "contains"
            },
            {
              "column_id": "title_and_abstract.search",
              "value": "perspectives",
              "operator": "contains"
            },
            {
              "column_id": "title_and_abstract.search",
              "value": "attitude",
              "operator": "contains"
            },
            {
              "column_id": "title_and_abstract.search",
              "value": "attitudes",
              "operator": "contains"
            },
            {
              "column_id": "title_and_abstract.search",
              "value": "beliefs",
              "operator": "contains"
            },
            {
              "column_id": "title_and_abstract.search",
              "value": "diary",
              "operator": "contains"
            },
            {
              "column_id": "title_and_abstract.search",
              "value": "diaries",
              "operator": "contains"
            }
          ]
        },
        {
          "join": "or",
          "filters": [
            {
              "column_id": "title_and_abstract.search",
              "value": "qualitative",
              "operator": "contains"
            },
            {
              "column_id": "title_and_abstract.search.exact",
              "value": "\"focus group\"",
              "operator": "contains"
            },
            {
              "column_id": "title_and_abstract.search.exact",
              "value": "\"focus groups\"",
              "operator": "contains"
            },
            {
              "column_id": "title_and_abstract.search.exact",
              "value": "\"semi structured\"",
              "operator": "contains"
            },
            {
              "column_id": "title_and_abstract.search",
              "value": "semistructured",
              "operator": "contains"
            },
            {
              "column_id": "title_and_abstract.search",
              "value": "unstructured",
              "operator": "contains"
            },
            {
              "column_id": "title_and_abstract.search",
              "value": "informal",
              "operator": "contains"
            },
            {
              "column_id": "title_and_abstract.search",
              "value": "in-depth",
              "operator": "contains"
            },
            {
              "column_id": "title_and_abstract.search",
              "value": "indepth",
              "operator": "contains"
            },
            {
              "column_id": "title_and_abstract.search",
              "value": "open",
              "operator": "contains"
            },
            {
              "column_id": "title_and_abstract.search.exact",
              "value": "\"open ended\"",
              "operator": "contains"
            },
            {
              "column_id": "title_and_abstract.search",
              "value": "experiences",
              "operator": "contains"
            },
            {
              "column_id": "title_and_abstract.search.exact",
              "value": "\"lived experience\"",
              "operator": "contains"
            },
            {
              "column_id": "title_and_abstract.search",
              "value": "perceptions",
              "operator": "contains"
            },
            {
              "column_id": "title_and_abstract.search",
              "value": "perspective",
              "operator": "contains"
            },
            {
              "column_id": "title_and_abstract.search",
              "value": "perspectives",
              "operator": "contains"
            },
            {
              "column_id": "title_and_abstract.search",
              "value": "attitude",
              "operator": "contains"
            },
            {
              "column_id": "title_and_abstract.search",
              "value": "attitudes",
              "operator": "contains"
            },
            {
              "column_id": "title_and_abstract.search",
              "value": "beliefs",
              "operator": "contains"
            },
            {
              "column_id": "title_and_abstract.search",
              "value": "diary",
              "operator": "contains"
            },
            {
              "column_id": "title_and_abstract.search",
              "value": "diaries",
              "operator": "contains"
            }
          ]
        },
        {
          "join": "or",
          "filters": [
            {
              "column_id": "display_name.search.exact",
              "value": "\"young people\"",
              "operator": "contains"
            },
            {
              "column_id": "display_name.search",
              "value": "adolescent",
              "operator": "contains"
            },
            {
              "column_id": "display_name.search",
              "value": "youth",
              "operator": "contains"
            },
            {
              "column_id": "display_name.search",
              "value": "pubertal",
              "operator": "contains"
            },
            {
              "column_id": "display_name.search",
              "value": "pubescent",
              "operator": "contains"
            },
            {
              "column_id": "display_name.search.exact",
              "value": "\"pre adolescent\"",
              "operator": "contains"
            },
            {
              "column_id": "display_name.search.exact",
              "value": "\"Pre pubescent\"",
              "operator": "contains"
            },
            {
              "column_id": "display_name.search.exact",
              "value": "\"pre pubertal\"",
              "operator": "contains"
            },
            {
              "column_id": "display_name.search",
              "value": "teen",
              "operator": "contains"
            },
            {
              "column_id": "display_name.search",
              "value": "preteen",
              "operator": "contains"
            },
            {
              "column_id": "display_name.search",
              "value": "tweens",
              "operator": "contains"
            },
            {
              "column_id": "display_name.search",
              "value": "tweenage",
              "operator": "contains"
            },
            {
              "column_id": "display_name.search",
              "value": "youths",
              "operator": "contains"
            },
            {
              "column_id": "display_name.search",
              "value": "schoolboy",
              "operator": "contains"
            },
            {
              "column_id": "display_name.search",
              "value": "schoolgirl",
              "operator": "contains"
            },
            {
              "column_id": "display_name.search.exact",
              "value": "\"school aged\"",
              "operator": "contains"
            },
            {
              "column_id": "display_name.search.exact",
              "value": "\"young person\"",
              "operator": "contains"
            },
            {
              "column_id": "display_name.search",
              "value": "juvenile",
              "operator": "contains"
            },
            {
              "column_id": "display_name.search",
              "value": "Boy",
              "operator": "contains"
            },
            {
              "column_id": "display_name.search",
              "value": "boys",
              "operator": "contains"
            },
            {
              "column_id": "display_name.search",
              "value": "children",
              "operator": "contains"
            },
            {
              "column_id": "display_name.search",
              "value": "child's",
              "operator": "contains"
            },
            {
              "column_id": "display_name.search",
              "value": "Girl",
              "operator": "contains"
            },
            {
              "column_id": "display_name.search",
              "value": "girls",
              "operator": "contains"
            },
            {
              "column_id": "display_name.search",
              "value": "Minors",
              "operator": "contains"
            },
            {
              "column_id": "display_name.search",
              "value": "preadolescent",
              "operator": "contains"
            },
            {
              "column_id": "display_name.search",
              "value": "Prepubescent",
              "operator": "contains"
            },
            {
              "column_id": "display_name.search",
              "value": "schoolchild",
              "operator": "contains"
            },
            {
              "column_id": "display_name.search.exact",
              "value": "\"early adolescent\"",
              "operator": "contains"
            }
          ]
        },
        {
          "join": "or",
          "filters": [
            {
              "column_id": "default.search",
              "value": "GB",
              "operator": "contains"
            },
            {
              "column_id": "default.search",
              "value": "Britain",
              "operator": "contains"
            },
            {
              "column_id": "default.search",
              "value": "UK",
              "operator": "contains"
            },
            {
              "column_id": "default.search.exact",
              "value": "\"United Kingdom\"",
              "operator": "contains"
            },
            {
              "column_id": "default.search",
              "value": "England",
              "operator": "contains"
            },
            {
              "column_id": "default.search.exact",
              "value": "\"Northern Ireland\"",
              "operator": "contains"
            },
            {
              "column_id": "default.search.exact",
              "value": "\"Northern Irish\"",
              "operator": "contains"
            },
            {
              "column_id": "default.search.exact",
              "value": "\"North Ireland\"",
              "operator": "contains"
            },
            {
              "column_id": "default.search.exact",
              "value": "\"North Irish\"",
              "operator": "contains"
            },
            {
              "column_id": "default.search",
              "value": "Scotland",
              "operator": "contains"
            },
            {
              "column_id": "default.search",
              "value": "Scottish",
              "operator": "contains"
            },
            {
              "column_id": "default.search",
              "value": "Wales",
              "operator": "contains"
            },
            {
              "column_id": "default.search",
              "value": "Welsh",
              "operator": "contains"
            },
            {
              "column_id": "default.search.exact",
              "value": "\"english boys\"",
              "operator": "contains"
            },
            {
              "column_id": "default.search.exact",
              "value": "\"English girls\"",
              "operator": "contains"
            },
            {
              "column_id": "default.search.exact",
              "value": "\"english school\"",
              "operator": "contains"
            },
            {
              "column_id": "default.search.exact",
              "value": "\"English children\"",
              "operator": "contains"
            },
            {
              "column_id": "default.search.exact",
              "value": "\"English teen\"",
              "operator": "contains"
            },
            {
              "column_id": "default.search.exact",
              "value": "\"English adolescent\"",
              "operator": "contains"
            },
            {
              "column_id": "default.search.exact",
              "value": "\"English young people\"",
              "operator": "contains"
            },
            {
              "column_id": "default.search.exact",
              "value": "\"English schoolchild\"",
              "operator": "contains"
            }
          ]
        }
      ]
    }
  }
];
