// AUTO-GENERATED by scripts/gen_oql_corpus.py -- do not edit by hand.
// Source of truth: openalex-elastic-api/docs/oql/corpus.yaml (oxjob #330).
// A pure yaml->js copy (oxjob #384): the canonical `oql`, materialized
// `oqo`, rendered `oxurl`, and authored `oxurl_status` are all precomputed
// in the corpus by its regen script, so this mirror needs no live parser.
// `oxurl_status` (ok rows): has-oxurl | oql-only | translator-bug |
// server-unsupported. `oxurl` is null for oql-only rows. See #345 / #384.
// corpus version: 2; rows: 86.

export const oqlCorpus = [
  {
    "id": 1,
    "category": "entity references",
    "provenance": {
      "type": "spec design",
      "label": "OQL v2 spec spine",
      "url": null
    },
    "oxurl_status": "has-oxurl",
    "status": "ok",
    "oql": "works where institution is I136199984 [Harvard]",
    "note": "ID authoritative; [Harvard] is an ignored annotation, regenerated on output.",
    "diagnostic": "",
    "oqo": {
      "get_rows": "works",
      "filter_rows": [
        {
          "column_id": "authorships.institutions.lineage",
          "value": "I136199984"
        }
      ]
    },
    "oxurl": "https://openalex.org/works?filter=authorships.institutions.lineage:I136199984"
  },
  {
    "id": 2,
    "category": "entity references",
    "provenance": {
      "type": "spec design",
      "label": "OQL v2 spec spine",
      "url": null
    },
    "oxurl_status": "has-oxurl",
    "status": "ok",
    "oql": "works where institution is I136199984 [Harvard]",
    "note": "The annotation is free text and is not validated — it cannot lie because nothing reads it.",
    "diagnostic": "",
    "oqo": {
      "get_rows": "works",
      "filter_rows": [
        {
          "column_id": "authorships.institutions.lineage",
          "value": "I136199984"
        }
      ]
    },
    "oxurl": "https://openalex.org/works?filter=authorships.institutions.lineage:I136199984"
  },
  {
    "id": 3,
    "category": "entity references",
    "provenance": {
      "type": "spec design",
      "label": "OQL v2 spec spine",
      "url": null
    },
    "oxurl_status": "has-oxurl",
    "status": "ok",
    "oql": "works where institution is any of (I33213144 [Harvard], I97018004 [Stanford])",
    "note": "( ... ) is a value list here; per-item annotations allowed.",
    "diagnostic": "",
    "oqo": {
      "get_rows": "works",
      "filter_rows": [
        {
          "join": "or",
          "filters": [
            {
              "column_id": "authorships.institutions.lineage",
              "value": "I33213144"
            },
            {
              "column_id": "authorships.institutions.lineage",
              "value": "I97018004"
            }
          ]
        }
      ]
    },
    "oxurl": "https://openalex.org/works?filter=authorships.institutions.lineage:I33213144|I97018004"
  },
  {
    "id": 4,
    "category": "entity references",
    "provenance": {
      "type": "spec design",
      "label": "OQL v2 spec spine",
      "url": null
    },
    "oxurl_status": "has-oxurl",
    "status": "ok",
    "oql": "works\nwhere institution is not I33213144 [Harvard]\n  and institution is not I97018004 [Stanford]",
    "note": "Negated set = NOT(a OR b) = (NOT a) AND (NOT b) by De Morgan; canonical NNF carries negation on the leaves.",
    "diagnostic": "",
    "oqo": {
      "get_rows": "works",
      "filter_rows": [
        {
          "column_id": "authorships.institutions.lineage",
          "value": "I33213144",
          "is_negated": true
        },
        {
          "column_id": "authorships.institutions.lineage",
          "value": "I97018004",
          "is_negated": true
        }
      ]
    },
    "oxurl": "https://openalex.org/works?filter=authorships.institutions.lineage:!I33213144,authorships.institutions.lineage:!I97018004"
  },
  {
    "id": 5,
    "category": "entity references",
    "provenance": {
      "type": "spec design",
      "label": "OQL v2 spec spine",
      "url": null
    },
    "oxurl_status": "has-oxurl",
    "status": "ok",
    "oql": "works where type is any of (article, review)",
    "note": "`is in` is accepted on input; canonical output spells it `is any of`.",
    "diagnostic": "",
    "oqo": {
      "get_rows": "works",
      "filter_rows": [
        {
          "join": "or",
          "filters": [
            {
              "column_id": "type",
              "value": "article"
            },
            {
              "column_id": "type",
              "value": "review"
            }
          ]
        }
      ]
    },
    "oxurl": "https://openalex.org/works?filter=type:article|review"
  },
  {
    "id": 6,
    "category": "entity references",
    "provenance": {
      "type": "spec design",
      "label": "OQL v2 spec spine",
      "url": null
    },
    "oxurl_status": null,
    "status": "error",
    "oql": "works where institution is [Harvard]",
    "note": "A display-name annotation with no ID — the v1.1 silent-mismatch footgun, now a loud error.",
    "diagnostic": "OQL_MISSING_ENTITY_ID",
    "oqo": null,
    "oxurl": null
  },
  {
    "id": 7,
    "category": "boolean logic",
    "provenance": {
      "type": "spec design",
      "label": "OQL v2 spec spine",
      "url": null
    },
    "oxurl_status": "has-oxurl",
    "status": "ok",
    "oql": "works where title contains apple and title contains any of (banana, cherry)",
    "note": "Mixed and/or with explicit parens is unambiguous.",
    "diagnostic": "",
    "oqo": {
      "get_rows": "works",
      "filter_rows": [
        {
          "column_id": "display_name.search",
          "value": "apple",
          "operator": "contains"
        },
        {
          "join": "or",
          "filters": [
            {
              "column_id": "display_name.search",
              "value": "banana",
              "operator": "contains"
            },
            {
              "column_id": "display_name.search",
              "value": "cherry",
              "operator": "contains"
            }
          ]
        }
      ]
    },
    "oxurl": "https://openalex.org/works?filter=display_name.search:apple,display_name.search:banana|cherry"
  },
  {
    "id": 8,
    "category": "boolean logic",
    "provenance": {
      "type": "spec design",
      "label": "OQL v2 spec spine",
      "url": null
    },
    "oxurl_status": null,
    "status": "error",
    "oql": "works where title contains apple and banana or cherry",
    "note": "Explicit mixed and/or at one level with no parens — the one deliberate departure from WoS/Scopus.",
    "diagnostic": "OQL_MIXED_BOOL_NEEDS_PARENS",
    "oqo": null,
    "oxurl": null
  },
  {
    "id": 9,
    "category": "boolean logic",
    "provenance": {
      "type": "spec design",
      "label": "OQL v2 spec spine",
      "url": null
    },
    "oxurl_status": "has-oxurl",
    "status": "ok",
    "oql": "works\nwhere title contains apple and title contains banana and title contains cherry",
    "note": "Pure-and is associative, no parens needed.",
    "diagnostic": "",
    "oqo": {
      "get_rows": "works",
      "filter_rows": [
        {
          "column_id": "display_name.search",
          "value": "apple",
          "operator": "contains"
        },
        {
          "column_id": "display_name.search",
          "value": "banana",
          "operator": "contains"
        },
        {
          "column_id": "display_name.search",
          "value": "cherry",
          "operator": "contains"
        }
      ]
    },
    "oxurl": "https://openalex.org/works?filter=display_name.search:apple,display_name.search:banana,display_name.search:cherry"
  },
  {
    "id": 10,
    "category": "boolean logic",
    "provenance": {
      "type": "spec design",
      "label": "OQL v2 spec spine",
      "url": null
    },
    "oxurl_status": "has-oxurl",
    "status": "ok",
    "oql": "works\nwhere title contains apple and title contains banana and title contains cherry",
    "note": "SPACE = implicit AND (Google/PubMed convention) — `apple banana cherry` == `apple and banana and cherry`.",
    "diagnostic": "",
    "oqo": {
      "get_rows": "works",
      "filter_rows": [
        {
          "column_id": "display_name.search",
          "value": "apple",
          "operator": "contains"
        },
        {
          "column_id": "display_name.search",
          "value": "banana",
          "operator": "contains"
        },
        {
          "column_id": "display_name.search",
          "value": "cherry",
          "operator": "contains"
        }
      ]
    },
    "oxurl": "https://openalex.org/works?filter=display_name.search:apple,display_name.search:banana,display_name.search:cherry"
  },
  {
    "id": 11,
    "category": "search semantics",
    "provenance": {
      "type": "spec design",
      "label": "OQL v2 spec spine",
      "url": null
    },
    "oxurl_status": "has-oxurl",
    "status": "ok",
    "oql": "works where title contains change and title contains climate",
    "note": "SPACE = stemmed AND; the words may be apart (recall). The everyday default.",
    "diagnostic": "",
    "oqo": {
      "get_rows": "works",
      "filter_rows": [
        {
          "column_id": "display_name.search",
          "value": "climate",
          "operator": "contains"
        },
        {
          "column_id": "display_name.search",
          "value": "change",
          "operator": "contains"
        }
      ]
    },
    "oxurl": "https://openalex.org/works?filter=display_name.search:change,display_name.search:climate"
  },
  {
    "id": 12,
    "category": "search semantics",
    "provenance": {
      "type": "spec design",
      "label": "OQL v2 spec spine",
      "url": null
    },
    "oxurl_status": "has-oxurl",
    "status": "ok",
    "oql": "works where title contains \"climate change\"",
    "note": "QUOTES = exact adjacent phrase, stemming OFF (.search.exact). The precision lever.",
    "diagnostic": "",
    "oqo": {
      "get_rows": "works",
      "filter_rows": [
        {
          "column_id": "display_name.search.exact",
          "value": "\"climate change\"",
          "operator": "contains"
        }
      ]
    },
    "oxurl": "https://openalex.org/works?filter=display_name.search.exact:%22climate%20change%22"
  },
  {
    "id": 13,
    "category": "search semantics",
    "provenance": {
      "type": "spec design",
      "label": "OQL v2 spec spine",
      "url": null
    },
    "oxurl_status": "has-oxurl",
    "status": "ok",
    "oql": "works where title contains near \"whopper junior\"",
    "note": "NEAR = stemmed adjacent phrase (.search) → matches \"whoppers junior\". The bridge that keeps recall on a phrase.",
    "diagnostic": "",
    "oqo": {
      "get_rows": "works",
      "filter_rows": [
        {
          "column_id": "display_name.search",
          "value": "\"whopper junior\"",
          "operator": "contains"
        }
      ]
    },
    "oxurl": "https://openalex.org/works?filter=display_name.search:%22whopper%20junior%22"
  },
  {
    "id": 14,
    "category": "search semantics",
    "provenance": {
      "type": "spec design",
      "label": "OQL v2 spec spine",
      "url": null
    },
    "oxurl_status": "has-oxurl",
    "status": "ok",
    "oql": "works where title contains \"cat\"",
    "note": "Quoting a SINGLE word = exact (no plurals). Same rule as a phrase — quotes always mean exact.",
    "diagnostic": "",
    "oqo": {
      "get_rows": "works",
      "filter_rows": [
        {
          "column_id": "display_name.search.exact",
          "value": "cat",
          "operator": "contains"
        }
      ]
    },
    "oxurl": "https://openalex.org/works?filter=display_name.search.exact:cat"
  },
  {
    "id": 15,
    "category": "search semantics",
    "provenance": {
      "type": "spec design",
      "label": "OQL v2 spec spine",
      "url": null
    },
    "oxurl_status": "has-oxurl",
    "status": "ok",
    "oql": "works where title contains cat",
    "note": "Bare word = stemmed (matches cats). Contrast with row 14 \"cat\" (exact).",
    "diagnostic": "",
    "oqo": {
      "get_rows": "works",
      "filter_rows": [
        {
          "column_id": "display_name.search",
          "value": "cat",
          "operator": "contains"
        }
      ]
    },
    "oxurl": "https://openalex.org/works?filter=display_name.search:cat"
  },
  {
    "id": 16,
    "category": "search semantics",
    "provenance": {
      "type": "spec design",
      "label": "OQL v2 spec spine",
      "url": null
    },
    "oxurl_status": "has-oxurl",
    "status": "ok",
    "oql": "works where title contains \"rock or roll\"",
    "note": "Inside quotes = literal: the `or` is a word, not a connective. One exact phrase.",
    "diagnostic": "",
    "oqo": {
      "get_rows": "works",
      "filter_rows": [
        {
          "column_id": "display_name.search.exact",
          "value": "\"rock or roll\"",
          "operator": "contains"
        }
      ]
    },
    "oxurl": "https://openalex.org/works?filter=display_name.search.exact:%22rock%20or%20roll%22"
  },
  {
    "id": 17,
    "category": "search semantics",
    "provenance": {
      "type": "spec design",
      "label": "OQL v2 spec spine",
      "url": null
    },
    "oxurl_status": null,
    "status": "error",
    "oql": "works where title contains climate change or warming",
    "note": "A space is an AND, so this mixes and/or at one level → loud error (no silent order-of-operations). Fix-it offers `climate (change or warming)` or `(climate change) or warming`.",
    "diagnostic": "OQL_MIXED_BOOL_NEEDS_PARENS",
    "oqo": null,
    "oxurl": null
  },
  {
    "id": 18,
    "category": "search semantics",
    "provenance": {
      "type": "spec design",
      "label": "OQL v2 spec spine",
      "url": null
    },
    "oxurl_status": "has-oxurl",
    "status": "ok",
    "oql": "works where title contains climate and title contains any of (change, warming)",
    "note": "The likely-intended disambiguation: climate AND (change OR warming). Implicit AND between `climate` and the group; the only `or` is nested.",
    "diagnostic": "",
    "oqo": {
      "get_rows": "works",
      "filter_rows": [
        {
          "column_id": "display_name.search",
          "value": "climate",
          "operator": "contains"
        },
        {
          "join": "or",
          "filters": [
            {
              "column_id": "display_name.search",
              "value": "change",
              "operator": "contains"
            },
            {
              "column_id": "display_name.search",
              "value": "warming",
              "operator": "contains"
            }
          ]
        }
      ]
    },
    "oxurl": "https://openalex.org/works?filter=display_name.search:climate,display_name.search:change|warming"
  },
  {
    "id": 19,
    "category": "search semantics",
    "provenance": {
      "type": "spec design",
      "label": "OQL v2 spec spine",
      "url": null
    },
    "oxurl_status": "has-oxurl",
    "status": "ok",
    "oql": "works where title contains \"bar*\"",
    "note": "Quoted wildcard = the sanctioned path (oxjob #364): runs on the no-stem `.search.exact` column. Reverses #337's old `OQL_WILDCARD_IN_QUOTES` — quotes are now where wildcards belong (stemming would drop the literal prefix).",
    "diagnostic": "",
    "oqo": {
      "get_rows": "works",
      "filter_rows": [
        {
          "column_id": "display_name.search.exact",
          "value": "bar*",
          "operator": "contains"
        }
      ]
    },
    "oxurl": "https://openalex.org/works?filter=display_name.search.exact:bar*"
  },
  {
    "id": 20,
    "category": "search semantics",
    "provenance": {
      "type": "spec design",
      "label": "OQL v2 spec spine",
      "url": null
    },
    "oxurl_status": null,
    "status": "error",
    "oql": "works where title contains bar*",
    "note": "Bare prefix wildcard is stemmed → silently wrong (oxjob #364): stemming removes the literal prefix at index time. Fix-it: quote it → \"bar*\" (runs on the no-stem column).",
    "diagnostic": "OQL_WILDCARD_NEEDS_EXACT",
    "oqo": null,
    "oxurl": null
  },
  {
    "id": 21,
    "category": "proximity & wildcards",
    "provenance": {
      "type": "spec design",
      "label": "OQL v2 spec spine",
      "url": null
    },
    "oxurl_status": "has-oxurl",
    "status": "ok",
    "oql": "works where title contains \"smart phone\" within 3 words",
    "note": "Exact proximity (quoted) → up to N positional moves apart, any order.",
    "diagnostic": "",
    "oqo": {
      "get_rows": "works",
      "filter_rows": [
        {
          "column_id": "display_name.search.exact",
          "value": "\"smart phone\"~3",
          "operator": "contains"
        }
      ]
    },
    "oxurl": "https://openalex.org/works?filter=display_name.search.exact:%22smart%20phone%22~3"
  },
  {
    "id": 22,
    "category": "proximity & wildcards",
    "provenance": {
      "type": "spec design",
      "label": "OQL v2 spec spine",
      "url": null
    },
    "oxurl_status": "has-oxurl",
    "status": "ok",
    "oql": "works where title contains \"foo*bar\"",
    "note": "Mid-word `*` (>=3-char prefix, within one token), quoted so it runs on the no-stem `.search.exact` column (oxjob",
    "diagnostic": "",
    "oqo": {
      "get_rows": "works",
      "filter_rows": [
        {
          "column_id": "display_name.search.exact",
          "value": "foo*bar",
          "operator": "contains"
        }
      ]
    },
    "oxurl": "https://openalex.org/works?filter=display_name.search.exact:foo*bar"
  },
  {
    "id": 23,
    "category": "proximity & wildcards",
    "provenance": {
      "type": "spec design",
      "label": "OQL v2 spec spine",
      "url": null
    },
    "oxurl_status": "has-oxurl",
    "status": "ok",
    "oql": "works where title contains \"wom?n\"",
    "note": "Mid-word `?` = exactly one character, quoted so it runs on the no-stem `.search.exact` column (oxjob",
    "diagnostic": "",
    "oqo": {
      "get_rows": "works",
      "filter_rows": [
        {
          "column_id": "display_name.search.exact",
          "value": "wom?n",
          "operator": "contains"
        }
      ]
    },
    "oxurl": "https://openalex.org/works?filter=display_name.search.exact:wom%3Fn"
  },
  {
    "id": 24,
    "category": "proximity & wildcards",
    "provenance": {
      "type": "spec design",
      "label": "OQL v2 spec spine",
      "url": null
    },
    "oxurl_status": null,
    "status": "error",
    "oql": "works where title contains *cycle",
    "note": "Leading `*` unsupported (perf; allow_leading_wildcard=False).",
    "diagnostic": "OQL_LEADING_WILDCARD",
    "oqo": null,
    "oxurl": null
  },
  {
    "id": 25,
    "category": "proximity & wildcards",
    "provenance": {
      "type": "spec design",
      "label": "OQL v2 spec spine",
      "url": null
    },
    "oxurl_status": null,
    "status": "error",
    "oql": "works where title contains ?cycle",
    "note": "Leading `?` unsupported.",
    "diagnostic": "OQL_LEADING_WILDCARD",
    "oqo": null,
    "oxurl": null
  },
  {
    "id": 26,
    "category": "proximity & wildcards",
    "provenance": {
      "type": "spec design",
      "label": "OQL v2 spec spine",
      "url": null
    },
    "oxurl_status": null,
    "status": "error",
    "oql": "works where title contains ab*",
    "note": "Sub-3-char prefix -> error, not a silent literal.",
    "diagnostic": "OQL_SHORT_WILDCARD_PREFIX",
    "oqo": null,
    "oxurl": null
  },
  {
    "id": 27,
    "category": "proximity & wildcards",
    "provenance": {
      "type": "spec design",
      "label": "OQL v2 spec spine",
      "url": null
    },
    "oxurl_status": "has-oxurl",
    "status": "ok",
    "oql": "works where title contains \"smart phone*\" within 3 words",
    "note": "Wildcard inside a quoted proximity phrase — SUPPORTED via an ES `intervals` query (trailing-prefix -> prefix rule, mid-word ? -> wildcard rule); ordered=false + max_gaps=N maps 1:1 to slop N (oxjob #355, pinned live on works-v33). query_string used to silently drop the wildcard. Leading / sub-3-char-prefix wildcards inside the phrase still rejected (#337).",
    "diagnostic": "",
    "oqo": {
      "get_rows": "works",
      "filter_rows": [
        {
          "column_id": "display_name.search.exact",
          "value": "\"smart phone*\"~3",
          "operator": "contains"
        }
      ]
    },
    "oxurl": "https://openalex.org/works?filter=display_name.search.exact:%22smart%20phone*%22~3"
  },
  {
    "id": 28,
    "category": "proximity & wildcards",
    "provenance": {
      "type": "spec design",
      "label": "OQL v2 spec spine",
      "url": null
    },
    "oxurl_status": "has-oxurl",
    "status": "ok",
    "oql": "works where title contains \"smart\" within 3 words of \"phone\"",
    "note": "Binary proximity: two SEPARATE quoted operands NEAR each other (WoS `NEAR/N`). SUPPORTED via an ES `intervals` query — each operand is its own (possibly multi-word, adjacent) sub-interval and the two are combined ordered=false + max_gaps=N (oxjob #355 Goal B; live works-v33 = 5,183 hits). `match_phrase`+slop genuinely cannot express it (slop is whole-phrase). Value encoding `\"A\"~N~\"B\"` extends the single-phrase `\"phrase\"~N` form. Exact-only (both operands quoted/no-stem).",
    "diagnostic": "",
    "oqo": {
      "get_rows": "works",
      "filter_rows": [
        {
          "column_id": "display_name.search.exact",
          "value": "\"smart\"~3~\"phone\"",
          "operator": "contains"
        }
      ]
    },
    "oxurl": "https://openalex.org/works?filter=display_name.search.exact:%22smart%22~3~%22phone%22"
  },
  {
    "id": 29,
    "category": "proximity & wildcards",
    "provenance": {
      "type": "spec design",
      "label": "OQL v2 spec spine",
      "url": null
    },
    "oxurl_status": null,
    "status": "error",
    "oql": "works where title contains smart* within 3 words",
    "note": "Wildcard + proximity can't compose.",
    "diagnostic": "OQL_WILDCARD_IN_PROXIMITY",
    "oqo": null,
    "oxurl": null
  },
  {
    "id": 79,
    "category": "proximity & wildcards",
    "provenance": {
      "type": "spec design",
      "label": "OQL v2 spec spine",
      "url": null
    },
    "oxurl_status": "has-oxurl",
    "status": "ok",
    "oql": "works where title contains \"smart* phone\"",
    "note": "Multi-token quoted wildcard phrase WITHOUT proximity = adjacency. SUPPORTED via an ES `intervals` query (ordered=true, max_gaps=0; trailing-prefix -> prefix rule, mid-word ? -> wildcard rule) — query_string would silently drop the wildcard. The no-`within` sibling of rows 27/58 (oxjob #355 Goal A; live works-v33 = 4,986 hits vs plain \"smart phone\" = 4,975). A SINGLE quoted wildcard token (\"studies*\") is #364's unquoted no-stem path, not this. Leading / sub-3-char-prefix wildcards inside the phrase still rejected (#337).",
    "diagnostic": "",
    "oqo": {
      "get_rows": "works",
      "filter_rows": [
        {
          "column_id": "display_name.search.exact",
          "value": "\"smart* phone\"",
          "operator": "contains"
        }
      ]
    },
    "oxurl": "https://openalex.org/works?filter=display_name.search.exact:%22smart*%20phone%22"
  },
  {
    "id": 80,
    "category": "proximity & wildcards",
    "provenance": {
      "type": "spec design",
      "label": "OQL v2 spec spine",
      "url": null
    },
    "oxurl_status": "has-oxurl",
    "status": "ok",
    "oql": "works where title contains \"machine learning\" within 5 words of \"neural network\"",
    "note": "Binary proximity with MULTI-WORD phrase operands on both sides — each phrase stays intact (its own ordered, gap-0 adjacency sub-interval) and the two are combined ordered=false + max_gaps=5. This is the shape only WoS (NEAR/N) and an ES `intervals`/`span` engine can express; `match_phrase`+slop cannot keep two phrases as units (oxjob #355 Goal B; live works-v33 = 1,531 hits).",
    "diagnostic": "",
    "oqo": {
      "get_rows": "works",
      "filter_rows": [
        {
          "column_id": "display_name.search.exact",
          "value": "\"machine learning\"~5~\"neural network\"",
          "operator": "contains"
        }
      ]
    },
    "oxurl": "https://openalex.org/works?filter=display_name.search.exact:%22machine%20learning%22~5~%22neural%20network%22"
  },
  {
    "id": 81,
    "category": "proximity & wildcards",
    "provenance": {
      "type": "spec design",
      "label": "OQL v2 spec spine",
      "url": null
    },
    "oxurl_status": null,
    "status": "error",
    "oql": "works where title contains \"pro*\" within 3 words of \"pre*\"",
    "note": "oxjob #355 perf guard: two wildcards in one intervals query (here a binary proximity) each need a >=4-char prefix — short 3-char prefixes multiply postings expansion (live: \"pro* pro*\" ~265ms vs ~45ms at 4 chars). \"prot*\" within 3 words of \"pret*\" is accepted. A lone wildcard keeps #337's >=3-char floor.",
    "diagnostic": "OQL_MULTI_WILDCARD_SHORT_PREFIX",
    "oqo": null,
    "oxurl": null
  },
  {
    "id": 82,
    "category": "proximity & wildcards",
    "provenance": {
      "type": "spec design",
      "label": "OQL v2 spec spine",
      "url": null
    },
    "oxurl_status": null,
    "status": "error",
    "oql": "works where title contains \"big* cat* dog*\"",
    "note": "oxjob #355 perf guard: at most 2 wildcards are allowed in one phrase / proximity / binary-proximity (one ES `intervals` query); 3+ multiplies prefix-expansion cost unacceptably. Remove a wildcard or split into separate searches.",
    "diagnostic": "OQL_TOO_MANY_WILDCARDS",
    "oqo": null,
    "oxurl": null
  },
  {
    "id": 30,
    "category": "proximity & wildcards",
    "provenance": {
      "type": "spec design",
      "label": "OQL v2 spec spine",
      "url": null
    },
    "oxurl_status": "has-oxurl",
    "status": "ok",
    "oql": "works\nwhere abstract is similar to \"graph neural networks for molecular property prediction\"",
    "note": "Semantic (search.semantic, 2-phase vector search).",
    "diagnostic": "",
    "oqo": {
      "get_rows": "works",
      "filter_rows": [
        {
          "column_id": "abstract.search.semantic",
          "value": "graph neural networks for molecular property prediction",
          "operator": "contains"
        }
      ]
    },
    "oxurl": "https://openalex.org/works?search.semantic=graph%20neural%20networks%20for%20molecular%20property%20prediction"
  },
  {
    "id": 31,
    "category": "proximity & wildcards",
    "provenance": {
      "type": "spec design",
      "label": "OQL v2 spec spine",
      "url": null
    },
    "oxurl_status": "has-oxurl",
    "status": "ok",
    "oql": "works where title & abstract contains \"machine learning\"",
    "note": "Exact phrase, no stemming (.search.exact).",
    "diagnostic": "",
    "oqo": {
      "get_rows": "works",
      "filter_rows": [
        {
          "column_id": "title_and_abstract.search.exact",
          "value": "\"machine learning\"",
          "operator": "contains"
        }
      ]
    },
    "oxurl": "https://openalex.org/works?filter=title_and_abstract.search.exact:%22machine%20learning%22"
  },
  {
    "id": 32,
    "category": "proximity & wildcards",
    "provenance": {
      "type": "spec design",
      "label": "OQL v2 spec spine",
      "url": null
    },
    "oxurl_status": "has-oxurl",
    "status": "ok",
    "oql": "works where title contains near \"smart phone\" within 3 words",
    "note": "STEMMED proximity (near + within) → .search column; contrast row 21 (exact proximity).",
    "diagnostic": "",
    "oqo": {
      "get_rows": "works",
      "filter_rows": [
        {
          "column_id": "display_name.search",
          "value": "\"smart phone\"~3",
          "operator": "contains"
        }
      ]
    },
    "oxurl": "https://openalex.org/works?filter=display_name.search:%22smart%20phone%22~3"
  },
  {
    "id": 33,
    "category": "filter, sort & sample",
    "provenance": {
      "type": "analytics question",
      "label": "OpenAlex analytics question (OAQ#2)",
      "url": null
    },
    "oxurl_status": "has-oxurl",
    "status": "ok",
    "oql": "works",
    "note": "Bare entity query, no filters.",
    "diagnostic": "",
    "oqo": {
      "get_rows": "works"
    },
    "oxurl": "https://openalex.org/works"
  },
  {
    "id": 34,
    "category": "filter, sort & sample",
    "provenance": {
      "type": "analytics question",
      "label": "OpenAlex analytics question (OAQ#3)",
      "url": null
    },
    "oxurl_status": "has-oxurl",
    "status": "ok",
    "oql": "works where year is 2020",
    "note": "",
    "diagnostic": "",
    "oqo": {
      "get_rows": "works",
      "filter_rows": [
        {
          "column_id": "publication_year",
          "value": 2020
        }
      ]
    },
    "oxurl": "https://openalex.org/works?filter=publication_year:2020"
  },
  {
    "id": 35,
    "category": "filter, sort & sample",
    "provenance": {
      "type": "analytics question",
      "label": "OpenAlex analytics question (OAQ#23)",
      "url": null
    },
    "oxurl_status": "has-oxurl",
    "status": "ok",
    "oql": "works\nwhere year >= 2020\n  and institution is any of (I136199984 [Harvard], I33213144 [Harvard])",
    "note": "",
    "diagnostic": "",
    "oqo": {
      "get_rows": "works",
      "filter_rows": [
        {
          "join": "or",
          "filters": [
            {
              "column_id": "authorships.institutions.lineage",
              "value": "I33213144"
            },
            {
              "column_id": "authorships.institutions.lineage",
              "value": "I136199984"
            }
          ]
        },
        {
          "column_id": "publication_year",
          "value": 2020,
          "operator": ">="
        }
      ]
    },
    "oxurl": "https://openalex.org/works?filter=publication_year:2020-,authorships.institutions.lineage:I136199984|I33213144"
  },
  {
    "id": 36,
    "category": "filter, sort & sample",
    "provenance": {
      "type": "analytics question",
      "label": "OpenAlex analytics question (AKQ#8)",
      "url": null
    },
    "oxurl_status": "has-oxurl",
    "status": "ok",
    "oql": "works\nwhere institution is I130438778 [Memorial University of Newfoundland]\nsort by citations desc",
    "note": "",
    "diagnostic": "",
    "oqo": {
      "get_rows": "works",
      "filter_rows": [
        {
          "column_id": "authorships.institutions.lineage",
          "value": "I130438778"
        }
      ],
      "sort_by": [
        {
          "column_id": "cited_by_count",
          "direction": "desc"
        }
      ]
    },
    "oxurl": "https://openalex.org/works?filter=authorships.institutions.lineage:I130438778&sort=cited_by_count:desc"
  },
  {
    "id": 37,
    "category": "filter, sort & sample",
    "provenance": {
      "type": "analytics question",
      "label": "OpenAlex analytics question (AKQ#19)",
      "url": null
    },
    "oxurl_status": "has-oxurl",
    "status": "ok",
    "oql": "works\nwhere institution is I201448701 [UW]\n  and funder is F4320332161 [NIH]\n  and it's not open access",
    "note": "",
    "diagnostic": "",
    "oqo": {
      "get_rows": "works",
      "filter_rows": [
        {
          "column_id": "authorships.institutions.lineage",
          "value": "I201448701"
        },
        {
          "column_id": "funders.id",
          "value": "F4320332161"
        },
        {
          "column_id": "open_access.is_oa",
          "value": false
        }
      ]
    },
    "oxurl": "https://openalex.org/works?filter=authorships.institutions.lineage:I201448701,funders.id:F4320332161,open_access.is_oa:false"
  },
  {
    "id": 38,
    "category": "filter, sort & sample",
    "provenance": {
      "type": "analytics question",
      "label": "OpenAlex analytics question (AKQ#46)",
      "url": null
    },
    "oxurl_status": "has-oxurl",
    "status": "ok",
    "oql": "works\nwhere title & abstract contains change and title & abstract contains climate",
    "note": "Bare = stemmed AND — exactly what the #284 OXURL did (space = AND on .search). Use `near \"climate change\"` for an adjacent phrase.",
    "diagnostic": "",
    "oqo": {
      "get_rows": "works",
      "filter_rows": [
        {
          "column_id": "title_and_abstract.search",
          "value": "climate",
          "operator": "contains"
        },
        {
          "column_id": "title_and_abstract.search",
          "value": "change",
          "operator": "contains"
        }
      ]
    },
    "oxurl": "https://openalex.org/works?filter=title_and_abstract.search:change,title_and_abstract.search:climate"
  },
  {
    "id": 39,
    "category": "filter, sort & sample",
    "provenance": {
      "type": "analytics question",
      "label": "OpenAlex analytics question (OAQ#10)",
      "url": null
    },
    "oxurl_status": "has-oxurl",
    "status": "ok",
    "oql": "authors sort by works_count desc",
    "note": "",
    "diagnostic": "",
    "oqo": {
      "get_rows": "authors",
      "sort_by": [
        {
          "column_id": "works_count",
          "direction": "desc"
        }
      ]
    },
    "oxurl": "https://openalex.org/authors?sort=works_count:desc"
  },
  {
    "id": 40,
    "category": "filter, sort & sample",
    "provenance": {
      "type": "analytics question",
      "label": "OpenAlex analytics question (AKQ#18)",
      "url": null
    },
    "oxurl_status": "has-oxurl",
    "status": "ok",
    "oql": "authors where it has an ORCID and author country is BR",
    "note": "",
    "diagnostic": "",
    "oqo": {
      "get_rows": "authors",
      "filter_rows": [
        {
          "column_id": "last_known_institutions.country_code",
          "value": "BR"
        },
        {
          "column_id": "has_orcid",
          "value": true
        }
      ]
    },
    "oxurl": "https://openalex.org/authors?filter=has_orcid:true,last_known_institutions.country_code:BR"
  },
  {
    "id": 41,
    "category": "filter, sort & sample",
    "provenance": {
      "type": "analytics question",
      "label": "OpenAlex analytics question (OAQ#17)",
      "url": null
    },
    "oxurl_status": "has-oxurl",
    "status": "ok",
    "oql": "authors where openalex id is A5022654839",
    "note": "",
    "diagnostic": "",
    "oqo": {
      "get_rows": "authors",
      "filter_rows": [
        {
          "column_id": "ids.openalex",
          "value": "A5022654839"
        }
      ]
    },
    "oxurl": "https://openalex.org/authors?filter=ids.openalex:A5022654839"
  },
  {
    "id": 42,
    "category": "filter, sort & sample",
    "provenance": {
      "type": "analytics question",
      "label": "OpenAlex analytics question (OAQ#6)",
      "url": null
    },
    "oxurl_status": "has-oxurl",
    "status": "ok",
    "oql": "sources where type is journal",
    "note": "",
    "diagnostic": "",
    "oqo": {
      "get_rows": "sources",
      "filter_rows": [
        {
          "column_id": "type",
          "value": "journal"
        }
      ]
    },
    "oxurl": "https://openalex.org/sources?filter=type:journal"
  },
  {
    "id": 43,
    "category": "filter, sort & sample",
    "provenance": {
      "type": "analytics question",
      "label": "OpenAlex analytics question (OAQ#12)",
      "url": null
    },
    "oxurl_status": "has-oxurl",
    "status": "ok",
    "oql": "institutions where country code is FR",
    "note": "",
    "diagnostic": "",
    "oqo": {
      "get_rows": "institutions",
      "filter_rows": [
        {
          "column_id": "country_code",
          "value": "FR"
        }
      ]
    },
    "oxurl": "https://openalex.org/institutions?filter=country_code:FR"
  },
  {
    "id": 44,
    "category": "filter, sort & sample",
    "provenance": {
      "type": "analytics question",
      "label": "OpenAlex analytics question (OAQ#14)",
      "url": null
    },
    "oxurl_status": "has-oxurl",
    "status": "ok",
    "oql": "topics where domain is 3",
    "note": "",
    "diagnostic": "",
    "oqo": {
      "get_rows": "topics",
      "filter_rows": [
        {
          "column_id": "domain.id",
          "value": "3"
        }
      ]
    },
    "oxurl": "https://openalex.org/topics?filter=domain.id:3"
  },
  {
    "id": 45,
    "category": "filter, sort & sample",
    "provenance": {
      "type": "analytics question",
      "label": "OpenAlex analytics question (AKQ#37)",
      "url": null
    },
    "oxurl_status": "has-oxurl",
    "status": "ok",
    "oql": "authors\nwhere last known institution is I114027177 [UNC]\n  and topics is T10895 [climate change]",
    "note": "",
    "diagnostic": "",
    "oqo": {
      "get_rows": "authors",
      "filter_rows": [
        {
          "column_id": "last_known_institutions.id",
          "value": "I114027177"
        },
        {
          "column_id": "topics.id",
          "value": "T10895"
        }
      ]
    },
    "oxurl": "https://openalex.org/authors?filter=last_known_institutions.id:I114027177,topics.id:T10895"
  },
  {
    "id": 46,
    "category": "group by",
    "provenance": {
      "type": "analytics question",
      "label": "OpenAlex analytics question (AKQ#10)",
      "url": null
    },
    "oxurl_status": "has-oxurl",
    "status": "ok",
    "oql": "works where author is A5066175077 [Stephen Hawking] group by author",
    "note": "",
    "diagnostic": "",
    "oqo": {
      "get_rows": "works",
      "filter_rows": [
        {
          "column_id": "authorships.author.id",
          "value": "A5066175077"
        }
      ],
      "group_by": [
        {
          "column_id": "authorships.author.id"
        }
      ]
    },
    "oxurl": "https://openalex.org/works?filter=authorships.author.id:A5066175077&group_by=authorships.author.id"
  },
  {
    "id": 47,
    "category": "group by",
    "provenance": {
      "type": "analytics question",
      "label": "OpenAlex analytics question (AKQ#17)",
      "url": null
    },
    "oxurl_status": "has-oxurl",
    "status": "ok",
    "oql": "works where fulltext contains near \"Macrocystis pyrifera\" group by author",
    "note": "A species name is a phrase but recall matters → `near` (stemmed adjacent), not exact quotes.",
    "diagnostic": "",
    "oqo": {
      "get_rows": "works",
      "filter_rows": [
        {
          "column_id": "fulltext.search",
          "value": "\"Macrocystis pyrifera\"",
          "operator": "contains"
        }
      ],
      "group_by": [
        {
          "column_id": "authorships.author.id"
        }
      ]
    },
    "oxurl": "https://openalex.org/works?filter=fulltext.search:%22Macrocystis%20pyrifera%22&group_by=authorships.author.id"
  },
  {
    "id": 48,
    "category": "group by",
    "provenance": {
      "type": "analytics question",
      "label": "OpenAlex analytics question (AKQ#75)",
      "url": null
    },
    "oxurl_status": "server-unsupported",
    "status": "ok",
    "oql": "works where year >= 1976 group by topic, year",
    "note": "Multi-dim group_by is expressible in the spec (live API single-dim only ->",
    "diagnostic": "",
    "oqo": {
      "get_rows": "works",
      "filter_rows": [
        {
          "column_id": "publication_year",
          "value": 1976,
          "operator": ">="
        }
      ],
      "group_by": [
        {
          "column_id": "primary_topic.id"
        },
        {
          "column_id": "publication_year"
        }
      ]
    },
    "oxurl": "https://openalex.org/works?filter=publication_year:1976-&group_by=primary_topic.id,publication_year"
  },
  {
    "id": 49,
    "category": "group by",
    "provenance": {
      "type": "analytics question",
      "label": "OpenAlex analytics question (AKQ#20)",
      "url": null
    },
    "oxurl_status": "has-oxurl",
    "status": "ok",
    "oql": "works where country is in collection col_eu27 and country is US group by topic",
    "note": "col_eu27 is a Collection reference. Cross-type membership: the canonical OQL is `is in collection` (oxjob #363); the URL surface stays the bare `<field>:col_…` value (resolved by the cross-type pre-pass).",
    "diagnostic": "",
    "oqo": {
      "get_rows": "works",
      "filter_rows": [
        {
          "column_id": "authorships.countries",
          "value": "col_eu27",
          "operator": "in collection"
        },
        {
          "column_id": "authorships.countries",
          "value": "US"
        }
      ],
      "group_by": [
        {
          "column_id": "primary_topic.id"
        }
      ]
    },
    "oxurl": "https://openalex.org/works?filter=authorships.countries:col_eu27,authorships.countries:US&group_by=primary_topic.id"
  },
  {
    "id": 50,
    "category": "group by",
    "provenance": {
      "type": "analytics question",
      "label": "OpenAlex analytics question (AKQ#48)",
      "url": null
    },
    "oxurl_status": "has-oxurl",
    "status": "ok",
    "oql": "works where it's retracted group by institution",
    "note": "",
    "diagnostic": "",
    "oqo": {
      "get_rows": "works",
      "filter_rows": [
        {
          "column_id": "is_retracted",
          "value": true
        }
      ],
      "group_by": [
        {
          "column_id": "authorships.institutions.lineage"
        }
      ]
    },
    "oxurl": "https://openalex.org/works?filter=is_retracted:true&group_by=authorships.institutions.lineage"
  },
  {
    "id": 51,
    "category": "group by",
    "provenance": {
      "type": "analytics question",
      "label": "OpenAlex analytics question (AKQ#27)",
      "url": null
    },
    "oxurl_status": "has-oxurl",
    "status": "ok",
    "oql": "works\nwhere citations > 100 and title & abstract contains near \"coral bleaching\"\ngroup by source",
    "note": "",
    "diagnostic": "",
    "oqo": {
      "get_rows": "works",
      "filter_rows": [
        {
          "column_id": "title_and_abstract.search",
          "value": "\"coral bleaching\"",
          "operator": "contains"
        },
        {
          "column_id": "cited_by_count",
          "value": 100,
          "operator": ">"
        }
      ],
      "group_by": [
        {
          "column_id": "primary_location.source.id"
        }
      ]
    },
    "oxurl": "https://openalex.org/works?filter=cited_by_count:>100,title_and_abstract.search:%22coral%20bleaching%22&group_by=primary_location.source.id"
  },
  {
    "id": 52,
    "category": "group by",
    "provenance": {
      "type": "analytics question",
      "label": "OpenAlex analytics question (AKQ#13)",
      "url": null
    },
    "oxurl_status": "has-oxurl",
    "status": "ok",
    "oql": "works where type is book group by field",
    "note": "",
    "diagnostic": "",
    "oqo": {
      "get_rows": "works",
      "filter_rows": [
        {
          "column_id": "type",
          "value": "book"
        }
      ],
      "group_by": [
        {
          "column_id": "primary_topic.field.id"
        }
      ]
    },
    "oxurl": "https://openalex.org/works?filter=type:book&group_by=primary_topic.field.id"
  },
  {
    "id": 53,
    "category": "group by",
    "provenance": {
      "type": "analytics question",
      "label": "OpenAlex analytics question (AKQ#59)",
      "url": null
    },
    "oxurl_status": "has-oxurl",
    "status": "ok",
    "oql": "works where institution is I154570441 [UCSB] and it's retracted group by author",
    "note": "",
    "diagnostic": "",
    "oqo": {
      "get_rows": "works",
      "filter_rows": [
        {
          "column_id": "authorships.institutions.lineage",
          "value": "I154570441"
        },
        {
          "column_id": "is_retracted",
          "value": true
        }
      ],
      "group_by": [
        {
          "column_id": "authorships.author.id"
        }
      ]
    },
    "oxurl": "https://openalex.org/works?filter=authorships.institutions.lineage:I154570441,is_retracted:true&group_by=authorships.author.id"
  },
  {
    "id": 54,
    "category": "group by",
    "provenance": {
      "type": "analytics question",
      "label": "OpenAlex analytics question (AKQ#22)",
      "url": null
    },
    "oxurl_status": "has-oxurl",
    "status": "ok",
    "oql": "works where institution is I107639228 [Notre Dame] group by SDG",
    "note": "",
    "diagnostic": "",
    "oqo": {
      "get_rows": "works",
      "filter_rows": [
        {
          "column_id": "authorships.institutions.lineage",
          "value": "I107639228"
        }
      ],
      "group_by": [
        {
          "column_id": "sustainable_development_goals.id"
        }
      ]
    },
    "oxurl": "https://openalex.org/works?filter=authorships.institutions.lineage:I107639228&group_by=sustainable_development_goals.id"
  },
  {
    "id": 55,
    "category": "librarian & SR queries",
    "provenance": {
      "type": "librarian guide",
      "label": "Cranfield SLR combining-strings guide",
      "url": "https://blogs.cranfield.ac.uk/library/slr-combining-strings/"
    },
    "oxurl_status": "has-oxurl",
    "status": "ok",
    "oql": "works\nwhere title & abstract contains agile\n  and title & abstract contains any of (near \"cycle time\", near \"lead time\")\n  and title & abstract contains any of (\n    near \"demand chain\",\n    near \"supply chain\",\n    near \"value chain\",\n  )",
    "note": "AND of OR-groups; the synonym phrases use `near` (stemmed adjacent) for recall. Top level is pure-and so no parens.",
    "diagnostic": "",
    "oqo": {
      "get_rows": "works",
      "filter_rows": [
        {
          "column_id": "title_and_abstract.search",
          "value": "agile",
          "operator": "contains"
        },
        {
          "join": "or",
          "filters": [
            {
              "column_id": "title_and_abstract.search",
              "value": "\"supply chain\"",
              "operator": "contains"
            },
            {
              "column_id": "title_and_abstract.search",
              "value": "\"demand chain\"",
              "operator": "contains"
            },
            {
              "column_id": "title_and_abstract.search",
              "value": "\"value chain\"",
              "operator": "contains"
            }
          ]
        },
        {
          "join": "or",
          "filters": [
            {
              "column_id": "title_and_abstract.search",
              "value": "\"lead time\"",
              "operator": "contains"
            },
            {
              "column_id": "title_and_abstract.search",
              "value": "\"cycle time\"",
              "operator": "contains"
            }
          ]
        }
      ]
    },
    "oxurl": "https://openalex.org/works?filter=title_and_abstract.search:agile,title_and_abstract.search:%22cycle%20time%22|%22lead%20time%22,title_and_abstract.search:%22demand%20chain%22|%22supply%20chain%22|%22value%20chain%22"
  },
  {
    "id": 56,
    "category": "librarian & SR queries",
    "provenance": {
      "type": "librarian guide",
      "label": "U. Manitoba Scopus proximity guide",
      "url": "https://libguides.lib.umanitoba.ca/scopus/phrases"
    },
    "oxurl_status": "has-oxurl",
    "status": "ok",
    "oql": "works where title & abstract contains near \"smart phone\" within 3 words",
    "note": "Stemmed proximity (`near`) → .search, matching the #284 column. Use plain quotes for exact proximity.",
    "diagnostic": "",
    "oqo": {
      "get_rows": "works",
      "filter_rows": [
        {
          "column_id": "title_and_abstract.search",
          "value": "\"smart phone\"~3",
          "operator": "contains"
        }
      ]
    },
    "oxurl": "https://openalex.org/works?filter=title_and_abstract.search:%22smart%20phone%22~3"
  },
  {
    "id": 57,
    "category": "librarian & SR queries",
    "provenance": {
      "type": "librarian guide",
      "label": "U. Manitoba Scopus proximity guide",
      "url": "https://libguides.lib.umanitoba.ca/scopus/phrases"
    },
    "oxurl_status": "has-oxurl",
    "status": "ok",
    "oql": "works where title & abstract contains \"phone*\"",
    "note": "Trailing wildcard, quoted so it runs on the no-stem `title_and_abstract.search.exact` column (oxjob #364). Bare `phone*` is now an error (OQL_WILDCARD_NEEDS_EXACT) — stemming would drop the literal prefix.",
    "diagnostic": "",
    "oqo": {
      "get_rows": "works",
      "filter_rows": [
        {
          "column_id": "title_and_abstract.search.exact",
          "value": "phone*",
          "operator": "contains"
        }
      ]
    },
    "oxurl": "https://openalex.org/works?filter=title_and_abstract.search.exact:phone*"
  },
  {
    "id": 58,
    "category": "librarian & SR queries",
    "provenance": {
      "type": "librarian guide",
      "label": "U. Manitoba Scopus proximity guide",
      "url": "https://libguides.lib.umanitoba.ca/scopus/phrases"
    },
    "oxurl_status": "has-oxurl",
    "status": "ok",
    "oql": "works where title & abstract contains \"smart phone*\" within 3 words",
    "note": "Wildcard-in-proximity, now SUPPORTED (oxjob #355): compiles to an ES `intervals` query that keeps the wildcard (query_string used to drop it). WoS/Scopus parity. ordered=false + max_gaps=N == slop N (pinned live on works-v33: 48,583 hits). Leading / sub-3-char-prefix wildcards still rejected (#337).",
    "diagnostic": "",
    "oqo": {
      "get_rows": "works",
      "filter_rows": [
        {
          "column_id": "title_and_abstract.search.exact",
          "value": "\"smart phone*\"~3",
          "operator": "contains"
        }
      ]
    },
    "oxurl": "https://openalex.org/works?filter=title_and_abstract.search.exact:%22smart%20phone*%22~3"
  },
  {
    "id": 59,
    "category": "librarian & SR queries",
    "provenance": {
      "type": "librarian guide",
      "label": "UCL Scopus search-techniques guide",
      "url": "https://library-guides.ucl.ac.uk/scopus/search-techniques"
    },
    "oxurl_status": "has-oxurl",
    "status": "ok",
    "oql": "works where title & abstract contains \"oyster toadfish\"",
    "note": "NL says \"exact phrase only, no lemmatization\" → plain quotes (exact, .search.exact). The textbook quotes-mean-exact case.",
    "diagnostic": "",
    "oqo": {
      "get_rows": "works",
      "filter_rows": [
        {
          "column_id": "title_and_abstract.search.exact",
          "value": "\"oyster toadfish\"",
          "operator": "contains"
        }
      ]
    },
    "oxurl": "https://openalex.org/works?filter=title_and_abstract.search.exact:%22oyster%20toadfish%22"
  },
  {
    "id": 60,
    "category": "librarian & SR queries",
    "provenance": {
      "type": "librarian guide",
      "label": "Caltech Web of Science wildcard guide",
      "url": null
    },
    "oxurl_status": "has-oxurl",
    "status": "ok",
    "oql": "works where title & abstract contains \"behavio*r\"",
    "note": "Mid-word wildcard (UK/US spellings in one query), quoted so it runs on the no-stem `title_and_abstract.search.exact` column (oxjob",
    "diagnostic": "",
    "oqo": {
      "get_rows": "works",
      "filter_rows": [
        {
          "column_id": "title_and_abstract.search.exact",
          "value": "behavio*r",
          "operator": "contains"
        }
      ]
    },
    "oxurl": "https://openalex.org/works?filter=title_and_abstract.search.exact:behavio*r"
  },
  {
    "id": 61,
    "category": "librarian & SR queries",
    "provenance": {
      "type": "librarian guide",
      "label": "KCL/Stirling systematic-review template",
      "url": "https://libguides.kcl.ac.uk/systematicreview/advanced"
    },
    "oxurl_status": "has-oxurl",
    "status": "ok",
    "oql": "works\nwhere language is en\n  and year <= 2024\n  and year >= 2015\n  and title & abstract contains any of (\n    ASD,\n    near \"autism spectrum disorder\",\n    autism,\n  )\n  and title & abstract contains any of (intervention, therapy, treatment)\n  and type is any of (article, review)",
    "note": "",
    "diagnostic": "",
    "oqo": {
      "get_rows": "works",
      "filter_rows": [
        {
          "join": "or",
          "filters": [
            {
              "column_id": "title_and_abstract.search",
              "value": "autism",
              "operator": "contains"
            },
            {
              "column_id": "title_and_abstract.search",
              "value": "ASD",
              "operator": "contains"
            },
            {
              "column_id": "title_and_abstract.search",
              "value": "\"autism spectrum disorder\"",
              "operator": "contains"
            }
          ]
        },
        {
          "join": "or",
          "filters": [
            {
              "column_id": "title_and_abstract.search",
              "value": "intervention",
              "operator": "contains"
            },
            {
              "column_id": "title_and_abstract.search",
              "value": "therapy",
              "operator": "contains"
            },
            {
              "column_id": "title_and_abstract.search",
              "value": "treatment",
              "operator": "contains"
            }
          ]
        },
        {
          "column_id": "publication_year",
          "value": 2015,
          "operator": ">="
        },
        {
          "column_id": "publication_year",
          "value": 2024,
          "operator": "<="
        },
        {
          "join": "or",
          "filters": [
            {
              "column_id": "type",
              "value": "article"
            },
            {
              "column_id": "type",
              "value": "review"
            }
          ]
        },
        {
          "column_id": "language",
          "value": "en"
        }
      ]
    },
    "oxurl": "https://openalex.org/works?filter=language:en,publication_year:2015-2024,title_and_abstract.search:ASD|%22autism%20spectrum%20disorder%22|autism,title_and_abstract.search:intervention|therapy|treatment,type:article|review"
  },
  {
    "id": 62,
    "category": "librarian & SR queries",
    "provenance": {
      "type": "vendor docs",
      "label": "Dimensions DSL reference + cookbook",
      "url": "https://docs.dimensions.ai/dsl/"
    },
    "oxurl_status": "has-oxurl",
    "status": "ok",
    "oql": "works where funder is F4320337351 [NCI] and OA status is gold",
    "note": "",
    "diagnostic": "",
    "oqo": {
      "get_rows": "works",
      "filter_rows": [
        {
          "column_id": "open_access.oa_status",
          "value": "gold"
        },
        {
          "column_id": "funders.id",
          "value": "F4320337351"
        }
      ]
    },
    "oxurl": "https://openalex.org/works?filter=funders.id:F4320337351,open_access.oa_status:gold"
  },
  {
    "id": 63,
    "category": "librarian & SR queries",
    "provenance": {
      "type": "vendor docs",
      "label": "Dimensions DSL reference + cookbook",
      "url": "https://docs.dimensions.ai/dsl/"
    },
    "oxurl_status": "has-oxurl",
    "status": "ok",
    "oql": "works\nwhere year <= 2023\n  and year >= 2018\n  and title & abstract contains CRISPR\n  and title & abstract contains near \"genome editing\"\nsort by citations desc\nsample 500",
    "note": "Mixes a bare token (CRISPR, stemmed) with a `near` phrase (genome editing) — the explicit version of #284's loose multi-word search.",
    "diagnostic": "",
    "oqo": {
      "get_rows": "works",
      "filter_rows": [
        {
          "column_id": "title_and_abstract.search",
          "value": "CRISPR",
          "operator": "contains"
        },
        {
          "column_id": "title_and_abstract.search",
          "value": "\"genome editing\"",
          "operator": "contains"
        },
        {
          "column_id": "publication_year",
          "value": 2018,
          "operator": ">="
        },
        {
          "column_id": "publication_year",
          "value": 2023,
          "operator": "<="
        }
      ],
      "sort_by": [
        {
          "column_id": "cited_by_count",
          "direction": "desc"
        }
      ],
      "sample": 500
    },
    "oxurl": "https://openalex.org/works?filter=publication_year:2018-2023,title_and_abstract.search:CRISPR,title_and_abstract.search:%22genome%20editing%22&sort=cited_by_count:desc&sample=500"
  },
  {
    "id": 64,
    "category": "librarian & SR queries",
    "provenance": {
      "type": "librarian guide",
      "label": "Bibliometric study of librarian-authored SRs",
      "url": null
    },
    "oxurl_status": "has-oxurl",
    "status": "ok",
    "oql": "works where raw affiliation contains library",
    "note": "",
    "diagnostic": "",
    "oqo": {
      "get_rows": "works",
      "filter_rows": [
        {
          "column_id": "raw_affiliation_strings.search",
          "value": "library",
          "operator": "contains"
        }
      ]
    },
    "oxurl": "https://openalex.org/works?filter=raw_affiliation_strings.search:library"
  },
  {
    "id": 65,
    "category": "librarian & SR queries",
    "provenance": {
      "type": "vendor docs",
      "label": "Elsevier Scopus Search Tips",
      "url": "https://schema.elsevier.com/dtds/document/bkapi/search/SCOPUSSearchTips.htm"
    },
    "oxurl_status": "has-oxurl",
    "status": "ok",
    "oql": "works where raw affiliation contains near \"london hospital\" within 5 words",
    "note": "Quoted phrase scopes to ONE affiliation (position_increment_gap); slop ~5 allows order/gap within it.",
    "diagnostic": "",
    "oqo": {
      "get_rows": "works",
      "filter_rows": [
        {
          "column_id": "raw_affiliation_strings.search",
          "value": "\"london hospital\"~5",
          "operator": "contains"
        }
      ]
    },
    "oxurl": "https://openalex.org/works?filter=raw_affiliation_strings.search:%22london%20hospital%22~5"
  },
  {
    "id": 66,
    "category": "librarian & SR queries",
    "provenance": {
      "type": "vendor docs",
      "label": "Elsevier Scopus Search Tips",
      "url": "https://schema.elsevier.com/dtds/document/bkapi/search/SCOPUSSearchTips.htm"
    },
    "oxurl_status": "has-oxurl",
    "status": "ok",
    "oql": "works where DOI is 10.1021/es052595+",
    "note": "Reserved chars (+, /) are ordinary inside a bare value; no escaping in OQL.",
    "diagnostic": "",
    "oqo": {
      "get_rows": "works",
      "filter_rows": [
        {
          "column_id": "doi",
          "value": "10.1021/es052595+"
        }
      ]
    },
    "oxurl": "https://openalex.org/works?filter=doi:10.1021/es052595%2B"
  },
  {
    "id": 67,
    "category": "librarian & SR queries",
    "provenance": {
      "type": "vendor docs",
      "label": "Clarivate Web of Science field tags",
      "url": "https://webofscience.zendesk.com/hc/en-us/articles/26916347018257-Web-of-Science-Core-Collection-Advanced-Search-Field-Tags"
    },
    "oxurl_status": "has-oxurl",
    "status": "ok",
    "oql": "works where ORCID is 0000-0002-1838-9363",
    "note": "",
    "diagnostic": "",
    "oqo": {
      "get_rows": "works",
      "filter_rows": [
        {
          "column_id": "authorships.author.orcid",
          "value": "0000-0002-1838-9363"
        }
      ]
    },
    "oxurl": "https://openalex.org/works?filter=authorships.author.orcid:0000-0002-1838-9363"
  },
  {
    "id": 68,
    "category": "librarian & SR queries",
    "provenance": {
      "type": "vendor docs",
      "label": "Dimensions DSL reference + cookbook",
      "url": "https://docs.dimensions.ai/dsl/"
    },
    "oxurl_status": null,
    "status": "out-of-scope",
    "oql": null,
    "note": "\"funded by the acronym DFG\" — out of scope (not representable). OQO only expresses funders.id equality AFTER an out-of-band /funders?search=DFG -> ID resolution; the acronym has no OQL/OQO form.",
    "diagnostic": "",
    "oqo": null,
    "oxurl": null
  },
  {
    "id": 69,
    "category": "librarian & SR queries",
    "provenance": {
      "type": "vendor docs",
      "label": "Elsevier Scopus Search Tips",
      "url": "https://schema.elsevier.com/dtds/document/bkapi/search/SCOPUSSearchTips.htm"
    },
    "oxurl_status": "has-oxurl",
    "status": "ok",
    "oql": "works where type is any of (article, review)",
    "note": "",
    "diagnostic": "",
    "oqo": {
      "get_rows": "works",
      "filter_rows": [
        {
          "join": "or",
          "filters": [
            {
              "column_id": "type",
              "value": "article"
            },
            {
              "column_id": "type",
              "value": "review"
            }
          ]
        }
      ]
    },
    "oxurl": "https://openalex.org/works?filter=type:article|review"
  },
  {
    "id": 70,
    "category": "librarian & SR queries",
    "provenance": {
      "type": "vendor docs",
      "label": "Elsevier Scopus Search Tips",
      "url": "https://schema.elsevier.com/dtds/document/bkapi/search/SCOPUSSearchTips.htm"
    },
    "oxurl_status": "has-oxurl",
    "status": "ok",
    "oql": "works where language is es",
    "note": "",
    "diagnostic": "",
    "oqo": {
      "get_rows": "works",
      "filter_rows": [
        {
          "column_id": "language",
          "value": "es"
        }
      ]
    },
    "oxurl": "https://openalex.org/works?filter=language:es"
  },
  {
    "id": 71,
    "category": "librarian & SR queries",
    "provenance": {
      "type": "librarian guide",
      "label": "UCL Web of Science search-tips guide",
      "url": "https://library-guides.ucl.ac.uk/web-of-science/search-tips"
    },
    "oxurl_status": "has-oxurl",
    "status": "ok",
    "oql": "works\nwhere title & abstract does not contain pediatric\n  and title & abstract contains covid",
    "note": "One negation mechanism: `does not contain` renders is_negated:true on a contains leaf.",
    "diagnostic": "",
    "oqo": {
      "get_rows": "works",
      "filter_rows": [
        {
          "column_id": "title_and_abstract.search",
          "value": "covid",
          "operator": "contains"
        },
        {
          "column_id": "title_and_abstract.search",
          "value": "pediatric",
          "operator": "contains",
          "is_negated": true
        }
      ]
    },
    "oxurl": "https://openalex.org/works?filter=title_and_abstract.search:!pediatric,title_and_abstract.search:covid"
  },
  {
    "id": 72,
    "category": "librarian & SR queries",
    "provenance": {
      "type": "vendor docs",
      "label": "Clarivate Web of Science field tags",
      "url": "https://webofscience.zendesk.com/hc/en-us/articles/26916347018257-Web-of-Science-Core-Collection-Advanced-Search-Field-Tags"
    },
    "oxurl_status": "has-oxurl",
    "status": "ok",
    "oql": "works\nwhere title & abstract contains computing and title & abstract contains quantum\ngroup by country",
    "note": "Bare = stemmed AND (faithful to the",
    "diagnostic": "",
    "oqo": {
      "get_rows": "works",
      "filter_rows": [
        {
          "column_id": "title_and_abstract.search",
          "value": "quantum",
          "operator": "contains"
        },
        {
          "column_id": "title_and_abstract.search",
          "value": "computing",
          "operator": "contains"
        }
      ],
      "group_by": [
        {
          "column_id": "authorships.countries"
        }
      ]
    },
    "oxurl": "https://openalex.org/works?filter=title_and_abstract.search:computing,title_and_abstract.search:quantum&group_by=authorships.countries"
  },
  {
    "id": 73,
    "category": "librarian & SR queries",
    "provenance": {
      "type": "vendor docs",
      "label": "Dimensions DSL reference + cookbook",
      "url": "https://docs.dimensions.ai/dsl/"
    },
    "oxurl_status": "has-oxurl",
    "status": "ok",
    "oql": "works\nwhere title & abstract contains CRISPR and title & abstract contains Cas9\ngroup by author",
    "note": "",
    "diagnostic": "",
    "oqo": {
      "get_rows": "works",
      "filter_rows": [
        {
          "column_id": "title_and_abstract.search",
          "value": "CRISPR",
          "operator": "contains"
        },
        {
          "column_id": "title_and_abstract.search",
          "value": "Cas9",
          "operator": "contains"
        }
      ],
      "group_by": [
        {
          "column_id": "authorships.author.id"
        }
      ]
    },
    "oxurl": "https://openalex.org/works?filter=title_and_abstract.search:CRISPR,title_and_abstract.search:Cas9&group_by=authorships.author.id"
  },
  {
    "id": 74,
    "category": "librarian & SR queries",
    "provenance": {
      "type": "vendor docs",
      "label": "Dimensions DSL reference + cookbook",
      "url": "https://docs.dimensions.ai/dsl/"
    },
    "oxurl_status": "has-oxurl",
    "status": "ok",
    "oql": "works where title & abstract contains CRISPR group by funder",
    "note": "Only the group-by-COUNT form is in scope. Ranking groups by mean citation impact is sort-by-aggregate -> #297.",
    "diagnostic": "",
    "oqo": {
      "get_rows": "works",
      "filter_rows": [
        {
          "column_id": "title_and_abstract.search",
          "value": "CRISPR",
          "operator": "contains"
        }
      ],
      "group_by": [
        {
          "column_id": "funders.id"
        }
      ]
    },
    "oxurl": "https://openalex.org/works?filter=title_and_abstract.search:CRISPR&group_by=funders.id"
  },
  {
    "id": 75,
    "category": "librarian & SR queries",
    "provenance": {
      "type": "librarian guide",
      "label": "Tufts Web of Science proximity examples",
      "url": "https://researchguides.library.tufts.edu/c.php?g=249270&p=1660077"
    },
    "oxurl_status": "has-oxurl",
    "status": "ok",
    "oql": "works where raw affiliation contains near \"tufts boston\" within 5 words",
    "note": "",
    "diagnostic": "",
    "oqo": {
      "get_rows": "works",
      "filter_rows": [
        {
          "column_id": "raw_affiliation_strings.search",
          "value": "\"tufts boston\"~5",
          "operator": "contains"
        }
      ]
    },
    "oxurl": "https://openalex.org/works?filter=raw_affiliation_strings.search:%22tufts%20boston%22~5"
  },
  {
    "id": 76,
    "category": "librarian & SR queries",
    "provenance": {
      "type": "librarian guide",
      "label": "UCL Web of Science search-tips guide",
      "url": "https://library-guides.ucl.ac.uk/web-of-science/search-tips"
    },
    "oxurl_status": null,
    "status": "out-of-scope",
    "oql": null,
    "note": "Set-reference / stateful query composition (refine a saved search) — no single OQO; out of scope.",
    "diagnostic": "",
    "oqo": null,
    "oxurl": null
  },
  {
    "id": 77,
    "category": "librarian & SR queries",
    "provenance": {
      "type": "zendesk ticket",
      "label": "OpenAlex zd#8101 + PR #240 (byline recall)",
      "url": "https://openalex.zendesk.com/agent/tickets/8101"
    },
    "oxurl_status": "has-oxurl",
    "status": "ok",
    "oql": "works where byline contains near \"john smith\" within 2 words",
    "note": "Byline slop ~2 recovers middle-name/initial forms without crossing co-authors.",
    "diagnostic": "",
    "oqo": {
      "get_rows": "works",
      "filter_rows": [
        {
          "column_id": "raw_author_name.search",
          "value": "\"john smith\"~2",
          "operator": "contains"
        }
      ]
    },
    "oxurl": "https://openalex.org/works?filter=raw_author_name.search:%22john%20smith%22~2"
  },
  {
    "id": 78,
    "category": "librarian & SR queries",
    "provenance": {
      "type": "zendesk ticket",
      "label": "OpenAlex zd#8101 — Claire's real systematic review",
      "url": "https://openalex.zendesk.com/agent/tickets/8101"
    },
    "oxurl_status": "oql-only",
    "status": "ok",
    "oql": "works\nwhere title contains any of (\n    Boy, Girl, Minors, Prepubescent, adolescent, boys, child's, children, girls,\n    juvenile, preadolescent, preteen, pubertal, pubescent, schoolboy,\n    schoolchild, schoolgirl, teen, tweenage, tweens, youth, youths,\n    \"Pre pubescent\", \"early adolescent\", \"pre adolescent\", \"pre pubertal\",\n    \"school aged\", \"young people\", \"young person\",\n  )\n  and title contains any of (\n    Height, bodyweight, fat, fatness, obese, obesity, overweight, thin,\n    thinness, weight, \"anti fat\", \"being fat\", \"being thin\", \"body esteem\",\n    \"body hatred\", \"body ideal\", \"body image\", \"body positive\", \"body shame\",\n    \"body shape\", \"body size\", \"body sizes\", \"fat ideal\", \"ideal body\",\n    \"thin ideal\", \"weight bias\",\n  )\n  and fulltext contains any of (\n    Britain, England, GB, Scotland, Scottish, UK, Wales, Welsh,\n    \"English adolescent\", \"English children\", \"English girls\",\n    \"English schoolchild\", \"English teen\", \"English young people\",\n    \"North Ireland\", \"North Irish\", \"Northern Ireland\", \"Northern Irish\",\n    \"United Kingdom\", \"english boys\", \"english school\",\n  )\n  and title & abstract contains any of (\n    attitude, attitudes, beliefs, diaries, diary, experiences, in-depth,\n    indepth, informal, open, perceptions, perspective, perspectives,\n    qualitative, semistructured, unstructured, \"focus group\", \"focus groups\",\n    \"lived experience\", \"open ended\", \"semi structured\",\n  )\n  and title & abstract contains any of (\n    attitude, attitudes, beliefs, diaries, diary, experiences, interview,\n    interviews, perceptions, perspective, perspectives, qualitative,\n    questionnaire, questionnaires, \"focus group\", \"focus groups\",\n    \"lived experience\",\n  )",
    "note": "The real zd#8101 systematic-review tree (Claire): a 5-block AND of large OR-synonym groups, each block scoped to a different search field (title / title & abstract x2 / anywhere). 114 leaves. No explicit oqo oracle — the harness asserts OQO->OQL->OQO identity through the whole tree.",
    "diagnostic": "",
    "oqo": {
      "get_rows": "works",
      "filter_rows": [
        {
          "join": "or",
          "filters": [
            {
              "column_id": "display_name.search",
              "value": "Boy",
              "operator": "contains"
            },
            {
              "column_id": "display_name.search",
              "value": "Girl",
              "operator": "contains"
            },
            {
              "column_id": "display_name.search",
              "value": "Minors",
              "operator": "contains"
            },
            {
              "column_id": "display_name.search",
              "value": "Prepubescent",
              "operator": "contains"
            },
            {
              "column_id": "display_name.search",
              "value": "adolescent",
              "operator": "contains"
            },
            {
              "column_id": "display_name.search",
              "value": "boys",
              "operator": "contains"
            },
            {
              "column_id": "display_name.search",
              "value": "child's",
              "operator": "contains"
            },
            {
              "column_id": "display_name.search",
              "value": "children",
              "operator": "contains"
            },
            {
              "column_id": "display_name.search",
              "value": "girls",
              "operator": "contains"
            },
            {
              "column_id": "display_name.search",
              "value": "juvenile",
              "operator": "contains"
            },
            {
              "column_id": "display_name.search",
              "value": "preadolescent",
              "operator": "contains"
            },
            {
              "column_id": "display_name.search",
              "value": "preteen",
              "operator": "contains"
            },
            {
              "column_id": "display_name.search",
              "value": "pubertal",
              "operator": "contains"
            },
            {
              "column_id": "display_name.search",
              "value": "pubescent",
              "operator": "contains"
            },
            {
              "column_id": "display_name.search",
              "value": "schoolboy",
              "operator": "contains"
            },
            {
              "column_id": "display_name.search",
              "value": "schoolchild",
              "operator": "contains"
            },
            {
              "column_id": "display_name.search",
              "value": "schoolgirl",
              "operator": "contains"
            },
            {
              "column_id": "display_name.search",
              "value": "teen",
              "operator": "contains"
            },
            {
              "column_id": "display_name.search",
              "value": "tweenage",
              "operator": "contains"
            },
            {
              "column_id": "display_name.search",
              "value": "tweens",
              "operator": "contains"
            },
            {
              "column_id": "display_name.search",
              "value": "youth",
              "operator": "contains"
            },
            {
              "column_id": "display_name.search",
              "value": "youths",
              "operator": "contains"
            },
            {
              "column_id": "display_name.search.exact",
              "value": "\"Pre pubescent\"",
              "operator": "contains"
            },
            {
              "column_id": "display_name.search.exact",
              "value": "\"early adolescent\"",
              "operator": "contains"
            },
            {
              "column_id": "display_name.search.exact",
              "value": "\"pre adolescent\"",
              "operator": "contains"
            },
            {
              "column_id": "display_name.search.exact",
              "value": "\"pre pubertal\"",
              "operator": "contains"
            },
            {
              "column_id": "display_name.search.exact",
              "value": "\"school aged\"",
              "operator": "contains"
            },
            {
              "column_id": "display_name.search.exact",
              "value": "\"young people\"",
              "operator": "contains"
            },
            {
              "column_id": "display_name.search.exact",
              "value": "\"young person\"",
              "operator": "contains"
            }
          ]
        },
        {
          "join": "or",
          "filters": [
            {
              "column_id": "display_name.search",
              "value": "Height",
              "operator": "contains"
            },
            {
              "column_id": "display_name.search",
              "value": "bodyweight",
              "operator": "contains"
            },
            {
              "column_id": "display_name.search",
              "value": "fat",
              "operator": "contains"
            },
            {
              "column_id": "display_name.search",
              "value": "fatness",
              "operator": "contains"
            },
            {
              "column_id": "display_name.search",
              "value": "obese",
              "operator": "contains"
            },
            {
              "column_id": "display_name.search",
              "value": "obesity",
              "operator": "contains"
            },
            {
              "column_id": "display_name.search",
              "value": "overweight",
              "operator": "contains"
            },
            {
              "column_id": "display_name.search",
              "value": "thin",
              "operator": "contains"
            },
            {
              "column_id": "display_name.search",
              "value": "thinness",
              "operator": "contains"
            },
            {
              "column_id": "display_name.search",
              "value": "weight",
              "operator": "contains"
            },
            {
              "column_id": "display_name.search.exact",
              "value": "\"anti fat\"",
              "operator": "contains"
            },
            {
              "column_id": "display_name.search.exact",
              "value": "\"being fat\"",
              "operator": "contains"
            },
            {
              "column_id": "display_name.search.exact",
              "value": "\"being thin\"",
              "operator": "contains"
            },
            {
              "column_id": "display_name.search.exact",
              "value": "\"body esteem\"",
              "operator": "contains"
            },
            {
              "column_id": "display_name.search.exact",
              "value": "\"body hatred\"",
              "operator": "contains"
            },
            {
              "column_id": "display_name.search.exact",
              "value": "\"body ideal\"",
              "operator": "contains"
            },
            {
              "column_id": "display_name.search.exact",
              "value": "\"body image\"",
              "operator": "contains"
            },
            {
              "column_id": "display_name.search.exact",
              "value": "\"body positive\"",
              "operator": "contains"
            },
            {
              "column_id": "display_name.search.exact",
              "value": "\"body shame\"",
              "operator": "contains"
            },
            {
              "column_id": "display_name.search.exact",
              "value": "\"body shape\"",
              "operator": "contains"
            },
            {
              "column_id": "display_name.search.exact",
              "value": "\"body size\"",
              "operator": "contains"
            },
            {
              "column_id": "display_name.search.exact",
              "value": "\"body sizes\"",
              "operator": "contains"
            },
            {
              "column_id": "display_name.search.exact",
              "value": "\"fat ideal\"",
              "operator": "contains"
            },
            {
              "column_id": "display_name.search.exact",
              "value": "\"ideal body\"",
              "operator": "contains"
            },
            {
              "column_id": "display_name.search.exact",
              "value": "\"thin ideal\"",
              "operator": "contains"
            },
            {
              "column_id": "display_name.search.exact",
              "value": "\"weight bias\"",
              "operator": "contains"
            }
          ]
        },
        {
          "join": "or",
          "filters": [
            {
              "column_id": "fulltext.search",
              "value": "Britain",
              "operator": "contains"
            },
            {
              "column_id": "fulltext.search",
              "value": "England",
              "operator": "contains"
            },
            {
              "column_id": "fulltext.search",
              "value": "GB",
              "operator": "contains"
            },
            {
              "column_id": "fulltext.search",
              "value": "Scotland",
              "operator": "contains"
            },
            {
              "column_id": "fulltext.search",
              "value": "Scottish",
              "operator": "contains"
            },
            {
              "column_id": "fulltext.search",
              "value": "UK",
              "operator": "contains"
            },
            {
              "column_id": "fulltext.search",
              "value": "Wales",
              "operator": "contains"
            },
            {
              "column_id": "fulltext.search",
              "value": "Welsh",
              "operator": "contains"
            },
            {
              "column_id": "fulltext.search.exact",
              "value": "\"English adolescent\"",
              "operator": "contains"
            },
            {
              "column_id": "fulltext.search.exact",
              "value": "\"English children\"",
              "operator": "contains"
            },
            {
              "column_id": "fulltext.search.exact",
              "value": "\"English girls\"",
              "operator": "contains"
            },
            {
              "column_id": "fulltext.search.exact",
              "value": "\"English schoolchild\"",
              "operator": "contains"
            },
            {
              "column_id": "fulltext.search.exact",
              "value": "\"English teen\"",
              "operator": "contains"
            },
            {
              "column_id": "fulltext.search.exact",
              "value": "\"English young people\"",
              "operator": "contains"
            },
            {
              "column_id": "fulltext.search.exact",
              "value": "\"North Ireland\"",
              "operator": "contains"
            },
            {
              "column_id": "fulltext.search.exact",
              "value": "\"North Irish\"",
              "operator": "contains"
            },
            {
              "column_id": "fulltext.search.exact",
              "value": "\"Northern Ireland\"",
              "operator": "contains"
            },
            {
              "column_id": "fulltext.search.exact",
              "value": "\"Northern Irish\"",
              "operator": "contains"
            },
            {
              "column_id": "fulltext.search.exact",
              "value": "\"United Kingdom\"",
              "operator": "contains"
            },
            {
              "column_id": "fulltext.search.exact",
              "value": "\"english boys\"",
              "operator": "contains"
            },
            {
              "column_id": "fulltext.search.exact",
              "value": "\"english school\"",
              "operator": "contains"
            }
          ]
        },
        {
          "join": "or",
          "filters": [
            {
              "column_id": "title_and_abstract.search",
              "value": "attitude",
              "operator": "contains"
            },
            {
              "column_id": "title_and_abstract.search",
              "value": "attitudes",
              "operator": "contains"
            },
            {
              "column_id": "title_and_abstract.search",
              "value": "beliefs",
              "operator": "contains"
            },
            {
              "column_id": "title_and_abstract.search",
              "value": "diaries",
              "operator": "contains"
            },
            {
              "column_id": "title_and_abstract.search",
              "value": "diary",
              "operator": "contains"
            },
            {
              "column_id": "title_and_abstract.search",
              "value": "experiences",
              "operator": "contains"
            },
            {
              "column_id": "title_and_abstract.search",
              "value": "in-depth",
              "operator": "contains"
            },
            {
              "column_id": "title_and_abstract.search",
              "value": "indepth",
              "operator": "contains"
            },
            {
              "column_id": "title_and_abstract.search",
              "value": "informal",
              "operator": "contains"
            },
            {
              "column_id": "title_and_abstract.search",
              "value": "open",
              "operator": "contains"
            },
            {
              "column_id": "title_and_abstract.search",
              "value": "perceptions",
              "operator": "contains"
            },
            {
              "column_id": "title_and_abstract.search",
              "value": "perspective",
              "operator": "contains"
            },
            {
              "column_id": "title_and_abstract.search",
              "value": "perspectives",
              "operator": "contains"
            },
            {
              "column_id": "title_and_abstract.search",
              "value": "qualitative",
              "operator": "contains"
            },
            {
              "column_id": "title_and_abstract.search",
              "value": "semistructured",
              "operator": "contains"
            },
            {
              "column_id": "title_and_abstract.search",
              "value": "unstructured",
              "operator": "contains"
            },
            {
              "column_id": "title_and_abstract.search.exact",
              "value": "\"focus group\"",
              "operator": "contains"
            },
            {
              "column_id": "title_and_abstract.search.exact",
              "value": "\"focus groups\"",
              "operator": "contains"
            },
            {
              "column_id": "title_and_abstract.search.exact",
              "value": "\"lived experience\"",
              "operator": "contains"
            },
            {
              "column_id": "title_and_abstract.search.exact",
              "value": "\"open ended\"",
              "operator": "contains"
            },
            {
              "column_id": "title_and_abstract.search.exact",
              "value": "\"semi structured\"",
              "operator": "contains"
            }
          ]
        },
        {
          "join": "or",
          "filters": [
            {
              "column_id": "title_and_abstract.search",
              "value": "attitude",
              "operator": "contains"
            },
            {
              "column_id": "title_and_abstract.search",
              "value": "attitudes",
              "operator": "contains"
            },
            {
              "column_id": "title_and_abstract.search",
              "value": "beliefs",
              "operator": "contains"
            },
            {
              "column_id": "title_and_abstract.search",
              "value": "diaries",
              "operator": "contains"
            },
            {
              "column_id": "title_and_abstract.search",
              "value": "diary",
              "operator": "contains"
            },
            {
              "column_id": "title_and_abstract.search",
              "value": "experiences",
              "operator": "contains"
            },
            {
              "column_id": "title_and_abstract.search",
              "value": "interview",
              "operator": "contains"
            },
            {
              "column_id": "title_and_abstract.search",
              "value": "interviews",
              "operator": "contains"
            },
            {
              "column_id": "title_and_abstract.search",
              "value": "perceptions",
              "operator": "contains"
            },
            {
              "column_id": "title_and_abstract.search",
              "value": "perspective",
              "operator": "contains"
            },
            {
              "column_id": "title_and_abstract.search",
              "value": "perspectives",
              "operator": "contains"
            },
            {
              "column_id": "title_and_abstract.search",
              "value": "qualitative",
              "operator": "contains"
            },
            {
              "column_id": "title_and_abstract.search",
              "value": "questionnaire",
              "operator": "contains"
            },
            {
              "column_id": "title_and_abstract.search",
              "value": "questionnaires",
              "operator": "contains"
            },
            {
              "column_id": "title_and_abstract.search.exact",
              "value": "\"focus group\"",
              "operator": "contains"
            },
            {
              "column_id": "title_and_abstract.search.exact",
              "value": "\"focus groups\"",
              "operator": "contains"
            },
            {
              "column_id": "title_and_abstract.search.exact",
              "value": "\"lived experience\"",
              "operator": "contains"
            }
          ]
        }
      ]
    },
    "oxurl": null
  },
  {
    "id": 83,
    "category": "entity references",
    "provenance": {
      "type": "spec design",
      "label": "Collections-in-filters (oxjob #363; IA from #367)",
      "url": null
    },
    "oxurl_status": "has-oxurl",
    "status": "ok",
    "oql": "works where work is in collection col_abc123",
    "note": "Same-type membership: works that are members of a Collection of works. Renders to the dedicated `filter=collection:col_…` API param (CollectionField).",
    "diagnostic": "",
    "oqo": {
      "get_rows": "works",
      "filter_rows": [
        {
          "column_id": "collection",
          "value": "col_abc123",
          "operator": "in collection"
        }
      ]
    },
    "oxurl": "https://openalex.org/works?filter=collection:col_abc123"
  },
  {
    "id": 84,
    "category": "entity references",
    "provenance": {
      "type": "spec design",
      "label": "Collections-in-filters (oxjob #363)",
      "url": null
    },
    "oxurl_status": "has-oxurl",
    "status": "ok",
    "oql": "works where work is not in collection col_abc123",
    "note": "Negated membership rides the single `is_negated` bit (§3.5) → URL `collection:!col_…`.",
    "diagnostic": "",
    "oqo": {
      "get_rows": "works",
      "filter_rows": [
        {
          "column_id": "collection",
          "value": "col_abc123",
          "operator": "in collection",
          "is_negated": true
        }
      ]
    },
    "oxurl": "https://openalex.org/works?filter=collection:!col_abc123"
  },
  {
    "id": 85,
    "category": "entity references",
    "provenance": {
      "type": "spec design",
      "label": "Collections-in-filters (oxjob #363)",
      "url": null
    },
    "oxurl_status": "has-oxurl",
    "status": "ok",
    "oql": "works where author is in collection col_xyz789",
    "note": "Cross-type membership: works by authors in a Collection of authors. OQO keeps the referenced entity column; URL surface is the bare `<field>:col_…` (resolved by the cross-type pre-pass).",
    "diagnostic": "",
    "oqo": {
      "get_rows": "works",
      "filter_rows": [
        {
          "column_id": "authorships.author.id",
          "value": "col_xyz789",
          "operator": "in collection"
        }
      ]
    },
    "oxurl": "https://openalex.org/works?filter=authorships.author.id:col_xyz789"
  },
  {
    "id": 86,
    "category": "entity references",
    "provenance": {
      "type": "spec design",
      "label": "Collections-in-filters (oxjob #363)",
      "url": null
    },
    "oxurl_status": null,
    "status": "error",
    "oql": "works where country is in collection US",
    "note": "`is in collection` requires a col_… id, not a literal value — a loud error, never a silent miss.",
    "diagnostic": "OQL_BAD_COLLECTION_REF",
    "oqo": null,
    "oxurl": null
  }
];
